### ISSUE TITLE
Performance improvement: Tag "RawString" for string no need to escape

### ISSUE THREAD

**Issue by cesco69** [samchon/typia#1000]
typia lose time on string escaping. The idea is introduce a tag for specify string that no need to be escaped, eg
```ts
import { tags } from "typia";

interface MyInterface {
  token: string & tags.RawString;
}
```
if a string is "raw", the serialization is just

```ts
export const $string = (str: string, isRaw?: boolean): string => {
    if( isRaw ){
        return '"' + str + '"'
    }
    // ...
}
```

**Comment by samchon** [comment]
Well, in that case, validation would be slower. 

Therefore, there would not be any merit for the `typia.json.assertString<T>()` function case.
