### ISSUE TITLE
Is Typia a AOT compiler to native binary for TypeScript?

### ISSUE THREAD

**Issue by Foxchandaisuki** [samchon/typia#1003]
or is it AOT compiler to JavaScript for TypeScript?

**Comment by samchon** [comment]
What do you mean?

**Comment by Foxchandaisuki** [comment]
Typia가 C, Go, Rust 컴파일러같이 프로그래밍 언어(타입스크립트)를 기계어로 컴파일하는 컴파일러인지, 아니면 타입스크립트를
자바스크립트로 컴파일하는 건지 여쭤본 겁니다. 의미 전달이 잘 안 된 것 같네요. 죄송합니다.

2024년 3월 12일 (화) 오후 7:30, Jeongho Nam ***@***.***>님이 작성:

**Comment by samchon** [comment]
타입스크립트가 자체 제공하는 컴파일러 api와 ast 구조를 사용, 새로운 타입스크립트 타입을 심어주는 구조입니다. 러스트 매크로와 유사합니다.
