### ISSUE TITLE
Unable to Perform Assertions on Extended Array Types.

### ISSUE THREAD

**Issue by uanid** [samchon/typia#1004]
## Bug Report

Example code:

```typescript
interface RedisJSONArray extends Array<RedisJSON> {}
interface RedisJSONObject {
  [key: string]: RedisJSON;
  [key: number]: RedisJSON;
}
type RedisJSON = null | boolean | number | string | Date | RedisJSONArray | RedisJSONObject;

const myArray = ['foo', 'bar', 'baz'];
typia.assert<Array<RedisJSON>>(myArray);
console.log('-------------------------')
typia.assert<RedisJSONArray>(myArray);
```

### 📝 Summary
Write a short summary of the bug in here.

  - **Typia Version**: 5.5.4
  - **Expected behavior**: pass all assertion functions. 
  - **Actual behavior**:  second assertion does not pass.

### ⏯ Playground Link

> https://typia.io/playground/?script=JYWwDg9gTgLgBDAnmYBDANHA3g1BzAZzgF84AzKCEOAIiRVRoG4AoF4AOxgFMozUAxtzgAlbgBNgBAFIBlAPIA5AIJQoqRHG4APHh3FFV6xAB4xkmQsUA+bMXZde-IaIlS5S+QCMAVtwHwWCxwIXAA2gDW3IgAXHAEMFCceAC6cebuVqyh4VGxcBwAriBevGmuFh6KrPb0whmWSnAAvAWFADbtcAA+cF4QEO3cqBw9bSW8YwlJHHhjACKoPGMNVUYaK26Nit5+AaxsAhAcCXAgiOuarWEA5GQDN5g3XqhQj3DPqABeNyms9GgAHSoAgEXgwEyXMxbKrWawACnOlwAlKwjidBtxAe0IHh4TcALRE4kk0lkkk3ZEsAGoYGg8HQypWS4IpFqDSothAA

### 💻 Code occuring the bug
```typescript
interface RedisJSONArray extends Array<RedisJSON> {}
```

**Comment by samchon** [comment]
Do not inherit Array please. 

If you do that, it is not an Array type, but just an Obect type which has dynamic accessor of number key.

Even in the v8 engine, it is not an Array, but just becomes `map<string | number, any>` type.

**Comment by uanid** [comment]
@samchon 

I agree that inheriting from Array is not a good practice. However, the code in issue isn't something I wrote. It's a type defined in the node-redis library, as seen here: https://github.com/redis/node-redis/blob/dbf8f59a47573e6a1c75b78e566af8c493015d5d/packages/json/lib/commands/index.ts#L73.

If you're looking to validate such types, what would be the best approach?

**Comment by samchon** [comment]
Then wait for next v5.5.5 update. Will consider the other way.

**Comment by samchon** [comment]
Upgrade to v5.5.5, then be supported.
