### ISSUE TITLE
Provide a way to use typia directly without build step as alternative

### ISSUE THREAD

**Issue by loynoir** [samchon/typia#1006]
## Feature Request

Provide a way to use typia directly without build step as alternative

## Comparison

- `jsonschema` is good, but ugly to read and write, one can use `ajv` validator with or without build step

- `@sinclair/typebox` generate subset of jsonschema, and reflect awesome types from definition, provides validator without build step. But does not provide easy way to use it AOT.

- `typia` is awesome at very easy for typescript user, and provides AOT. But seems must AOT.

## Thought

I think, it  will be more awesome  if provide an easy way to use typia without build step.

## Additonal

If I remember correctly, both ajv and typebox use `new Function()` approach.

**Comment by samchon** [comment]
No way without AOT inn typia.

**Comment by loynoir** [comment]
Maybe a nodejs loader?

https://nodejs.org/docs/latest/api/module.html#hooks

Something like https://github.com/privatenumber/tsx?tab=readme-ov-file#%EF%B8%8F-quick-start

```sh
$ npx tsx ./script.ts
```
Compilation is done within loader `async load()` when needed, user don't need to run build command.

```sh
$ export NODE_OPTIONS='--loader typia-loader --loader loader-from-tsx'
```

```
$ node ./script-use-typia-directly-without-compile.ts
```
