### ISSUE TITLE
Any Stringified<T> type for JSON.stringify() in typia?

### ISSUE THREAD

**Issue by tungrix** [samchon/typia#1013]
I am reading a stringified from somewhere else and wish to declare its type before `JSON.parse()`, so `x` won't be any type.
```javscript
interface Foo {
  x: number;
  y: string;
}
const foo: Stringified<Foo> = "{x:3,y:'abc'}"
const x = JSON.parse(foo)
```
Is there any similar type in typia can achieve this? [Reference](https://github.com/Microsoft/TypeScript/issues/19244)

**Comment by samchon** [comment]
Will you design the `Stringified<T>` type? I can't imagine it.

**Comment by samchon** [comment]
Close due to too much time waiting.
