### ISSUE TITLE
Unclear instruction on how to use Typia

### ISSUE THREAD

**Issue by tnhh00037** [samchon/typia#1017]
I'm interested in Typia. However I am struggling finding how to use Typia via its official document. I can list a few

1. No clear instruction on how to compile typescript to javascript
Tried to look for way to do this, but I couldn't find any related information. 
Eventually I tried to build typescript by `npx tsc` as I normally do and it worked
I think it's better to mention this information somewhere in the document

2. No mention about whether need to build everything to javascript before running it, or can run directly typescript file with popular libraries like `ts-node` or `ts-node-dev`

2. No instruction on how to build `.proto` file
I saw document mentioned about protobuf support. And again, no clear mention about whether Typia can help user generate `.proto` file or not. And if yes, how to do it.

I suggest adding step-to-step instruction (including commands) to use each feature.
Also it would be great if there is sample repository to let user clone and try using Typo

Thank you for you hardwork!

**Comment by samchon** [comment]
Hope your contribution.

**Comment by samchon** [comment]
Close due to no contribution.
