### ISSUE TITLE
nested query string

### ISSUE THREAD

**Issue by masoudesm** [samchon/typia#1018]
## Feature Request
Imagine we want to have a shape like below when we have parsed query string:
```
interface Address {
  id: number;
  city: string;
  coordinate: {
    lat: number;
    lon: number;
  }
}

interface Person {
  firstName: string;
  lastName: string;
  age: number;
  address: Address;
}

interface IQuery {
  limit?: number;
  enforce: boolean;
  values?: string[];
  atomic: string | null;
  indexes: number[];
  person: Person;
}

```

currently it saying `Error on typia.http.createQuery(): no transform has been configured.`
but what I wanted is to be able to query like this in my query string `person.address.id=2`, how I can do that, if it is not supported, how I can add this, I really like to contribute if I can help. thanks a lot for creating this library.

**Comment by samchon** [comment]
Not possible. If you want to do that, use request body.

**Comment by masoudesm** [comment]
I don't want to use body (it is a query string), have created a typescript type which will create those nested keys with dot in each level, can I integrate it, or it would not be feasible.

**Comment by samchon** [comment]
Unfortunately, query string spec does not contain the nested object type.

If you write `person.address.id=2` statement, it means `obj["person.address.id"] = 2` in the query string spec.

Therefore, no way to support your suggestion.

**Comment by masoudesm** [comment]
I understand what you mean, but I have Java and hibernate background also, look at this link [Filtering your entities With Query Criteria](https://www.jhipster.tech/entities-filtering/), I want to do something like that, with my ORM criteria from the query string. :), if it needs development, I will do it, just need your guidance :)

**Comment by masoudesm** [comment]
I can write that function which do the transformation from `person.address.id` to `obj['person']['address']['id']` or `obj.person.address.id` but I prefer to do it AOT with a ts plugin as in yours. or even in your plugin

**Comment by masoudesm** [comment]
and I will have mongo or some other query criteria which I prefer to integrate to. I hope I said my idea well. it will be really cool and useful, I have never seen this feature of QueryCriteria from JPA in typescript and nodejs world, so I want to add it.

**Comment by samchon** [comment]
It's because Java Hibernate way is not standard, but one of anti pattern. 

I'm sorry but, I don't have plan to develop such anti pattern feature.

**Comment by masoudesm** [comment]
Thanks, I see, but Java Persistence API is not 100% an anti pattern, and in any case it is a need to do this criteria from query string to database (or we do in graphql via Queries), I just wanted to have a generic solution like they did in [Nestjs-Query](https://doug-martin.github.io/nestjs-query/) for graphql, because in any case we try to limit or filter a REST resource from query string, but again thanks, I will find a way for it. I wanted to avoid writing trivial code instead of writing `filterByAddressId` criteria as we know what is the interface we can create the criteria, using `.` is just a naming we could camelCase and join the keys. I see if I can add, will share again if you are interested. all the best...
