### ISSUE TITLE
localhost:port is not a valid url

### ISSUE THREAD

**Issue by Devidian** [samchon/typia#1036]
### 📝 Summary
When using `string & Format<'url'>` validation fails if host is localhost+port

  - **Typia Version**: 4.1.2
  - **Expected behavior**: localhost:port should be valid
  - **Actual behavior**: its not

I just updated some interfaces and started using Format<'url'> in some cases. My local test environment has no real domains, so the url's i am using look like `http://localhost:18050/rtb/notice/billing/6620ffda328b9ee43fb233eb/1/65f94adc1f8b387528c9c64a`. But what i get in response is a Bad Request.
I tested it in the playground to verify, see link below. If you just exchange the localhost:18050 with something like `api.mydomain.com` it passes.

### ⏯ Playground Link
https://typia.io/playground/?script=JYWwDg9gTgLgBDAnmYBDANHA3g1BzAZzgF84AzKCEOAIiRVRoG4AoF4AOxgFMozUAxtzgBJALLcQAI17YWcOMAAmALjgEYUTnjgAyXIQB0AMWghUMADw0ArjeU0AfKwUdUIbmo1aOeF3AALKm4wfE91TW09AwITMwtLAHIbKAAbROd5ODC1DhtpWV0shRh8WIAVZG5rey4AZgAmJz1imMMxTlB8ywaABkcWhRKywwBRAA8BVJsCYAA3bjFUca6QSwBGXv7WYjYBCA4NOA8CqDVxSRkoOABeBGQ0QyhUDiUqSwvTxwAKAEpWE5XQxBDyhPDCO40AIwGBgFQAenhqQgAlQqSCGhU6wAHL0AKy9eGwKTwjgQGDAITwqTAVKpbTwgBsjL6ZDISlQjWxUgAnNxuAAWOpkKQNOp1bgk9ZMvFkHkC1BKATrMjcurYgDseIa2IEPIEjIVzBY+0O8AEAW4AgA1mopBAIKluC9bvcGIZgARvoDeP8TQcjgArAgHLyRXyu+iPYMHQzebTAMiIb2XX2sU1HGluKCINQAVU4MGxAEEoM9EJGHqhDGBKDAIFIbGRDNwOPslNwU6c-f7Do7uIZkXhvlgsj6oOgshardbJwoYxw53As6gc5PiP84CwgA

### 💻 Code occuring the bug
```typescript
import typia, { tags } from "typia";

interface IMember {
  id: string & tags.Format<"uuid">;
  name: string;
  homepage: string & tags.Format<'url'>;
  age: number &
    tags.Type<"uint32"> &
    tags.Minimum<20> &
    tags.ExclusiveMaximum<100>;
}

const member: IMember = typia.random<IMember>();
member.homepage = "http://localhost:18050/rtb/notice/billing/6620ffda328b9ee43fb233eb/1/65f94adc1f8b387528c9c64a";
const check: boolean = typia.is(member);
const json: string = typia.json.stringify(member);
const binary: Uint8Array = typia.protobuf.encode(member);

console.log({
  member,
  check,
  json,
  binary,
}); 
```

**Comment by samchon** [comment]
It is the spec of `url` format.

If you want to allow the localhost text, use `uri` format instead.

**Comment by Devidian** [comment]
Ok pardon, did not check the spec, thought localhost is valid. I'll give uri a try, thanks.
