### ISSUE TITLE
Why I can't generate custom tags from a shared package?

### ISSUE THREAD

**Issue by dror-weiss** [samchon/typia#1039]
## Question

I'm trying to share `typia` custom tags in a different package, but I can't generate the validation.
It's probably about naming of the imports but I can't seem to find a way to make it work.

This works:
```ts
import typia from 'typia';

const a = typia.createAssert<Settings>();

export type Settings = {
    domain: string & typia.tags.MinLength<20>;
};
```

This doesn't get generated
```ts
import typia from 'typia';
import {typiaTags} from '@company/package';

const a = typia.createAssert<Settings>();

export type Settings = {
    domain: string & typiaTags.MinLength<20>;
};
```

Any idea why?

My end goal is to share entire `typia` and custom tags from my other package, meaning:
```ts
import {typia, typiaTags} from '@company/package';

const a = typia.createAssert<Settings>();
//...
```

**Comment by samchon** [comment]
Can you provide me a reproducible repo with the custom package?

I am also doing same thing with you, and in my case, it works properly.

**Comment by samchon** [comment]
Close due to too much time reproducible repo waiting.
