### ISSUE TITLE
Simpler NestJS use case

### ISSUE THREAD

**Issue by RDeluxe** [samchon/typia#1046]
## Feature Request
Hello there!

I found out about Typia and I'm excited to try it out. However for some of our projets I would prefer to add Typia on top of Nest via a simple Pipe, rather than installing Nestia and replacing all NestJS default routing system.

I could probably do a PR to add this to the official documentation, as an "alternative and less magical" way to add Typia to an existing NestJS project. But I was wondering if you had a simple implementation in mind.

**Comment by samchon** [comment]
You don't need to replace whole NestJS routing system.

Nestia is just helper library of NestJS, so that compatible with it.

Just choose what you want.
