### ISSUE TITLE
Use a `Set` on primitive type unions to verify if they are valid

### ISSUE THREAD

**Issue by ImUrX** [samchon/typia#1054]
## Feature Request
Imagine a type for example a type called `Alpha3Code` which contains an union of strings of all valid [ISO 3166-1 alpha-3](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3#Officially_assigned_code_elements).

The validation currently would just generate a comparison check for each primitive by doing a lot of logical ORs like this:
```js
"ABW" === input.country ||
"AFG" === input.country ||
"AGO" === input.country ||
"AIA" === input.country ||
"ALA" === input.country
// etc...
```

But `typia` could generate a `Set` based on all the types and simply do `set.has(input.country)` instead which would be much more optimized.

**Comment by samchon** [comment]
It seems good idea, but needs entire level refactoring of compiler related codes.

This feature would be adjusted to the v7 major update, so please wait for some months.

By the way, if the number of constant literal values are lower, using `Set<T>` strategy becomes slower than current individual comparisons. Therefore, need to determine the standard number whether to use `Set<T>` strategy or not. About the count, do you have any idea? If not, I'll determine it after measuring a benchmark.

**Comment by ImUrX** [comment]
If we are talking about same length text, I'm betting around 10, but yes a benchmark seems like a good idea specially for the other cases.

There is other optimizations that could be done depending on type, like strings could also have their min and max length taken for checking before looking them up and numbers could do the same by taking their min and max number which are all cheaper operations compared to a Set lookup but that should be another issue.
