### ISSUE TITLE
How can I discriminate union types with optional properties?

### ISSUE THREAD

**Issue by ChapterSevenSeeds** [samchon/typia#1058]
Let me start out by saying that I love Typia with all my heart. It has been a great help to me in multiple projects.

Now, suppose you have the following code:
```ts
import { createIs } from 'typia';

type Type1 = {
    value?: string | null
};
type Type2 = {
    property?: string | null;
};

const isType1 = createIs<Type1>();
const isType2 = createIs<Type2>();

const obj1: Type1 | Type2 = {
    value: "value"
};
const obj2: Type1 | Type2 = {
    property: "property"
};

if (isType1(obj1)) {
    console.log("obj1 is Type1");
} else if (isType2(obj1)) {
    console.log("obj1 is Type2");
}

if (isType1(obj2)) {
    console.log("obj2 is Type1");
} else if (isType2(obj2)) {
    console.log("obj2 is Type2");
}
```

The compiled version of this code looks like this:
```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var typia_1 = require("typia");
var isType1 = function (input) {
    var $io0 = function (input) { return null === input.value || undefined === input.value || "string" === typeof input.value; };
    return "object" === typeof input && null !== input && false === Array.isArray(input) && $io0(input);
};
var isType2 = function (input) {
    var $io0 = function (input) { return null === input.property || undefined === input.property || "string" === typeof input.property; };
    return "object" === typeof input && null !== input && false === Array.isArray(input) && $io0(input);
};
var obj1 = {
    value: "value"
};
var obj2 = {
    property: "property"
};
if (isType1(obj1)) {
    console.log("obj1 is Type1");
}
else if (isType2(obj1)) {
    console.log("obj1 is Type2");
}
if (isType1(obj2)) {
    console.log("obj2 is Type1");
}
else if (isType2(obj2)) {
    console.log("obj2 is Type2");
}

```

Because the properties in `Type1` and `Type2` are optional, the code generated by Typia fails to discriminate between the two types. Now, since the properties in both these types are different, I would argue that `obj1` is definitely not an instance of `Type2` nor is `obj2` an instance of `Type1`. But, when running the code, you get the following output:
```
obj1 is Type1
obj2 is Type1
```

The current workaround I'm using involves making all properties required. Could there be some added benefit to creating an `isStrict` method that rejects objects that have properties that don't exist in the type?

**Comment by samchon** [comment]
In that case, you should add significant discriminator property.

The discriminator property will make it clear.

If you don't do that, no way in your type case.

https://typia.io/playground/?script=JYWwDg9gTgLgBDAnmYBDOAzKERwORIqp4DcAUGYQKZwAqyVAjHALxwDeZccA1sAHYATAFxwARADdUAGwCuVMeW5S5VAPyiAzjCgCA5nAA+cfrOnSyAX3LU6DAEysOXXgJHiw2MFViJFLzwhvXw04bV1+A2NTc3JrCkI0ADoAYygqVBgqAElNAB56b2ZjQqp7AD4ACgBKEiA
