### ISSUE TITLE
remove Namespacee for tree shaking

### ISSUE THREAD

**Issue by ryoppippi** [samchon/typia#1069]
## Feature Request

Related to https://github.com/samchon/typia/issues/1063

Typescript's `namespace` is great, but this is not good for tree shaking.

### with namespace
When you use vite for bundler, this code

```ts
namespace calc {
  export function add(a: number, b: number): number {
    return a + b;
  }

  export function sub(a: number, b: number): number {
    return a - b;
  }
}

console.log(add(1,2))
```

bundled like this

```ts
var calc;
((calc2) => {
  function add(a, b) {
    return a + b;
  }
  calc2.add = add;
  function sub(a, b) {
    return a - b;
  }
  calc2.sub = sub;
})(calc || (calc = {}));
console.log(calc.add(1, 2));
```

### without namespace

However, if you do not use namespace

```ts
  export function add(a: number, b: number): number {
    return a + b;
  }

  export function sub(a: number, b: number): number {
    return a - b;
  }

console.log(add(1,2))
```

the bundle is like this↓

```ts
function add(a, b) {
  return a + b;
}

console.log(add(1, 2));
```

Or you can split the codebase and use [Namespace Import](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Statements/import#import_an_entire_modules_contents):

calc.ts
```ts
export function add(a: number, b: number): number {
  return a + b;
}

export function sub(a: number, b: number): number {
  return a - b;
}
```

index.ts
```ts
import * as calc from "./calc.js";

console.log(calc.add(1, 2));
```

the bundle result here↓

```ts
import { add } from './calc.js';

console.log(add(1, 2));
```

**Comment by samchon** [comment]
I'm developing it on v7 update advised by https://github.com/samchon/typia/issues/752

Wait for next 3 to 4 months please.

**Comment by ryoppippi** [comment]
If you need it, I'll help you!
Currently I have time to work on it

**Comment by samchon** [comment]
Thanks for helping me, but this issue needs my working, due to it needs entire compiler API level refactoring.

**Comment by ryoppippi** [comment]
OK! Thanks.
So, I wait for that! Thanks

**Comment by ryoppippi** [comment]
The namespace has almost disappeared at the implementation level, so this issue is good to close
Also, tree-skaing of named import/export works well with this https://github.com/samchon/typia/pull/1133

However, `random` function is not optimized yet. 

Other things are fine.

So I'll create a new issue for this specific topic!
