### ISSUE TITLE
Bun build support

### ISSUE THREAD

**Issue by ryoppippi** [samchon/typia#1078]
## Feature Request
Thanks for your suggestion. Feel free to just state your idea. Writing the issue, it would better to filling the below items:

  - A description of the problem you're trying to solve.
  - An overview of the suggested solution.
  - Examples of how the suggestion would work in various places.
    - Code examples showing the expected behavior.

`randexp.js` and thier dependency `DRange` is complied by old CJS.
It works fine with node.js, but `bun build` fails bundling ( I know `typia` does not support bun officially)

Related: https://github.com/ryoppippi/unplugin-typia/issues/44

For solving, I'll implement an alternative of `randexp.js` 

(This is just suggestion. If you do not want it, close this issue)

**Comment by samchon** [comment]
If you can fully replace it, I don't matter.

**Comment by ryoppippi** [comment]
@samchon 
No I found another solution.
I'll create a PR.
