### ISSUE TITLE
Why we need `ts-node` for setup

### ISSUE THREAD

**Issue by ryoppippi** [samchon/typia#1083]
## Question

I apologise if this has been asked many times, but I asked this question because I couldn't find it when I looked for it.
Why does the Setup section ask me to install `ts-node`?
I read the code in the typia command tools, but it didn't seem to be running ts-node.

**Comment by samchon** [comment]
The library requires `ts-node` is not `typia` but `nestia`. 

This is just my mistake.

**Comment by samchon** [comment]
I should upgrade the setup wizard not to install the `ts-node`.
