### ISSUE TITLE
You need a better explanation of what typia is/does

### ISSUE THREAD

**Issue by axefrog** [samchon/typia#1103]
On your website's landing page:

- "Only one line" -- Only one line of what? To do what?

- "No extra schema required" -- Extra schema? What extra schema? We need a schema for something? What is typia? What does it have to do with schemas?

- "Just fine with pure TypeScript type" -- Oookay? I still have no idea what typia is, so I don't know how this benefit relating to TypeScript types is relevant to anything.

- "`typia.assert<T>(input);`" -- I can see that you're making a point about conciseness here. Conciseness is good. But I still don't know what typia is or how it helps me, so demonstrating how concise it is is premature.

Then, further below:

- "Super-fast Runtime Validator" -- Speed is good. So I guess typia is faster than whatever it's competing against? But I still don't know what typia is. Is it a validator, or does it _have_ a validator? What's it validating? Is validation the main feature, or is it just something that's an important part of what it does? _What is typia?_

- "Fast JSON Serialization" -- Again, same thing. I don't know what typia does, so the fact that it has fast JSON serialization isn't helping me judge its efficacy in addressing my needs.

Anyway you get the picture. I get the impression that your landing page has started with an assumption that someone arriving there is already aware of your product and is looking for a solution that they know typia could possibly help with.

But what about people who don't know what typia is? I am a developer in the broader AI space, and I was recently sent a link (among many I frequently receive) to the typia homepage, but I found myself frustrated because I felt like I was looking at something that could be useful to me, and yet even after reading through the whole landing page, I still had no idea what was being offered. My suggestion is to drop all assumptions about who you're talking to, and pretend that the only thing you know is that you're talking to a developer and that they probably know what TypeScript is. But that's it. Therefore, your landing page should start with something short and to the point that expresses what problem you're solving and who it's for. Make sure that by the time I reach the feature list, I already know whether or not typia is relevant to me, even if I have never done any development in the space that typia is targeting.

**Comment by samchon** [comment]
Not easy mission \o/. 

To accomplish this issue, I have to entirely remake the intro page.

May need lots of time to start.

**Comment by ryoppippi** [comment]
@samchon 
How about enable discussion feature for this Repo and move this issue there.
