### ISSUE TITLE
Wrap Generics

### ISSUE THREAD

**Issue by dan-fritchman** [samchon/typia#1107]
Great project, thanks for all of your work on it!  

Question: typia has many generic functions which (I think) require a type-literal at their call site.  
The snippet below uses `createValidate` as an example.  

The goal: I would like to be able to call them from my own generic functions, e.g.: 

```typescript
import typia from "typia";

type A = { a: string };
type B = { b: number };

// The point: try to pass a generic argument to `createValidate`
function wrapCreateValidate<T>() {
  return typia.createValidate<T>();
}

const a = wrapCreateValidate<A>();
const b = wrapCreateValidate<B>();
```

Generates:

```
src/test_typia_stuff.ts:8:10 - error TS(typia.createValidate): non-specified generic argument.

8   return typia.createValidate<T>();
```

The question: is there a way to make something like that work?

**Comment by samchon** [comment]
Too much repeated question, but no way to implement it.

**Comment by dan-fritchman** [comment]
Understand, thanks!
