### ISSUE TITLE
Prisma JsonArray causes infinite loop

### ISSUE THREAD

**Issue by tjhiggins** [samchon/typia#1121]
### 📝 Summary
I'm using Prisma with Nestjs and Nestia. One of my fields in a model is causing issues for `nestia swagger`:
```prisma
items Json[] @default([])
```

  - **Typia Version**: 6.2.1
  - **Expected behavior**: Nestia generates the swagger docs
  - **Actual behavior**: Nestia swagger hits an infinite loop in typia trying to generate schema for Prisma ArrayJsonValue

I was pinned to Typia 5.5.4 for awhile because of this issue, but have since upgraded and pnpm patched the application_array.js to use the latest version. https://github.com/samchon/typia/pull/1005 seems to have been the culprit. Here is my current workaround via a pnpm patch:

```
diff --git a/lib/programmers/internal/application_array.js b/lib/programmers/internal/application_array.js
index 042af654f861c07a56ecbda9a19f2fc37ec2267f..1d0b576814fa7ed75a9633877c8a28a214fffaa1 100644
--- a/lib/programmers/internal/application_array.js
+++ b/lib/programmers/internal/application_array.js
@@ -9,7 +9,7 @@ var application_array = function (generator) {
     return function (array) {
         return (0, application_plugin_1.application_plugin)({
             type: "array",
-            items: generator(array.type.value),
+            items: array.type.name === 'ArrayJsonValue' ? [] : generator(array.type.value),
         }, array.tags);
     };
 };
```

### ⏯ Playground Link
https://typia.io/playground/?script=JYWwDg9gTgLgBDAnmYBDOAzKERwERIqp4DcAUGYQKZwBSAzhAHYDyARgFZUDG8AvHADeAbQDSVRHGBM49GFGkBzALoB+AFx1GTAGqoANgFcqAX0rIaDZnqM0BchU0VwAPnCaGQbKlFdw2EBD6VKgyblasnDzw4doAglBQqJJuHvr6ZNIwPhio3JbxiclwVAAe2UwAJvRwCUmIADwRNsYAfEJmmUzZULn5cACSALJUXj5CZHBS2SD0mhF1yeSd3MxycCCj3lCaw1vjAoRoAHRJVTgNe2NQrQAUAJTkq0zr3AAWPADWmgFBITKHZAnYD0W6ba6PMjPdYcbSaBxKOCAojHWHMY4IpzADCIMH7KCQgD0hOh8DY0lQUEQmgAqlkAByLSTIk5gbAwCBsQwYY5UJirSpUPEQ8hQtZ-Y76CCKW6CSYbfEAGnl7y+yqmaKY6rgxPJTEpiGVJkecDIQA

I couldn't even save the playground with `binary` uncommented because it also causes an infinite loop. 

To reproduce the issue:
1. Uncomment `binary` and run

### Stack trace
```bash
# npx nestia swagger
RangeError: Maximum call stack size exceeded
    at /home/tj/code/accelerait/accelerait/api/node_modules/.pnpm/typia@6.2.1_typescript@5.4.5/node_modules/typia/src/programmers/internal/application_v31_schema.ts:26:3
    at /home/tj/code/accelerait/accelerait/api/node_modules/.pnpm/typia@6.2.1_typescript@5.4.5/node_modules/typia/src/programmers/internal/application_array.ts:19:43
    at /home/tj/code/accelerait/accelerait/api/node_modules/.pnpm/typia@6.2.1_typescript@5.4.5/node_modules/typia/src/programmers/internal/application_v31_schema.ts:71:71
    at /home/tj/code/accelerait/accelerait/api/node_modules/.pnpm/typia@6.2.1_typescript@5.4.5/node_modules/typia/src/programmers/internal/application_array.ts:19:43
    at /home/tj/code/accelerait/accelerait/api/node_modules/.pnpm/typia@6.2.1_typescript@5.4.5/node_modules/typia/src/programmers/internal/application_v31_schema.ts:71:71
    at /home/tj/code/accelerait/accelerait/api/node_modules/.pnpm/typia@6.2.1_typescript@5.4.5/node_modules/typia/src/programmers/internal/application_array.ts:19:43
    at /home/tj/code/accelerait/accelerait/api/node_modules/.pnpm/typia@6.2.1_typescript@5.4.5/node_modules/typia/src/programmers/internal/application_v31_schema.ts:71:71
    at /home/tj/code/accelerait/accelerait/api/node_modules/.pnpm/typia@6.2.1_typescript@5.4.5/node_modules/typia/src/programmers/internal/application_array.ts:19:43
    at /home/tj/code/accelerait/accelerait/api/node_modules/.pnpm/typia@6.2.1_typescript@5.4.5/node_modules/typia/src/programmers/internal/application_v31_schema.ts:71:71
    at /home/tj/code/accelerait/accelerait/api/node_modules/.pnpm/typia@6.2.1_typescript@5.4.5/node_modules/typia/src/programmers/internal/application_array.ts:19:43
    at /home/tj/code/accelerait/accelerait/api/node_modules/.pnpm/typia@6.2.1_typescript@5.4.5/node_modules/typia/src/programmers/internal/application_v31_schema.ts:71:71
    at /home/tj/code/accelerait/accelerait/api/node_modules/.pnpm/typia@6.2.1_typescript@5.4.5/node_modules/typia/src/programmers/internal/application_array.ts:19:43
    at /home/tj/code/accelerait/accelerait/api/node_modules/.pnpm/typia@6.2.1_typescript@5.4.5/node_modules/typia/src/programmers/internal/application_v31_schema.ts:71:71
    at /home/tj/code/accelerait/accelerait/api/node_modules/.pnpm/typia@6.2.1_typescript@5.4.5/node_modules/typia/src/programmers/internal/application_array.ts:19:43
    at /home/tj/code/accelerait/accelerait/api/node_modules/.pnpm/typia@6.2.1_typescript@5.4.5/node_modules/typia/src/programmers/internal/application_v31_schema.ts:71:71
    at /home/tj/code/accelerait/accelerait/api/node_modules/.pnpm/typia@6.2.1_typescript@5.4.5/node_modules/typia/src/programmers/internal/application_array.ts:19:43
```

**Comment by samchon** [comment]
https://typia.io/playground/?script=JYWwDg9gTgLgBDAnmYBDOAzKERwERIqp4DcAUGYQKZwBSAzhAHYDyARgFZUDG8AvHADeAbQDSVRHGBM49GFGkBzALoB+AFx1GTAGqoANgFcqAX0rIaDZnqM0BchU0VwAPnCaGQbKlFdw2EBD6VKgyblasnDzw4doAglBQqJJuHvr6ZNIwPhio3JbxiclwVAAe2UwAJvRwCUmIADwRNsYAfEJmZNzMcnCoYGBwAoRoAHQc2qP9YPrA3KgwwMwNwhF1yQA0WtYGxlsR7Fy8yq0AFACU5N1MjMGj+hCKp9OXFCOoo9xQIdkAkvRNQr1M6vd7jSZfH5UADK8iUwAwjWauyoIJIQA

Working fine. What is the problem?

Can you copy and paste the breaking code?

**Comment by samchon** [comment]
Succeeded to make infinite loop condition:

```typescript
import typia from "typia";
interface JsonArray extends Array<JsonArray> {
  children?: JsonArray;
}

typia.json.application<[JsonArray]>();
```

https://typia.io/playground/?script=JYWwDg9gTgLgBDAnmYBDOAzKERwERIqp4DcAUMAHYwCmUGqAxjXAFIDOElAglFKojg0AHrUoATdnF79EAHg5cZAgHxwA3mThxGAC2AAbcVBqUA-AC42nHnwHkAvmTKE0AOgBWNt6jBgDwIyoMMBccgDairayALoqZEA

**Comment by samchon** [comment]
Upgrade to v6.2.2, then be fixed.

**Comment by tjhiggins** [comment]
> Upgrade to v6.2.2, then be fixed.

Thank you so much for the quick fix!
