### ISSUE TITLE
`https` url tag.

### ISSUE THREAD

**Issue by ryoppippi** [samchon/typia#1156]
## Feature Request
Hi! Thank you as always.
If we have `https only URL` tag, it is really useful for me

**Comment by samchon** [comment]
HTTPS only URL is not registered in the JSON schema's string format type. Therefore, it is not possible to support by `typia` as formal type. Instead, those chapters would be helpful. You can make your own validation (or JSON schema plugin type) easily like below:

- https://typia.io/docs/validators/tags/#customization
- https://typia.io/docs/json/schema/#customization

**Comment by ryoppippi** [comment]
Oh ok so combine with regret is really good option for this thanks!!
