### ISSUE TITLE
Unexpected output with discriminated union

### ISSUE THREAD

**Issue by soc221b** [samchon/typia#1160]
### 📝 Summary
Write a short summary of the bug in here.

  - **Typia Version**: 6.5.0
  - **Expected behavior**: log `false`
  - **Actual behavior**: log `true`

Write detailed description in here.

As title

### ⏯ Playground Link
https://typia.io/playground/?script=JYWwDg9gTgLgBDAnmYBDOAzKERwERIqp4DcAUGYQKZwAiVVYtwAzgMZSjAB2qMVAEwCq3YBG5wAvHADeZOAmRUAXHADkqUSFQAbNeQUCGYZfIVwAPrLPnz1VWoEQA5vpu24AI1RQA1qoAKAEopAD5ZAF8DDwj3KzkPOyUHNj43RIUQKggAd0CQyXCZKPcFEpKyNnEWeB4wAFd4aQTFMBV1TVBdNQAaMyNGVRaFe3UnVz7bLNz8sMjJuAi+2MrqiB0qADodFwDCNE2qAEd63RYAHnpGZnZOEB4+QRExblCAusagoJI4MgB6P5wcIwKD1Kg9OAsAAWEHqOgEXhoGDOVDIQA

### 💻 Code occuring the bug
```typescript
import typia from "typia";

type DeepDiscriminatedUnion = {
  type: 'animal';
  deep:
    | {
        type: 'dog';
        bark: () => {};
      }
    | {
        type: 'cat';
        meow: () => {};
      };
};

const input = {
  type: 'animal',
  deep: {
    type: 'dog',
    meow: () => {},
  },
}

console.log(typia.equals<DeepDiscriminatedUnion>(input)); 
// > true, should be false

```

Thank you for this amazing tool. :heart:

**Comment by samchon** [comment]
Default option configured `typia` does not validate functional property type.

To make your code work, you should configure `tsconfig.json` like below:

```json
{
  "compilerOptions": {
    "plugins": [
      {
        "transform": "typia/lib/transform",
        "functional": true
      }
    ]
  }
}
```
