### ISSUE TITLE
Why is the Bun plugin so much slower than the default tsc version?

### ISSUE THREAD

**Issue by kirankunigiri** [samchon/typia#1165]
## Question
Typia has been really awesome to use. I wanted to use it in a Bun project, but the dev experience for restarting my server on a file change (hot reload) during development is so much slower that it doesn't feel usable. In fact I even decided to switch back to tsc for my project just so I could use typia properly.

But I also wanted to know why exactly it is so much slower than tsc, and also if other plugins in general are just slower (or if it is just the Bun plugin for some reason).

Here is a simple benchmark I did with just the following example:
```typescript
typia.createIs<number>();
console.log(check(10));
```
- **Bun with Typia Plugin** - 0.4-0.6s generation
  - I added a time logger to the plugin source code to get the exact generation time
  - Because Bun doesn't support --watch with plugins, I had to use nodemon which added an additional 0.2-0.4s on file save. Which means the total time was almost 1s minimum, with reaching 2-3s when defining more complex interfaces
- **Node with `ts-node-dev --respawn`** - 0.1s max. I didn't even bother checking how much time the plugin itself was taking vs. ts-node-dev file watcher, because this is almost instantaneous. It's so much faster.

It would be interesting to know why there's such a drastic difference in times, if this is just a Bun issue or a plugin problem in general, and what possible improvements could be.

**Comment by samchon** [comment]
I don't know about bun (even have not used it at all).

So I'll toss this issue to @ryoppippi, the `unplugin-typia` developer.

**Comment by ryoppippi** [comment]
Related: https://github.com/ryoppippi/unplugin-typia/issues/197

This is not an issue with Typia. Most bundlers use hot module replacement (HMR) to cache individual JavaScript files, but Bun rebuilds all JavaScript files, including libraries, every time. 

I implemented caching feature for `unplugin-typia` but this plugin doesn't cache other libraries including `Typia` itself...

If you want a better developer experience (DX) with Bun, you should wait for the resolution of https://github.com/oven-sh/bun/issues/4689.

If you don't need to stick with Bun, I recommend using Vite in dev mode, which offers a superior hot reloading experience.

**Comment by kirankunigiri** [comment]
Thanks for the explanation! I'll hold off on using bun so I can keep using typia
