### ISSUE TITLE
How to use typia with hono framework, I get error Uncaught Error: Error on typia.createValidate(): no transform has been configured.

### ISSUE THREAD

**Issue by tin-pham** [samchon/typia#1177]
## Question
Hono have a page where it can use with typia, but I can't seem make this to work. https://github.com/honojs/middleware/tree/main/packages/typia-validator

Here is how I did it
1) Setup a normal hono app using the Getting Started: https://hono.dev/docs/getting-started/basic
2) Install typia
``` 
npm install typia @hono/typia-validator
```
3) Add some typia validation code according to hono doc: https://github.com/honojs/middleware/tree/main/packages/typia-validator
3) Run ``` npx typia setup ```
4) Run ``` npm run dev``` (It will run ```wrangler dev```)

Here is my full code: 
```
// blogs.controller.ts
import { Hono } from 'hono'
import type { BLOG } from './blogs.interface'
import { blogValidate } from './blogs.validate'

const blogs: BLOG[] = []

const blogController = new Hono()

blogController.get('/blogs', (c) => c.json({ data: blogs }))

blogController.get('/blogs/:id', (c) => {
	const { id } = c.req.param()
	const blog = blogs.find((data) => data.id === parseInt(id))
	return c.json(blog || { message: 'Blog not found' })
})

blogController.post('/blogs', blogValidate, async (c) => {
	const body = c.req.valid('json') as BLOG

	const newBlog: BLOG = {
		id: blogs.length + 1,
		title: body.title,
		content: body.content,
	}

	blogs.push(newBlog)
	return c.json(newBlog)
})

export { blogController }
```

```
// blogs.validate.ts
import { typiaValidator } from '@hono/typia-validator'
import typia from 'typia'
import { createMiddleware } from 'hono/factory'

export type BLOG = {
	id: number;
	title: string;
	content: string;
};

export const validate = typia.createValidate<BLOG>()

export const blogValidate = createMiddleware(
	typiaValidator('json', validate, (result, c) => {
		if (!result.success) {
			return c.json({ status: 400, message: 'Invalid data' })
		}
	}),
)
```

It will cause this error
```
✘ [ERROR] service core:user:hono-app: Uncaught Error: Error on typia.createValidate(): no transform has been configured. Read and follow https://typia.io/docs/setup please.
```
I try to search everywhere but it can't seem to work
The closest discussion is this: https://github.com/samchon/typia/issues/812, but nothing relate to my problem.

**Comment by ryoppippi** [comment]
Can you read the error message?
Have you EVER read the documantaion?
You haven't configured transformation. Therefore, the code causes error.
So you have three choices.
- execute `typia generate` manually (https://github.com/honojs/middleware/blob/e488b9f08acf6cdb756114831d7aa5e7da3fc8f7/packages/typia-validator/package.json#L12 or you can see this Japanese article https://zenn.dev/daichi2mori/articles/20240422-hono-validation-demo#typia)
- use `typia generate` for custom command in `wrangler.toml` (see https://developers.cloudflare.com/workers/wrangler/custom-builds/)
- use bundlers like `vite` with unplugin-typia (see https://github.com/ryoppippi/unplugin-typia/blob/1010c892e6c4f2f43ee331c0fcff72d8efe374a4/examples/vite-hono)

**Comment by tin-pham** [comment]
Thanks, i got it to work with the second choice, sorry for you inconvenient

**Comment by ryoppippi** [comment]
No worries! Cheers

**Comment by airtonix** [comment]
> Can you read the error message? Have you EVER read the documantaion? You haven't configured transformation. 

if you read in the OPs original message, they say: 

> npx typia setup

[The docs for typia say](https://github.com/samchon/typia/blob/master/website/pages/docs/setup.mdx?plain=1#L35) that this is all that's required.

And if you don't run this, then the docs say that manual setup is just: 

- install some deps
- modify your tsconfig to include `plugins`

What are you thoughts regarding `npx typia setup`
