### ISSUE TITLE
Invalid JavaScript is generated when using Index Signatures

### ISSUE THREAD

**Issue by colinaaa** [samchon/typia#1179]
### 📝 Summary
Write a short summary of the bug in here.

  - **Typia Version**: 6.5.3
  - **Expected behavior**:  Create a valid JavaScript
  - **Actual behavior**: Create an invalid JavaScript with SyntaxError

When using `typia` with [Index Signatures](https://www.typescriptlang.org/docs/handbook/2/objects.html#index-signatures), invalid JavaScript is generated:

```js
                        "string" === typeof value[0] || $report(_exceptionable, {
                            path: _path + $join(key[0]",
                            expected: "string",
                            value: value[0]
                        })
```

### ⏯ Playground Link

https://typia.io/playground/?script=JYWwDg9gTgLgBDAnmYBDOAzKERwERIqp4DcAUGcAHYwCmUGqAxrXAGIQRwDeZccYVDAAWAZwD8ALh59+cANpYc00TCjUA5gF1p81eqrby-AL7kTFJhCqq4AN1QAbYABMhtaQApqYAK4xpXyoAayoIAHcqAEo4AF4APgRkNAA6AEkANSdXIWBrAB4OCETY2UJUpihadyznNzoAUQBHXydRQs54zyjyMisbCEdaFMcIDU9efgc69wAaMhMesiA

### 💻 Code occuring the bug
```typescript
import typia from "typia";

interface Foo {
  paths?: {
    [from: string]: [string];
  };
}

const validate: (input: unknown) => typia.IValidation<Foo> =
  typia.createValidateEquals<Foo>();

console.log({
  validate,
});
```

**Comment by samchon** [comment]
Uprade to v6.5.5, then be fixed.

**Comment by colinaaa** [comment]
Thank you @samchon. It works like a charm.
