### ISSUE TITLE
How can I wrap typia in a library?

### ISSUE THREAD

**Issue by dror-weiss** [samchon/typia#1196]
Hi,

I'm trying to re-export typia in a utility library in my monorepo and I can't get it working with that setup. The error I get is "no transform has been configured" for a `createAssert` function.

It does work when I import typia directly.

Works:
```ts
import typia from 'typia';
...
const throwIfInvalidSomething = typia.createAssert<Something>();
```

Doesn't work:
```ts
import {typia} from '@company/schema'; // export {default as typia} from 'typia';
...
const throwIfInvalidSomething = typia.createAssert<Something>();
```

Any suggestions to what might cause this?

- unplugin-typia = 0.6.16, for esbuild
- typia = 6.7.0

**Comment by ryoppippi** [comment]
@dror-weiss sounds intersting.
Could you give us some minimal reproduction repo?

**Comment by dror-weiss** [comment]
Ok, so it definitely not a bug and totally my fault: I misunderstood the deployment flow which didn't apply the plugin on the deployment script but did apply it on a serverless function.

Closing.
