### ISSUE TITLE
TypedFormData.Body throw me error

### ISSUE THREAD

**Issue by sacru2red** [samchon/typia#1230]
### 📝 Summary
Write a short summary of the bug in here.

  - **Typia Version**: 6.8.0
  - **Expected behavior**: No Errors 
  - **Actual behavior**: 
throw error

error TS(nestia.core.TypedFormData.Body): unsupported type detected
- FormBodyDto.foo: (global.File | string)
  - only atomic, constant or blob (file) types are allowed in array.

```ts
type FileOrString = Array<File | string>
type FormBodyDto = {
    foo: FileOrString
}
```

Write detailed description in here.

### ⏯ Playground Link
https://typia.io/playground

Visit above playground and write code occuring the bug.

After that, copy and paste link address of that.

https://typia.io/playground/?script=JYWwDg9gTgLgBDAnmYBDOAzKERwERIqp4DcAUGYQKZwBiwANlQPJQDKMUwAdgOZwBeOAEEoUVIgA89JnAA+cAM6cevAHyVkNWtBAAhCABNEAERgRBcAN5k4dzBAgAuOoxbsVfMgF8KAYwhuZQcoEBNUGHQhbioAdzpdcMiACgBKMgxEiNQAOlQwMCpuQ2SAckyIUoAaOAApNmYAORzlLj5gDERkgG1yx1KAXVT0gHoRhGQ0HIALGBgwPMVFKlgdUKTUaV0DYzMINWTM9ez0siA

### 💻 Code occuring the bug
```typescript
import typia from "typia";

/* Demonstration code occuring the bug you're reporting */
```

**Comment by sacru2red** [comment]
It works on typescript@5.4.5 typia@6.2.1

**Comment by samchon** [comment]
Union type is not allowed in the `@TypedFormData.Body()` function.

**Comment by sacru2red** [comment]
Thanks
