### ISSUE TITLE
Generates invalid regular expression if tags.Pattern contains the slash('/') character

### ISSUE THREAD

**Issue by kakasoo** [samchon/typia#1232]
# Typia Playground
- [playground](https://typia.io/playground/?script=JYWwDg9gTgLgBDAnmYBDANHA3g1BzAZzgF84AzKCEOAIiRVRoG4AoFgUwA9JYFl24BAHaowBABYR4AXmxs4cAPQAqZSwVxlcACriBUdpALAY0RHABGUVEIDG4hONTwYUYHjzsDAE0fAiwqISUgB06grKiuEGZABcgq7AQnhwAGThCjD4BCEACs4wXkIAPDQAejEEADqKNAB8rMSsLLYQQgQQADbsIZ0QeAAU9Ggh-sWBYpIwdQNYxACU80xAA)

# Code
```
import typia, { tags } from "typia";

export type snapshot = {

  /**
   * The repository branch that triggered this snapshot.
   */
  ref: string &
    tags.Pattern<"^refs/">;
};

console.log(typia.is<snapshot>({}));

```

# Expected
```ts
import typia from "typia";
console.log(
  (() => {
    const $io0 = (input) =>
      "string" === typeof input.ref && /^refs\//.test(input.ref); // `\/` means `/`
    return (input) =>
      "object" === typeof input && null !== input && $io0(input);
  })()({}),
);

```

# Actual
```
import typia from "typia";
console.log((() => { const $io0 = input => "string" === typeof input.ref && /^refs/ / .test(input.ref); return input => "object" === typeof input && null !== input && $io0(input); })()({}));
```

**Comment by samchon** [comment]
Welcome your PR.

**Comment by samchon** [comment]
Considered whether to change the `tags.Pattern` type for a while.

However, this is a break change which can occur many unexpected errors to the ordinary `typia` users.

Instead, you can avoid this problem by changing the text as `"^refs\\/"`, following the current specification of `Pattern` type.

I think this way is enough proper, so that it doesn't look like a weird solution.

https://typia.io/playground/?script=JYWwDg9gTgLgBDAnmYBDANHA3g1BzAZzgF84AzKCEOAIiRVRoG4AoFgUwA9JYFl24BAHaowBABYR4AXmxs4cAPQAqZSwVxlcACriBUdpALAY0RHABGUVEIDG4hONTwYUYHjzsDAE0fAiwqISUgB06grKiuEGZABcgq7AQnhwAGS4hCEACs4wXkIAPDQAejEEADrlijQAfKzErCy2EEIEEAA27CHtEHgAFPRoIbYGzuwAkgQFgWKSMDV9AJQhpgDKiclLi0xAA

```typescript
// CURRENT
export type Pattern<Value extends string> = TagBase<{
  target: "string";
  kind: "pattern";
  value: Value;
  validate: `/${Value}/.test($input)`;
  exclusive: ["format", "pattern"];
  schema: {
    pattern: Value;
  };
}>;

// CONSIDERED FOR A WHILE
export type Pattern<Value extends string> = TagBase<{
  target: "string";
  kind: "pattern";
  value: Value;
  validate: `new RegExp("${Value}").test($input)`;
  exclusive: ["format", "pattern"];
  schema: {
    pattern: Value;
  };
}>;
```

**Comment by samchon** [comment]
Oops, have to consider the JSON schema case

It needs more investigation.

**Comment by samchon** [comment]
`typia` had missed many escaped characters in the `tags.Pattern` type.

It needs type challenge like below.

> https://github.com/type-challenges/type-challenges/issues/22394#issuecomment-1397158205

```typescript
export type Pattern<Value extends string> = TagBase<{
  target: "string";
  kind: "pattern";
  value: Value;
  validate: `RegExp("${Stringify<Value>}").test($input)`;
  exclusive: ["format", "pattern"];
  schema: {
    pattern: Value;
  };
}>;

type Stringify<T extends string, Output extends string = ""> = string extends T
  ? never
  : T extends ""
    ? Output
    : T extends `${infer P}${infer R}`
      ? Stringify<R, `${Output}${P extends keyof Escape ? Escape[P] : P}`>
      : never;

type Escape = {
  '"': '\\"';
  "\\": "\\\\";
  "\b": "\\b";
  "\f": "\\f";
  "\n": "\\n";
  "\r": "\\r";
  "\t": "\\t";
};
```

**Comment by samchon** [comment]
Something to test:

```typescript
type X = Stringify<"^[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$">;
```
