### ISSUE TITLE
Support Node native TypeScript (--experimental-strip-types and --experimental-transform-types)

### ISSUE THREAD

**Issue by ismailkarsli** [samchon/typia#1244]
## Feature Request

I want to use these new flags to get rid of configs, nodemon, ts-node etc. but can't because typia. I really like typia and don't want to lose it. Is there any plans for Node native TS?

Cheers.

**Comment by ryoppippi** [comment]
because typia using tsc to extract type information, you need to run scripts by running tsc + typia

**Comment by ismailkarsli** [comment]
> because typia using tsc to extract type information, you need to run scripts by running tsc + typia

So we need tsc no matter what. I guess I should wait [generation to suffixed files feature](https://github.com/samchon/typia/issues/1251), at least.

Or [generate mode](https://github.com/samchon/typia/issues/1252) with proper caching. Thanks for the info.

**Comment by ismailkarsli** [comment]
@ryoppippi I just checked unplugin-typia and saw it can work with Bun. It looks like it injects with a preload script and it reminded me how ts-node can run with Node —require parameter: https://www.npmjs.com/package/ts-node#node-flags-and-other-tools

I’m wondering, can unplugin-typia work same way and use —loader, —require or —import flag to extract types in Node?

cc @samchon

**Comment by ryoppippi** [comment]
@ismailkarsli unplugin-typia uses tsc inside

**Comment by ismailkarsli** [comment]
@ryoppippi Since ts-node can transform TS files to JS files with `node -r ts-node/register`, I thought that typia can extract TS types with tsc and then let other compilers do their jobs.

I don’t know how tsc, typia or unplugin-typia works so please excuse me if I asked meaningless questions.
