### ISSUE TITLE
Unplugin-typia support npmjs.org

### ISSUE THREAD

**Issue by akirarika** [samchon/typia#1249]
Thank you for creating typia! I love it so much! It became an indispensable part of my project!

Just a few small proposals, can Unplugin-typia support npmjs.org? In China, many websites including JSR are very slow to access, but many of our universities and commercial companies have set up mirrors, but unfortunately these mirrors are for npmjs.org

If it does, it will be very helpful for Chinese developers or some other people who are using mirrors!

**Comment by samchon** [comment]
@ryoppippi

**Comment by ryoppippi** [comment]
@akirarika 
We think it is only a matter of time before jsr is mirrored; it is hard to manage builds and maintain package.json for complex plugins like unplugin. If there is a PR, I would welcome it, but personally I think it is only a matter of time before there is a mechanism to ensure that anything raised in jsr is automatically raised in npm
However, I will try to think of a way to do it.
If you have any ideas, please make an issue in the unplugin-typia repository!

**Comment by ryoppippi** [comment]
@Akirarika However, I had never thought about the situation of JSR in China, and it was interesting because it was the first time I knew about it. Thank you very much

**Comment by ryoppippi** [comment]
@akirarika 
I'm now considering whether I can publish unplugin-typia to npm, but it seems to need refactoring as it has a jsr only package as a dependency.
Please consider putting up a mirror issue in the JSR official.
I think the problem of slow downloads is serious!

**Comment by ryoppippi** [comment]
https://github.com/jsr-io/jsr/issues/110
Oh, I found this issue

**Comment by sxzz** [comment]
In China, if we want to have a good development experience, we will definitely use an accelerator/VPN.

But just in case, I will also publish the package to both JSR and npm, as support for JSR is not yet widespread.

**Comment by ryoppippi** [comment]
@samchon @akirarika 
It was so hard, but finally.... 

https://www.npmjs.com/package/@ryoppippi/unplugin-typia

**Comment by ryoppippi** [comment]
I just want to say that publishing to NPM is so hard...
Look at this looooong exports field... 
![Screenshot 2024-08-29 at 15 39 20](https://github.com/user-attachments/assets/b905063a-e29a-4084-9512-1498442d2aa6)

**Comment by akirarika** [comment]
Well, it seems that this is indeed a more difficult job than expected! 🥲

I am trying to replace the methods used in `@std/collections` and adjust the packagg. If I am successful, I will try to provide a PR!

**Comment by ryoppippi** [comment]
@akirarika oh i didn't notice that i still use std/collections
I can fix it
Give me a minute,

**Comment by ryoppippi** [comment]
@akirarika well, I thinks `@std/collections` is bundled, what is wrong with that?
If so, please create an issue.
I cannot find any issue yet.

**Comment by ryoppippi** [comment]
@akirarika 
FYI: 
I made a new CLI tool for solving this problem

https://github.com/ryoppippi/mirror-jsr-to-npm
