### ISSUE TITLE
Support glob patterns in `typia generate`

### ISSUE THREAD

**Issue by mayorandrew** [samchon/typia#1251]
## Feature Request

Typia is a great library! In the setup I work with, I unfortunately can't use ts-patch and typescript transformers, so the `generate` CLI command is a very welcome feature. 

In our project we structure files in folders based on their semantics rather than type, so validators could end up in many different folders. 

To handle this use-case I propose to extend the generate CLI command to support an arbitrary glob pattern as input and add an option to output generated files right near the input file with an extra suffix.

### Example:
Running
```bash
typia generate --input ./src/**/*.validator.ts --outputSuffix generated
```
would generate the following files:
```
src
├─ module1
│  ├─ input.validator.ts
│  └─ input.validator.generated.ts
└─ module2
   ├─ input.validator.ts
   └─ input.validator.generated.ts
```

In this example the new `--outputSuffix` argument is added that switches the output mode from "output to a folder" to "output near original file with a suffix". 

We can also consider a reverse behavior that removes the latest suffix:
```bash
typia generate --input ./src/**/*.validator.template.ts --outputRemoveSuffix
```
```
src
├─ module1
│  ├─ input.validator.template.ts
│  └─ input.validator.ts
└─ module2
   ├─ input.validator.template.ts
   └─ input.validator.ts
```

If you're ok with this feature and the argument design, I can draft a PR.

**Comment by samchon** [comment]
Will support at next v6.10 update.

By the way, how about using `unplugin-typia` of @ryoppippi 

https://typia.io/docs/setup/#unplugin-typia

**Comment by ryoppippi** [comment]
`unplugin-typia` is one of the best choice in this case.
Please use it.
If you have any questions, ask me with a mention to me.

@mayorandrew

**Comment by mayorandrew** [comment]
> Will support at next v6.10 update.

Thank you! Just to clarify, do you mean that you are going to implement this, or is the issue open for contributions?

> By the way, how about using `unplugin-typia` of @ryoppippi
> `unplugin-typia` is one of the best choice in this case. Please use it. If you have any questions, ask me with a mention to me.

Thank you for the suggestion. Unfortunately in the setup I work with we use a plethora of different tools in different contexts, sometimes even just `swc` without any bundler, so ensuring that all of them support typescript transformations would create extra maintenance burden. Therefore using CLI generation is the best option for us that keeps the right balance.

**Comment by samchon** [comment]
@mayorandrew Trying to make it, but how can I distinguish the root directory of the generation mode with glob pattern? 

Most common directory should be it?

  - a/b/c/d
  - a/b/e/f/
    - `a/b` becomes the root directory?

**Comment by samchon** [comment]
Tried but to way to accomplish glob pattern in the generation mode.

It is possible to filter input files by glob pattern, but no way to filter out the generated files, because TypeScript compiler reads every related files and combines them to a program.

Here is the example case, and you can do the same thing by `npm install typia@6.10.1-dev.20240914`.

- CLI: `npx typia generate --input input/**.controller.ts --output output`
- input
  - private
    - private.interface.ts
    - private.controller.ts
  - protected
    - protected.interface.ts
    - protected.controller.ts
- output
  - private
    - private.interface.ts
    - private.controller.ts
  - protected
    - protected.interface.ts
    - protected.controller.ts
