### ISSUE TITLE
Macro Support and Generics

### ISSUE THREAD

**Issue by bradleat** [samchon/typia#1257]
I believe that typia should support "macros" as supported by the bun and parcel bundlers.

- https://parceljs.org/features/macros/
- https://bun.sh/docs/bundler/macros

In this bundling support `typia.createIs<T>()` can replace itself with the output function.

Howeover, the greatest support should be the addition of generic support for typia within macro calls. For instance, if the user has a macro function `fetch`:

```

export function fetch<T>() {

/// does some stuff

cont result: unknown = // ... use your imagination

const isResult = typia.is<T>(result);

if (isResult === false) throw 'wrong type`;

return result

}

```

In the example, `fetch` is itself a macro funtion, so for every use of it, it will be inlined and `T` can be known. Therefore, typia would gain support for use within generics in macros.

**Comment by samchon** [comment]
I can understand your intention, but I don't dare to put it into practice.

Let's utilize closure function.

**Comment by samchon** [comment]
O
