### ISSUE TITLE
Migrate Publish Process to GitHub Actions

### ISSUE THREAD

**Issue by elliot-huffman** [samchon/typia#1262]
### A description of the problem you're trying to solve
Currently, the NPM package publishing process is handled manually on the author's personal computer. This approach has several drawbacks:
- **Security Risks**: Publishing from a personal computer increases the risk of exposing sensitive credentials and is vulnerable to local security threats.
- **Inconsistency**: Manual processes can lead to inconsistencies in the published packages due to human error.
- **Lack of Transparency**: It is difficult for collaborators to track and verify the publishing process.
- **Limited Automation**: The current setup does not leverage the benefits of continuous integration and deployment (CI/CD) pipelines.
- Unblocks #1255 

### An overview of the suggested solution
The way to implement this is to get the set of steps currently taken to publish the package, then implement them in a GH Actions workflow.
These set of steps fixes the above reported issues.

### Examples of how the suggestion would work in various places
https://github.com/Software-Hardware-Integration-Lab/ObjectID-Converter/blob/main/.github/workflows/NPM-Publish.yml

### PR
Requested change - #1274

**Comment by samchon** [comment]
Thanks for suggestion and contribution.

**Comment by elliot-huffman** [comment]
@samchon, what are the current set of steps that you perform to publish a new version?

Also, are there any check you want to succeed before the publish command is issued?

**Comment by samchon** [comment]
`npm run package:latest` is the command including build and test.

**Comment by elliot-huffman** [comment]
## Workflow Double Check
So, to double check before I write the PR, the order of operations looks like this?

1. `npm run package:latest`
2. `npm publish`

## NPM Permissions Grant

Also, I will need you to generate a fine-grained NPM JS access token, create a new environment in the repo settings called `NPM` and put the publish token in there as a secret with the name of `NPM_PUBLISH`.

When making the [fine-grained token](https://docs.npmjs.com/about-access-tokens#about-granular-access-tokens), make sure it only has access to the `typia` package and no other permissions.
When making the [GitHub environment configuration](https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-deployments/managing-environments-for-deployment), I highly recommend that you target it to the `master` branch with `*` as the tags to target.
I also recommend that you configure the environment to not proceed until someone approves it that you specify. This will prevent usage of your publisher token without your approval (or by others that you may trust) in this repo.
When making the token, you can make the expiration be a long time if you wish, there is no max date that I am aware of.

**Comment by elliot-huffman** [comment]
I have created a PR after some code review to get the specifics figured out: #1274.
@samchon, let me know what you think :)

**Comment by samchon** [comment]
Completed. Thanks for suggestion and contribution.

**Comment by elliot-huffman** [comment]
Hi @samchon ,

I went through the new CI/CD code and since you have it tied to release publish (I do that too) and have not GH Environment with approval process, anyone that has write access to the repo is able to create a release.

I just wanted to make sure you knew this as anyone that is a member essentially has NPM Publish rights now.
GH Environments fixes this issue by stopping execution until there is approval from your specified groups/users.

If this is the expected behavior, no worries. Just wanted to make sure you were aware.

Thanks!
