### ISSUE TITLE
[BUG] Returning type of createAssertGuard is invalid

### ISSUE THREAD

**Issue by miyaji255** [samchon/typia#1264]
## Bug Report

Returning types of `createAssertGuard` and `createAssertGuardEquals` are invalid.

**Document**

![image](https://github.com/user-attachments/assets/48584743-a9c7-40d8-be8b-46d6d3e3e17b)

**Actual types**

https://github.com/samchon/typia/blob/cd6ed78a9815134617405b34d5ee891da56f539a/src/module.ts#L722-L724

https://github.com/samchon/typia/blob/cd6ed78a9815134617405b34d5ee891da56f539a/src/module.ts#L896-L898

### ⏯ Playground Link

https://typia.io/playground/?script=JYWwDg9gTgLgBDAnmYBDANHA3g1BzAZzgF84AzKCEOAIiRVRoG4AoF4AOxgFMozUAxtzgBJALLcQAI17YWcOMAAmALjgEYUTnjgAyXIQB0AMWghUMADw0ArjeU0AfKwUdUIbmo1aOeF3HxPOA4baVldeQUDAkMAFWRua3suAGYAJic9SIUYfBixTlBQyzSABkcsqOjDAFEADwEAGxsCYAA3bjFUOqKQSwBGUvLWYhYBCA4NODwbVCglCTCoOABeBGQ0QwEobgtuAEECAl4YAHFZ+ctxSRkoRwAKAEpWccn4CCkAK1WsUZYZuYLG68e4fT6PNivAgQRrcQyNCB4e4AA2UagAJFgwYZlMRkY8gA

**Comment by samchon** [comment]
```typescript
import typia, { tags } from "typia";

interface IMember {
  id: string & tags.Format<"uuid">;
  name: string;
  age: number &
    tags.Type<"uint32"> &
    tags.Minimum<20> &
    tags.ExclusiveMaximum<100>;
}
const guardMember: typia.AssertionGuard<IMember> = typia.createAssertGuard<IMember>();
```

You have to declare explicit type like above.

It is the TypeScript assertion type rule.

**Comment by samchon** [comment]
Reopened after the 2026-07 repository issue campaign verified the unresolved runtime/type mismatch. The prior note about explicitly annotating assertion-function variables remains correct; the residual defect is that the factory overload itself returns `(input: unknown) => AssertionGuard<T>`, which falsely types a successful guard invocation as returning another guard although runtime returns `undefined`. The refreshed body is the operative implementation handoff.
