### ISSUE TITLE
TypeError: util2.strToChars is not a function in Typia 6.10.0 with Angular 18 and TypeScript 5.5.4

### ISSUE THREAD

**Issue by Karbashevskyi** [samchon/typia#1277]
Here's the updated bug report with the correct Typia version:

---

## Bug Report

Note that the bug you're reporting may have already been registered in the [issues](https://github.com/samchon/typia/search?type=issues) by another user. The bug may also have been fixed in the `@next` version. For that reason, I recommend checking the old [issues](https://github.com/samchon/typia/search?type=issues) and reproducing your code with the `@next` version before publishing the bug reporting issue.

```bash
npm install --save-dev typia@next
```

When the same error occurs even in the `@next` version, please fill in the template below:

---

### 📝 Summary
Encountering `TypeError: util2.strToChars is not a function` when using Typia with Angular 18, TypeScript 5.5.4, and Node.js 20.11.1.

  - **Typia Version**: 6.10.0 (Latest)
  - **Expected behavior**: Typia should run without errors in a standard Angular project.
  - **Actual behavior**: Runtime error occurs, indicating `util2.strToChars is not a function`.

I encountered this issue during runtime after setting up Typia with Angular and TypeScript. The error suggests that a function (`strToChars`) is missing or unavailable in a utility module that Typia relies on.

---

### ⏯ Playground Link
[No playground link available as the issue is specific to an Angular setup.]

---

### 💻 Code Occurring the Bug
```typescript
import {Component} from '@angular/core';
import {Enum} from "@src/module/utility/domain";
import typia, {tags} from "typia";
import {CustomerTypeEnum} from "@customer/domain/enum/customer-type.enum";
import {IBaseEntity} from "@utility/domain/interface";

export interface IBaseEntity<OBJECT_TYPE extends string> {
    // Added by the system
    _id: string & tags.Pattern<'^(?=[a-f\\d]{24}$)(\\d+[a-f]|[a-f]+\\d)'>;
    createdAt: string & tags.Format<'date-time'>;
    updatedAt: string & tags.Format<'date-time'>;
    object: OBJECT_TYPE;
}

export type RIBaseEntity<OBJECT_TYPE extends string> = Required<IBaseEntity<OBJECT_TYPE>>;

/**
 * Declare interface by business logic, if you need case when each property is optional, use Partial<ICustomer>
 */
export interface ICustomer extends IBaseEntity<'CustomerDto'> {
    firstName: string & tags.MaxLength<50> | null;
    lastName: string & tags.MaxLength<50> | null;
    phone: string | null;
    email: string & tags.Format<"email"> | null;
    note: string | null;
    customerType: CustomerTypeEnum & tags.Default<CustomerTypeEnum.new>;
    active: Enum.ActiveEnum & tags.Default<Enum.ActiveEnum.YES>;
}

export const isCustomer = typia.createIs<ICustomer>();
export const validCustomer = typia.createValidate<ICustomer>();
export const randomCustomer = typia.createRandom<ICustomer>();

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'typia-angular-integration';

  constructor() {
    console.log(randomCustomer())
  }
}
```

#### **Error Trace:**
```
TypeError: util2.strToChars is not a function
    at [file]:[line number]
```

---

### 💡 Additional Information
- **Environment Details:**
  - **Angular Version:** 18.x (Latest)
  - **TypeScript Version:** 5.5.4
  - **Node.js Version:** 20.11.1
  - **Operating System:** MacOS

I’ve ensured that all dependencies are up to date and have also attempted reinstalling node modules using `rm -rf node_modules && npm install`. Despite this, the issue persists.

This error seems to stem from a missing or deprecated function in one of Typia's dependencies. I was unable to locate `strToChars` in the utility modules involved.

Any guidance on resolving this would be appreciated!

---

Let me know if any further adjustments are needed!

**Comment by samchon** [comment]
https://typia.io/playground/?script=JYWwDg9gTgLgBDAnmYBDANHA3g1BzAZzgF84AzKCEOAIiRVRoG4AoF4AOxgFMozUAxtzgBJALLcQAI17YWcOAH1gAEwBccAjCic8cAGS5CAOgAKqGDygcAPAHIAegAoA-AF4A2qgC0ZADp+KgC6WABMACzEACQAlE4BKgDUXr5BAD4pZEGJCTF2AHysxGwCEBwEEAA23MaVEHhO8gjIaMZQqBwqVDbikjJQ+U4x6CwxTHAsQA

@ryoppippi This problem comes from the rollup configuration. How shoul do?

**Comment by samchon** [comment]
@ryoppippi Tried by myself, but failed to escape this problem.

I disabled `preserveModules` option for a while, just to fix this bug. 

If you know how to escape it, please help me.

**Comment by ryoppippi** [comment]
@samchon I cannot find the `strToChars`
Where is the function implemented.

**Comment by ryoppippi** [comment]
@Karbashevskyi If you create a reproduction repository, it makes life easier

**Comment by samchon** [comment]
@ryoppippi Here it is.

Such `_virtual` directory exported empty object is used in the `ret` library.

Also, you can test it with previous `typia` version.

![image](https://github.com/user-attachments/assets/eade7a2b-b4ed-4cac-88f0-194b75874d0f)

**Comment by ryoppippi** [comment]
Ok, let me check
This comes with ret

**Comment by ryoppippi** [comment]
Hmm, in my local build, it is not missing

**Comment by ryoppippi** [comment]
Oh, okay. I got it
