### ISSUE TITLE
Support @example JSDoc tag in JSON schema.

### ISSUE THREAD

**Issue by tin-pham** [samchon/typia#1294]
## Feature Request

Is this possible, I'm currently at newest version, trying typia.json.application with @example tag but it show nothing when generate schema.
It would be great if typia have this, I'm currently try to automate the documentation task, generate swagger from interface, then put it in Docusaurus, but currently the example taken from Schema (default like "string", "number") 

``` typescript
interface Something {
  /**
   * This is the title.
   *
   * This is the description.
   */
  id: string;

  /**
   * This is not the description.
   *
   * @title Name
   * @description This is the description of the name
   * @example some_name
   */
  name: string;

  /**
   * @description No title.
   *
   * @example 'some description'
   */
  description: string;
}
```

**Comment by samchon** [comment]
How about supporting `tags.Example<T>` type?

**Comment by tin-pham** [comment]
Even better, it won't bloat the interface if the example is too long.

**Comment by samchon** [comment]
Added `tags.Example` and `tags.Examples` types.

Not possible to add example to an object typed property yet, but the others are all supported.

Upgrade to `6.10.3`, then you can use them.

**Comment by ismailkarsli** [comment]
I wish we had this in the comments as well, because tags can't be used in Prisma.

**Comment by Zomono** [comment]
I also like to provide example values by using @comment in the JSDoc section. These example values are only used for OpenAPI generation and not for validation or serialization. This is why I don't want them to occur in real source code (like tags.Example() decorator).
Are there plans to support @example from jsdoc comments?
Thanks so far for this great library.
