### ISSUE TITLE
Not friendly to the vscode debugger ?

### ISSUE THREAD

**Issue by shlroland** [samchon/typia#1305]
Originally, I used zod as the validator for my hono app. After seeing typia, I want to try using it to replace the original zod.

After replacing with typia, it can run normally. 

But when I want to debug the function, I found that typia seems to be not friendly to vscode debug. I can't get the context according to the code logic of my original ts file. Is there any way to solve this problem?

This is the snapshot when zod used

![image](https://github.com/user-attachments/assets/111ea949-c78a-4326-b878-44ef26ecead9)

This is the snapshot when typia used

![image](https://github.com/user-attachments/assets/263207ec-ec80-417a-b14f-bcef70fbe06d)

enviroments:

Bun: 1.1.29
Hono: 4.6.3
@hono/typia-validator: 0.3.0
typia: 6.11.1

**Comment by samchon** [comment]
It would not be familiar until TypeScript officially supportinng the transform API.
