### ISSUE TITLE
Assert function not working with generic type

### ISSUE THREAD

**Issue by RumyantsevOleg** [samchon/typia#1309]
## Bug Report

This code throw  non-specified generic argument (even considering that there is no call to this function anywhere yet)

```
public decodeJwtToken<T>(token: string) {
    const payload = jwt.verify(token, jwtSecret);

    return assert<T>(payload);}
}
```

**Comment by samchon** [comment]
Too much duplicated questions, but the error message is showing the detailed reason why.

You have to call the `typia.assert()` function with exactly specified type.

The type `T` is a significant generic argument, and it is not supported.

**Comment by RumyantsevOleg** [comment]
Thank you. But how I can solve my problem. This is really popular case, and I need to find solution. Could you help please. Thank you
