### ISSUE TITLE
typia string & Pattern not work

### ISSUE THREAD

**Issue by daimalou** [samchon/typia#1326]
@samchon Hi

I made a link here, thank you.

https://typia.io/playground/?script=JYWwDg9gTgLgBDAnmYBDANHA3g1BzAZzgF84AzKCEOAIiRVRoG4AoF+gUzgEkATOALy5CAOgAKqGDA5QAdgB4aAPQCMAHV5YVABmIASGgD52yLnwBMg4QXGTpcxas079RtgGMIsgvHcALDncAayt6NBF3KA5JDm4CeR8oYFk8OAAyHl5DAAoASlZPb18A4MshMNQIqJi4hJgklPTM8xz8lkKCCAAbDhEuiDxs-0Cg7IByFQBOaZnZsdy2ju7e-sHh0vGp2e35-KA

**Comment by samchon** [comment]
When writing string based `RegExp`, `"\"` is not proper, but `"\\n"` is exact.

```typescript
string & tags.Pattern<"^1\\d{10}$">
```
