### ISSUE TITLE
`schema()` function for singular JSON schema types

### ISSUE THREAD

**Issue by ismailkarsli** [samchon/typia#1343]
## Feature Request
Currently there is only the application() function to generate JSON schema and it works pretty well. However, it is a bit difficult to use when you don't want to create the entire OpenAPI file.

An example from Elysiajs and Fastify:
```typescript
app.post(
	"/login",
	() => {
		return { token: "123" };
	},
	{
		body: application<[UserLogin]>().components.schemas?.UserLogin,
		response: application<[{ token: string }]>().schemas.at(0),
	},
);
```

```typescript
fastify.post(
	"/login",
	{
		schema: {
			body: application<[UserLogin]>().components.schemas?.UserLogin,
			response: { 200: application<[{ token: string }]>().schemas.at(0) },
		},
	},
	(request, reply) => {
		reply.status(200).send({ token: "123" });
	},
);
```

Therefore, I recommend making a trimmed copy of the `application()` function. Converts the received type to JSON schema component. If not, throws an error etc. I believe it would make things much cleaner.

```typescript
app.post(
	"/login",
	() => {
		return { token: "123" };
	},
	{
		body: schema<UserLogin>(),
		response: schema<{ token: string }>(),
	},
);
```

**Comment by samchon** [comment]
Try to use this one if no recursive relationship exists.

https://typia.io/docs/llm/schema/

**Comment by ismailkarsli** [comment]
> Try to use this one if no recursive relationship exists.
> 
> https://typia.io/docs/llm/schema/

I did not expect this feature to be under the LLM title. Thanks 🙏
