### ISSUE TITLE
[Feature Request] A pattern tag overrides a template literal

### ISSUE THREAD

**Issue by miyaji255** [samchon/typia#1346]
## Feature Request
We can specify conditions with Pattern Tag easier than template literal string. So, Pattern Tag should override template literal string.

```ts
type String0x = `0x${string}`; // /0x(.*)/

// Override
type String0x = `0x${string}` & tags.Pattern<'^0[xX][A-Fa-f0-9][A-Fa-f0-9]+$'>; // /^0[xX][A-Fa-f0-9][A-Fa-f0-9]+$/
```

**Comment by samchon** [comment]
No way to support template level tag type, because TypeScript compiler cannot parse it properly.

**Comment by wighawag** [comment]
Not sure I understand, so sorry in advance, but the solution proposed would be to use the tags.Pattern here and ignore the template litreral
