### ISSUE TITLE
Is there a reason to make a tar.gz file that builds typia when you proceed with the test?

### ISSUE THREAD

**Issue by sunrabbit123** [samchon/typia#1357]
## Question

Is there a reason to make a tar.gz file that builds typia when you proceed with the test?

Packaging build files is considered a bottleneck.
package.json can refer to the package.json in the local file.

like next:
```json
    "typia": "../"
```

Is there a reason?

**Comment by samchon** [comment]
No reason.

If possible to setup test like sub projects with such simple configuration and there is no problem even in the transformation leve (`plugin` configuration in the `test/tsconfig.json`), it would be nice.

**Comment by sunrabbit123** [comment]
I tested it in relation to it, but even the files I don't need are imported.

![스크린샷 2024-11-18 오후 12 04 37](https://github.com/user-attachments/assets/9e77a6f0-4574-4704-bede-c4340fbdbf44)

I confirmed that npmignore is not working either.

Well, it's just going to be decided whether or not there's a pack level

What do you think?

If you are negative about the correction, please close the issue.

https://stackoverflow.com/questions/55400151/how-to-avoid-adding-package-to-node-modules-if-it-placed-locally

**Comment by samchon** [comment]
Let's just use the relative path setup.
