### ISSUE TITLE
Support for nested query string parameters 

### ISSUE THREAD

**Issue by ramiroaisen** [samchon/typia#1363]
## Feature Request

We are using typa.http.assertQuery for an API we are using.
We need to be able to use nested query parameters in the query string.
An example of this would be a query like this: `?nested[param1]=1&nested[param2]=foo`
Which should match with a type like this.

```ts
type Query = {
  nested: {
    param1: number
    param2: string
  }
}
```

**Comment by sunrabbit123** [comment]
good idea, but is this a standard spec?

https://jsonapi.org/format/#query-parameters-families:~:text=Therefore%2C%20JSON%3AAPI%20provides%20its%20own%20definition%20of%20a%20query%20parameter.
https://url.spec.whatwg.org/#urlencoded-parsing

**Comment by samchon** [comment]
No standard spec.

Also, typia is using `URLSearchParams` of JS standard, and it does not support the nested property either.

**Comment by ramiroaisen** [comment]
> good idea, but is this a standard spec?
> 
> https://jsonapi.org/format/#query-parameters-families:~:text=Therefore%2C%20JSON%3AAPI%20provides%20its%20own%20definition%20of%20a%20query%20parameter. https://url.spec.whatwg.org/#urlencoded-parsing

Not sure if it is standarized, but is a *de facto* standard. It is the way [qs](https://www.npmjs.com/package/qs) module works, and many others in others languages like [serde_qs](https://crates.io/crates/serde_qs) for Rust.
Also the `express` query parser works this way.

**Comment by ramiroaisen** [comment]
> No standard spec.
> 
> Also, typia is using `URLSearchParams` of JS standard, and it does not support the nested property either.

URLSearchParams will output entries with the full path of every property, but typia could support this nevertheless.

```js
[...new URLSearchParams("a[b]=1&c[d]=2").entries()]
```
will output this entries
```js
[
  [ "a[b]", "1" ],
  [ "c[d]", "2" ]
]
```

Support for this will supose a little extra effort in the parsing logic, but I think it's doable. I'm willing to take a look with your persmission and guidance to implement this.

**Comment by ramiroaisen** [comment]
> good idea, but is this a standard spec?
> 
> https://jsonapi.org/format/#query-parameters-families:~:text=Therefore%2C%20JSON%3AAPI%20provides%20its%20own%20definition%20of%20a%20query%20parameter. https://url.spec.whatwg.org/#urlencoded-parsing

I found it in the OpenAPI v3 spec here:

https://swagger.io/docs/specification/v3_0/describing-parameters/#:~:text=deepObject%20%E2%80%93%20/points%3Fcolor%5BR%5D%3D100%26color%5BG%5D%3D200%26color%5BB%5D%3D150

You have to specifiy the query parameter as `deepObject`.

I think if it's accepted in OpenAPI v3 it counts as being standarized, right?

**Comment by sunrabbit123** [comment]
The standard I thought would be RFC or document.
This format, collectively called the Qs style, is gradually being applied to ecosystems
I don't think there's a separate document, and I think I'm relying on the QS library.

It is also possible to infer from the fact that there have been discussions about how to specify this within open api.

https://datatracker.ietf.org/doc/html/rfc6570
https://datatracker.ietf.org/doc/html/rfc3986#section-3.4
https://www.w3.org/TR/html401/interact/forms.html#form-content-type

As you can see from the above cases, nothing has been decided
It is a function that has no choice but to rely on the implementation of the server, so I think we should be careful about deepObject.

**Comment by samchon** [comment]
This is out of standard, and as URL path has length limit, URL query must not be compliicated.
