### ISSUE TITLE
Support for Record in query functions

### ISSUE THREAD

**Issue by ramiroaisen** [samchon/typia#1364]
## Feature Request

This isssue assumes first the implementation of #1363 

We are using typia.http.assertQuery in an API we are developing.

In a place we need to accept a custom attributes filter in the form of Record<string, string>

So a query like this:
```ts
type Query = {
  attrs: Record<string, string>,
}
```

could be parsed from a string like this `?attrs[foo]=bar&attrs[baz]=das`

And the parsing should correctly resolve to an object like this:

```javascript
{
  attrs: {
    foo: "bar",
    baz: "das",
  }
}
```

That shape correctly match the expected format.

**Comment by samchon** [comment]
Why not using request body instead? I cannot understand this use case. 

This is out of the standard. As URL path has limit length (1,024), the query parameter must not be detailed. If your API has deep nested structure, it is just a tremendous design level mistake.

**Comment by ramiroaisen** [comment]
> Why not using request body instead? I cannot understand this use case.
> 
> This is out of the standard. As URL path has limit length (1,024), the query parameter must not be detailed. If your API has deep nested structure, it is just a tremendous design level mistake.

Design level mistake? have you ever seen google urls? I recommend you to be more humble
