### ISSUE TITLE
Support Pattern<function()>

### ISSUE THREAD

**Issue by st-clair-clarke** [samchon/typia#1392]
## Feature Request
Thanks for your suggestion. Feel free to just state your idea. Writing the issue, it would better to filling the below items:

  - A description of the problem you're trying to solve.
  - I have the following function that returns a RegExp:
  
  ```
export const nounRegex = (): RegExp => XRegExp.tag('gmnx')`
      (
         (
           ( d[eu] | l[ae] | Ste?.? | v[ao]n )  # match a name particle; non-capturing
          \x20                               # followed by a literal space
      )*                                     # 0 or more times; non-capturing
      (?<name> [A-Za-z' -]+) (\k<name>)*    # match a named-capture with a named-backreference 0 or more times
      )                                      # non-capturing
       [a-z']                                # end with lowercase character or single quote
     `
```
  
  - An overview of the suggested solution.
  However, the tags.Pattern<> ony supports a string,

    - Code examples showing the expected behavior.

I would like to be able to do the following:

```
type TName = {
   first: string & tags.MinLength<2> & tags.MaxLength<20> & tags.Pattern<nounRegex()>
}
```

Let me know what you think.

**Comment by samchon** [comment]
Return value of the `nounRegex()` function, you can get it in the runtime.

By the way, defining type must be in the compilation time.

No way to take runtime value to the compile time defining type.
