### ISSUE TITLE
Can we get the old (v6) typia.llm.schema under the name of typia.json.schema?

### ISSUE THREAD

**Issue by ismailkarsli** [samchon/typia#1417]
I was using that function to generate singular schemas but it has been deprecated with v7. Is there any chance you can bring it back as typia.json.schema or a different name?

**Comment by samchon** [comment]
`typia.json.schema<T, "3.0">()` is the thing what you want.

**Comment by ismailkarsli** [comment]
Are you sure? I'm getting this error on 7.0.2:
`Property 'schema' does not exist on type 'typeof import(".../node_modules/typia/lib/json")'. Did you mean 'schemas'?`

I don't see a `schema` function in `typia/lib/json` file.

**Comment by samchon** [comment]
There had not been `typia.json.schema()` function.

I think you are misunderstanding `typia.llm.schema()` function.

**Comment by ismailkarsli** [comment]
I think I was misunderstood. What I'm trying to say is:

`typia.llm.schema()` in 7.0.2 is in this type:
```typescript
function schema<
  T,
  Model extends ILlmSchema.Model,
  Config extends Partial<ILlmSchema.ModelConfig[Model]> = {},
>(
  ...$defs: Extract<
    ILlmSchema.ModelSchema[Model],
    { $ref: string }
  > extends never
    ? []
    : [Record<string, ILlmSchema.ModelSchema[Model]>]
): ILlmSchema.ModelSchema[Model];
```

while 6.12.2, it was in this type:
```typescript
function schema<T>(): ILlmSchema;
```

So in the end, the old `typia.llm.schema()` function is changed and can't be used in old way. We just can't use the expression below as before with the new `typia.llm.schema()` function.
```typescript
const userSchema = schema<User>();
```

What I'm asking is, can you please make a new `typia.json.schema()` function that acts like old, 6.12.2 version `typia.llm.schema()`?

**Comment by samchon** [comment]
You can still use the `typia.llm.schema<T, "3.0">()` function as I've mentioned.

What do you specially want from the `typia.json.schema()` function? `typia.json.schemas<Types>()` function cannot satify you?

**Comment by ismailkarsli** [comment]
Ok I tried `typia.llm.schema<T, "3.0">()` and it works as before. You are right.

I tried it with 3.1 when I first upgraded and thought I needed to provide array of $defs. I guess it's not needed for 3.0.

Thanks for the information and attention 🙏
