### ISSUE TITLE
Generate invalid types

### ISSUE THREAD

**Issue by miyaji255** [samchon/typia#1432]
### 📝 Summary

`typia.http.headers` generates invalid types. Passing `string | string[] | undefined` despite `_httpHeaderReadNumber` argument being `string | undefined`.

  - **Typia Version**: 7.3.0
  - **Expected behavior**: pass type check 

### ⏯ Playground Link
https://typia.io/playground/?script=JYWwDg9gTgLgBDAnmYBDOAzKERwERIqp4DcAUGcAHYwCmUGqAxrXAMpMAWtI6A3nGAATAFxwqAVxAAjeiTgBfMoTQA6TjBhh1tVEPoBnADwduvAHwAKPgoCUQA

### 💻 Code occuring the bug
```typescript
import typia from "typia";

interface Schema { id: number; }
typia.http.headers<Schema>({})
```

**Comment by samchon** [comment]
https://typia.io/docs/misc/#headers-functions

Use one of below:

- `typia.http.assertHeaders`
- `typia.http.isHeaders`
- `typia.http.validateHeaders`

**Comment by miyaji255** [comment]
They makes same issues.

Here is a generated code error.
```typescript
(
    input: Record<string, string | string[] | undefined>,
  ): import("typia").Resolved<Schema> => {
    const output = {
      id: __typia_transform__httpHeaderReadNumber._httpHeaderReadNumber(
        input.id, // Argument of type 'string | string[] | undefined' is not assignable to parameter of type 'string | undefined'.  Type 'string[]' is not assignable to type 'string'.ts(2345)
      ),
    };
    return output as any;
  };
}
```
