### ISSUE TITLE
[Question] How to assert rgb union array type?

### ISSUE THREAD

**Issue by daimalou** [samchon/typia#1448]
## Question
I have a rgb data type like `[[128, 128, 128], [0, 0, 0]]`, how to assert using typia.

I get stuck in `[number, number, number][]`.

**Comment by samchon** [comment]
Define like below.

```typescript
import typia, { tags } from "typia";

type RgbValue = number & tags.Type<"uint32"> & tags.Maximum<256>;
type RgbTuple = [RgbValue, RgbValue, RgbValue];

typia.createIs<Array<RgbTuple>>();
```

https://typia.io/playground/?script=JYWwDg9gTgLgBDAnmYBDANHA3g1BzAZzgF84AzKCEOAIiRVRoG4AoF+gUzgCU8AjAGqoANgFcuAXjgA7USD4cocAGS5CAOgAqyDgB4ao4NJgBmAEw0AfCrUF1AWVQAPUHN1mArADZLrTj35NUTBhSTgAbV5BEXFMKKExDjj+BPEAXVZ2ZDR1AGMoDlQYDgBJAl0AQSgoVERdKKCQjktLAAoASiYgA

**Comment by daimalou** [comment]
@samchon Thank you very much.
