### ISSUE TITLE
Add a new function `TSON.random<T>(): T`

### ISSUE THREAD

**Issue by samchon** [samchon/typia#174]
https://github.com/samchon/nestia/issues/141

@SkyaTura suggested a good idea in `nestia`, but `typescript-json` seems more suitable.

Create a transformer function that generates a random data following its generic argument type.

```typescript
export function random<T>(): T;
```

Also, TypeScript compiler has started supporting AST features even in the descriptive comments since 4.7 update. Therefore, study the new TypeScript compiler AST and check whether writing script in comment is possible or not like below.

```typescript
export interface IMember {
    /**
     * E-mail address of member.
     *
     * {@validate Validator.email}
     * {@random RandomGenerator.email}
     */
    email: string;
}

**Comment by SkyaTura** [comment]
This type of annotation would be useful for string masking as well.

Also, maybe, presets/alias to set repetitive combination of helpers, like email. (But I don't really know what to think about this being too "magically" abstracted)

**Comment by samchon** [comment]
I'm sorry for give up this issue. I've failed to find how to generate random data of patterned string
