### ISSUE TITLE
`assertType` and `is` should accept `any` or `unknown`

### ISSUE THREAD

**Issue by paulrostorp** [samchon/typia#184]
## Feature Request
![Screenshot 2022-09-12 at 12 45 44](https://user-images.githubusercontent.com/1866649/189634964-10d470ac-9dfb-469c-ae1c-079c7778a521.png)

The runtime type checking methods `assertType` and `is` work fine when the input value is `any` but if you're trying to validate a value that is one of a union, it doesn't work...

I believe the typings should be changed to:
```js
export declare function is<T>(input: unknown): input is T;
```

This is how `typescript-is` behaves.

The workaround with the current type is to manually typecast everything:
```js
assertType<string>(v as string);
```

cc @samchon

**Comment by samchon** [comment]
It seems right. Your suggestion would be accepted soon.

Also, previous declaration would be kept and be compatible with your suggestion like below.

```typescript
export declare function is<T>(input: T): boolean;
export declare function is<T>(input: unknown): input is T;
```

**Comment by paulrostorp** [comment]
I'll make a PR

**Comment by samchon** [comment]
~~@paulrostorp Oops, already completed the new version.~~

Thanks, I will wait for your PR.

**Comment by paulrostorp** [comment]
@samchon Whatever you prefer...

When you said "Your suggestion would be accepted soon.", I thought you were hinting that I should make a PR 😄

**Comment by samchon** [comment]
OK, the new version is `3.2.3`.

**Comment by paulrostorp** [comment]
@samchon 🏆

**Comment by samchon** [comment]
@paulrostorp Oops, I'm sorry but emergent patch to `v3.2.4` is required.
