### ISSUE TITLE
Flag for assertType so that it won't fail if transforms are not available

### ISSUE THREAD

**Issue by KristjanTammekivi** [samchon/typia#186]
## Feature Request
Trying to have tests for types alongside integration tests. This would require switching off transpileOnly which would make test startup time slower, so idea is to only run tests without transpileOnly in CI.

One option would be to have a generic function in my code to try/catch and inspect the error, but that's stuck on #125 
Since #125 is a complex issue to solve, another option would be to add a fail silently flag on assertType

For example:
```typescript
// if CI, fail if transforms have not been run. Else don't throw and fail silently
assertType<SomeType>(value, process.env.CI !== 'true');
```

**Comment by samchon** [comment]
Your suggestion is too domestic, but I can understand why you need such feature.

What about define a custom function through function parameter like below?

```typescript
export function domesticAssert<T>(
    input: T,
    asserter: (input: T) => T
): T {
    if (Configuration.testing)
        return input;
    return asserter(input);
}

const something: Something;
domesticAssert(something, input => TSON.assertType(input));
```
