### ISSUE TITLE
Add new functions `equals`, `assertEquals` and `validateEquals`

### ISSUE THREAD

**Issue by KristjanTammekivi** [samchon/typia#187]
## Question

Is there a way to check if a type has no excess properties for example. the following should throw
```typescript
import TSON from "../../../src";

TSON.assertType<{ a: true }>({ a: true, b: false });
```

**Comment by samchon** [comment]
Not implemented yet, but would implement it in this month because your feature looks useful.

**Comment by samchon** [comment]
Similar library `typescript-is` is providing `equals()` and `assertEquals()` functions.

Therefore, I'll provide similar named functions, for `typescript-is` users, like below:

```typescript
TSON.equals<T>(input: T): boolean;
TSON.assertEquals<T>(input: T): boolean; // throws TypeGuardError
TSON.validateEquals<T>(input: T): IValudationResult;
```

**Comment by samchon** [comment]
@KristjanTammekivi You can use those `equals()` and `assertEquals()` functions by installing `@next` version.

```bash
npm install --save typescript-json@next
```

The stable version will be published until tomorrow, maybe.

**Comment by samchon** [comment]
@KristjanTammekivi update to `v3.2.6`, then you can use new functions

**Comment by KristjanTammekivi** [comment]
Thanks, will give it a try tomorrow
