### ISSUE TITLE
assertEquals produces false negatives with Record type

### ISSUE THREAD

**Issue by KristjanTammekivi** [samchon/typia#196]
### Summary
Write a short summary of the bug in here.

  - **SDK Version**: git/master
  - **Expected behavior**: No error 
  - **Actual behavior**: invalid type on $input["1"], expect to be undefined

### Code occuring the bug
```typescript
import TSON from "../../../src";


interface A {
    id: number;
    name: string;
}

type B = Record<number, A>;

TSON.assertEquals<B>({
    "1": {
        id: 1,
        name: "1",
    },
}); // TypeGuardError: Error on TSON.assertEquals(): invalid type on $input["1"], expect to be undefined
```

**Comment by samchon** [comment]
Not support dynamic property, but soon - #153
