### ISSUE TITLE
Get excess fields / superfluous property fields

### ISSUE THREAD

**Issue by enghitalo** [samchon/typia#202]
## Question
Hi, samchon! Fantastic project.

I don't see nothing in readme.md about this.

Has some way to I get exceted/superfluous properties of one object?

Something like
```ts
type AnyTypeTry = { a: string}

const value = {
a: "lalala",
b: "axkaoask",
}

const test= TSON.difference(AnyTypeTry, value)

console.log(test)
/** 
output:
{b: "axkaoask"}
*/
```

I have tried solve this in typescript (left) and vlang (right)
As you can see, it is very hard to typescript and not well secure for both
 
![image](https://user-images.githubusercontent.com/63821277/191828308-bde0886a-3f38-41a1-a636-87182bb629d2.png)

**Comment by samchon** [comment]
Here is the code what you can do:

```typescript
import TSON from "../../src";

type AnyTypeTry = { a: string };

const validation: TSON.IValidation = TSON.validateEquals<AnyTypeTry>({
    a: "something",
    b: "more",
    c: "and",
    d: "more",
});

console.log(
    validation.errors
        .filter((err) => err.expected === "undefined")
        .map((err) => err.path),
);
```

You can run upper code following below command:

```bash
git clone https://github.com/samchon/typescript-json
cd typescript-json
npm install
npm run issue 202
```

The console output is:

```bash
[ '$input.b', '$input.c', '$input.d' ]
```

**Comment by samchon** [comment]
Oops, I misunderstood your requirement.

The `TSON.difference()` function seems interesting.

I'll try your feature at this Saturday.

**Comment by samchon** [comment]
Looking at your screenshot, it seems that removing all superfluous properties.

It's possible by repeating `JSON.parse()` and `TSON.stringify()` like below:

```typescript
const shrinked: SomeType = JSON.parsse(TSON.stringify<SomeType>(someObj));
```

**Comment by enghitalo** [comment]
> Oops, I misunderstood your requirement.
> 
> The `TSON.difference()` function seems interesting.
> 
> I'll try your feature at this Saturday.

Well, I have implemented this. https://github.com/enghitalo/Ultis/blob/main/typescript/src/app.ts

Maybe, can be useful

**Comment by enghitalo** [comment]
```ts
const employee_type_descriptor = {
  name: String() || undefined,
  age: Number(),
};

type Employee = typeof employee_type_descriptor;

const json_response = '{"name":"Peter","age":28,"salary":95000.5,"title":2}';

function verifyIfIsEmpty(obj: any): boolean {
  const isEmpty =
    obj &&
    Object.keys(obj).length === 0 &&
    Object.getPrototypeOf(obj) === Object.prototype;

  return isEmpty;
}

function pruneTheLeaves<T>(
  untyped_parse: any,
  descriptor: T,
  show_warn?: boolean
): T {
  const new_typed: any = {};
  for (let key in descriptor) {
    try {
      const val = untyped_parse[key];
      delete untyped_parse[key];

      if (typeof val !== "undefined") {
        new_typed[key] = val;
      }
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      throw new Error(`could not pick ${key}: ${msg}`);
    }
  }

  if (!verifyIfIsEmpty(untyped_parse) && show_warn) {
    console.warn(
      `\nThe above fields is not used from the json_response \nand need be improved from back-end side. \nThis can result in performance loss\n`,
      untyped_parse
    );
    console.log("");
  }

  /**
   *  This enables JavaScript's automatic processes to remove the variable from memory.
   *  https://javascript.info/garbage-collection
   */
  untyped_parse = null;
  return new_typed;
}

const json_response_decode: Employee = pruneTheLeaves<Employee>(
  JSON.parse(json_response),
  employee_type_descriptor,
  true
);

const json_response_encode = JSON.stringify(json_response_decode);

```
One of the weaks point is that I can't see when is missing nested objects/sub leaf

**Comment by samchon** [comment]
I've completed implemening #211 and #153 may be completed in this week. 

Therefore, I'll try to implement this feature. 

However, before the implementation, I'm confusing how to define the new function's return type. 

@enghitalo, can you prepare the return type definition?

```typescript
// 1st way, use any type?
export function superfluous<T extends object>(obj: T): Omit<any, keyof T>;

// 2nd way, use record type, but how to represent hierarchical type?
export function superfluous<T extends object>(obj: T): Omit<Record<string, any>, keyof T>;
```

**Comment by tjhiggins** [comment]
Looking for the same. Cool library btw. Instead of it being a separate function I'd almost prefer it as an option on validate
```ts
TSON.validate<T>(obj, { superfluous: true });
```

**Comment by Jheniffershteffani** [comment]
Fantastic!!!

I am looking for this feature have a long time, too. I finally found.

I can't wait for it to be implemented.

**Comment by samchon** [comment]
@enghitalo Please define the return type.

Especially, have to consider hierarchical relationship like below case:

https://github.com/samchon/typescript-json/blob/master/test/structures/ObjectHierarchical.ts

**Comment by enghitalo** [comment]
> @enghitalo Please define the return type.
> 
> Especially, have to consider hierarchical relationship like below case:
> 
> https://github.com/samchon/typescript-json/blob/master/test/structures/ObjectHierarchical.ts

Hi, @samchon.

Sorry for delay.

I am not the best guy for TypeScript Type issues but the `export function superfluous<T extends object>(obj: T): Omit<any, keyof T>;` look be the best fit for me.

In addition to seeming simpler to implement.

**Comment by samchon** [comment]
@enghitalo 

Unfortunately, I'd asked to define that type because it is even hard for me. 

Anyway, the `Omit<any, keyof T>` type can represent hierarchical type. I should study about it.

**Comment by enghitalo** [comment]
Really, really, sorry.
I will study more about this, too.
And, may be I can be more useful for you.

**Comment by enghitalo** [comment]
@samchon  What is the branch that you are using for implement the superfluous function?

**Comment by samchon** [comment]
> @samchon What is the branch that you are using for implement the superfluous function?

Not yet, but would be `features/superfluous`
