### ISSUE TITLE
Support the `@default` tag

### ISSUE THREAD

**Issue by Inkdpixels** [samchon/typia#211]
## Feature Request

Really awesome work on this! There are just two things that I miss, one is the following feature: Support of the `@default` tag.

As the library already supports quite common JSDoc tags such as `@minimum` etc as per https://github.com/samchon/typescript-json/issues/175 I think it would be a great addition. This way server side validation can be properly done for optional values where the validator supports infering them, e.g. AJV with the `useDefaults` option.

https://ajv.js.org/options.html#usedefaults

```ts
type Spec = {
  /**
    * @default "foo"
    */
  property: string
}
const schema = TSON.application<[Spec], "swagger">();  // { schemas: [{ type: "object", properties: { property: { type: "string", default: "foo" }} }] }
```

**Comment by samchon** [comment]
I've not seen using `"` symbol on jsDoc tag. Therefore, it seems `@default foo` is better than `@default "foo"`.

If I'm taking a mistake, please inform me.

If agree to using `@default foo`, I'll implement this until Wednesday.

**Comment by samchon** [comment]
@Inkdpixels Look at those files, then you may understand the `@default` tag has been exactly implemented.

  - https://github.com/samchon/typescript-json/blob/19bccd9bc8a2cc888fb82a602f22cb3c17506536/test/structures/TagDefault.ts
  - https://github.com/samchon/typescript-json/blob/19bccd9bc8a2cc888fb82a602f22cb3c17506536/test/features/application/test_application_tag_default.ts
