### ISSUE TITLE
Support arbitrary format values on the `@format` tag

### ISSUE THREAD

**Issue by Inkdpixels** [samchon/typia#212]
## Feature Request
Really awesome work on this! There are just two things that I miss, one is the following: Support of arbitrary format values on the @format tag.

E.g. if one would be generating the json-schema for ajv with this library, the developer should be able to use custom formats.

https://github.com/ajv-validator/ajv-formats

```ts
type Spec = {
  /**
    * @format "date"
    */
  property: string
}
```

**Comment by samchon** [comment]
@Inkdpixels Can you construct a regular expression for the `@format date` tag?

**Comment by Inkdpixels** [comment]
@samchon  Dates are a prime example where regular expressions will not be sufficient, e.g. you could build a RegExp that guarantees the structure of the string, but not the validity of it. 

Take for example the validation logic that was integrated into `ajv-formats` for leap years to meet the [requirements of the OpenAPI spec](rfc-editor.org/rfc/rfc3339#section-5.6)

https://github.com/ajv-validator/ajv-formats/blob/master/src/formats.ts#L136-L149

**Comment by samchon** [comment]
Got it, if you're planning to send a PR, I'll wait it.

If not, I'll implement this in this Saturday ~ Sunday.
