### ISSUE TITLE
typescript-json CLI

### ISSUE THREAD

**Issue by Inkdpixels** [samchon/typia#214]
## Feature Request

Hey @samchon, would you accept a PR that will introduce a CLI that wraps around the `TSON.application()` API?

E.g.

```ts
// src/index.ts
export type MySpec = {
  foo: string
}
```

```sh
npx typescript-json [entryFile] [...options]

# Generates the JSON and prints it into stdout
npx typescript-json ./src/index.ts --typeName=MySpec --purpose=ajv
# OR
# Generates the JSON and writes it into the given output file
npx typescript-json ./src/index.ts --typeName=MySpec --purpose=ajv --out schema.json
```

If you would accept such a feature, I would give it a try

**Comment by samchon** [comment]
It seems good idea, and it is okay to renaming cli from `typescript-json` to shorter or more significant.

**Comment by samchon** [comment]
https://github.com/YousefED/typescript-json-schema

This is what you want to make from this `typescript-json`. Traveling its [source code](https://github.com/YousefED/typescript-json-schema/blob/master/typescript-json-schema.ts), I understood that it never can implement compliate union type. Testing the library and understood that most [test structures](https://github.com/samchon/typescript-json/tree/master/test/structures) of `typescript-json` are being failed.

**Comment by samchon** [comment]
May I ask you the reason why you're converting TypeScript type to JSON schema, to utilize `ajv`, instead of using `assertType` function of this `typescript-json`?

**Comment by Inkdpixels** [comment]
@samchon I am currently working for a client that has some pre-built packages which expect the json-schema to be passed in directly, under the hood AJV will then take over and validate the request/response for a multitude of lambda functions in a standardized way.

So using `assertType` is not an option for this project unfortunately.

**Comment by samchon** [comment]
@Inkdpixels If you're busy, just tell me detailed CLI spec what you want.

```bash
npx typia schema ~
```

**Comment by samchon** [comment]
As you'd not responsed for a long time, I'll do it by myself - #509
