### ISSUE TITLE
Type literal properties get rejected with the name `__type`

### ISSUE THREAD

**Issue by KristjanTammekivi** [samchon/typia#224]
### Summary

assertType produces incorrect errors when using type literals as properties

  - **SDK Version**: master
  - **Expected behavior**: expect to be { b: 1 }
  - **Actual behavior**:  expect to be Resolve<__type>

Write detailed description in here.

### Code occuring the bug
```typescript
import TSON from "typescript-json";

assertType<{ a: { b: 1 } }>({ a: null }); // TypeGuardError: Error on TSON.assertType(): invalid type on $input.a, expect to be Resolve<__type.o1>
```

**Comment by samchon** [comment]
When unnamed type comes, TypeScript compiler names it as `__type`.

It is possible to renaming its type following the type literals like `{ a: { b: 1 } }`, however it can make error content (`TypeGuardError.message` and `TypeGuardError.expected`) to be very long, if very complicate unnamed type comes. Note that, TypeScript compiler considers alias type (`type Something = { a: string }`) as unnamed type, too.

Therefore, I recommend you not to use the unnamed type. If not possible to avoid it, just read only `TypeGuardError.path`.

If you have another idea, please tell me. If not, I won't fix this.

**Comment by KristjanTammekivi** [comment]
How about putting ellipses if the stringified type goes for longer than N characters,
so { b: 1 } would be displayed as is,
but { someProperty: SomeComplicatedTypeLiteral[], someOtherProperty } would be shortened to { someProperty: ... }?

**Comment by thelinuxlich** [comment]
This is a bit sad, I don't even work with interfaces in my codebase :(

**Comment by KristjanTammekivi** [comment]
> This is a bit sad, I don't even work with interfaces in my codebase :(

That's odd, interfaces work just fine for me. Do you mean type literal properties of interfaces?

Which brings to mind another option, instead of showing the stringified type, show the path from the last resolved type,
so SomeInterface['SomeTypeUnion']

**Comment by samchon** [comment]
> This is a bit sad, I don't even work with interfaces in my codebase :(

Paste your interface
