### ISSUE TITLE
Using partial with declare class doesn't work as expected

### ISSUE THREAD

**Issue by tjhiggins** [samchon/typia#226]
### Summary
I wanted to validate on a DeepPartial<T>, but the validation doesn't work as expected when using a type via `declare class`. It seems to work as expected if I use an interface. I included a repl that shows the issue. However, I'm trying to use a type from a third party package that defines its types via declare class.

### Code occuring the bug
Reproducible demo:
https://replit.com/@TJHiggins1/TSON-Partial-Bug#index.ts

```ts
import TSON from "typescript-json";

type DeepPartial<T> = T extends object ? {
  [P in keyof T]?: DeepPartial<T[P]>;
} : T;

const input = { a: 'valid' }

console.log('Works with interface:')

interface TestInterface {
  a: string;
}

const res = TSON.validateEquals<TestInterface>(input);
console.log('valid:', res)

const res2 = TSON.validateEquals<Partial<TestInterface>>(input);
console.log('valid:', res2)

const res3 = TSON.validateEquals<DeepPartial<TestInterface>>(input);
console.log('valid:', res3)

console.log('')
console.log('---------------------------')
console.log('')

console.log('Does not work with declare class:')

declare class TestClass {
  a: string;
}

const res4 = TSON.validateEquals<TestClass>(input);
console.log('valid:', res4)

const res5 = TSON.validateEquals<Partial<TestClass>>(input);
console.log('should be valid:', res5)

const res6 = TSON.validateEquals<DeepPartial<TestClass>>(input);
console.log('should be valid:', res6)
```

**Comment by samchon** [comment]
![image](https://user-images.githubusercontent.com/13158709/194473256-998398ba-b68d-4c67-a650-bb7569cb7b3d.png)

`res5` is bug, but `res6` is not.

I'll fix this bug soon.

**Comment by tjhiggins** [comment]
Out of curiosity why is `res6` not a bug? Partial and DeepPartial should be the same for the example.

**Comment by samchon** [comment]
@tjhiggins Ah, its bug, right. I misunderstood the `DeepPartial` type (I understood that non-object type be `never`).

Anyway, I've fixed the bug what you've reported. Thanks for your good point advising reporting.

Update to `3.3.7` version, then the bug would be fixed like below:

```bash
Jeongho Nam@JH-DESKNOTE MINGW64 /d/github/samchon/typescript-json (v3.3)
$ npm run issue 226

> typescript-json@3.3.7 issue
> node test/issue "226"

Works with interface:
valid: { success: true, errors: [] }
valid: { success: true, errors: [] }
valid: { success: true, errors: [] }

---------------------------

Does not work with declare class:
valid: { success: true, errors: [] }
should be valid: { success: true, errors: [] }
should be valid: { success: true, errors: [] }
```

**Comment by tjhiggins** [comment]
🎉 thanks @samchon! 

I wanted to point out that this test will never fail:
https://github.com/samchon/typescript-json/pull/227/files#diff-c52ef86833d1f670e4fe94a60b94a79c294cdf3c206e3d9b182cad97cb8dba2dR42
