### ISSUE TITLE
Introduce how to setup with pure Create React App

### ISSUE THREAD

**Issue by paradox37** [samchon/typia#233]
Can you update the documentation to provide setup for the pure ReactJS? Also, some examples how to use it in forms with ReactJS would be nice.

**Comment by samchon** [comment]
I recommend to using `vite` following https://github.com/samchon/typescript-json#vite step.

However, you want not to use any boilerplate, right?

It's possible to configuring React project with `webpack` and `ts-loader` and I recommend you to search it in google.

**Comment by samchon** [comment]
TypeScript handbook can be a good guide document.

Follow the https://webpack.js.org/guides/typescript/ step and just add special configuration of `typescript-json` following https://github.com/samchon/typescript-json#webpack

**Comment by paradox37** [comment]
The project used Create React App for the setup, so I would like to integrate and use your library in that setup if possible.

**Comment by samchon** [comment]
I don't know how to in CRA unless call the `npm run eject` command. 

Someone else knows how to?

**Comment by mazhuravlev** [comment]
I wanted to use **typescript-json** in an ejected CRA project, but CRA uses babel-loader and there is no option like getCustomTransformers as in ts-loader.

**Comment by samchon** [comment]
When builing project, Babel removes all types. Therefore, supporting Babel is not possible.

If no way to adapting `ts-loader` instead of `babel-loader`, no way. It would better to use `vite` instead.

**Comment by samchon** [comment]
Will support through #509
