### ISSUE TITLE
Doesn't work with SvelteKit

### ISSUE THREAD

**Issue by newsve** [samchon/typia#236]
Followed the readme and get dozens of errors of these type:

```
 [...]/Somefilesvelte:1:19
 Error: error TS5083: Cannot read file '/myproject/.svelte-kit/tsconfig.json'.
  (svelte(script))
 <script lang="ts">
   import {
...
```

**Comment by samchon** [comment]
Can you make a public repo that can test svelte environment?

**Comment by DetachHead** [comment]
it's because svelte does not support compiler plugins. https://github.com/sveltejs/svelte-preprocess/issues/537

**Comment by samchon** [comment]
Then no way to support it.
