### ISSUE TITLE
 Error on TSON.is(): no transform has been configured

### ISSUE THREAD

**Issue by transcendr** [samchon/typia#240]
## Question
I continue to get the error message related to the transformer in tsconfig.json. I've followed the setup setup.  Could you lmk what I've done wrong here:
https://replit.com/@transcendr/typescript-json#tsconfig.json

many thanks!

**Comment by samchon** [comment]
You configured property name as `transforms`.

Changed it to `transform`.

**Comment by transcendr** [comment]
Hey @samchon thank you for your quick response.  My apologies, but actually that extra 's' must've been something that got accidentally added after I posted here.  The 's' wasn't originally there, and I've removed it now, you can see,  I still get the same error without the proper spelling.  Sorry about the confusion.

**Comment by samchon** [comment]
Build through `ttsc` command, then it would be. Please read the README again.

**Comment by jochamb** [comment]
i ran into a similar issue, and put together a minimal reproduction [here](https://github.com/jasonnnc3/ts-json-debug-example). tried building through `ttsc` and `ts-node -C ttypescript`, wasn't able to get either one working

**Comment by samchon** [comment]
@jasonnnc3 remove below line, then it works fine:

```typescript
{
  "ts-node": {
    "swc": true
  }
}
```

https://github.com/jasonnnc3/ts-json-debug-example/blob/5c786e926cf74929017ee122b8b993c032d94bab/tsconfig.json#L20-L22

**Comment by jochamb** [comment]
works great, thanks for helping out
