### ISSUE TITLE
Support generic keywords 

### ISSUE THREAD

**Issue by giovannicardamone-facile** [samchon/typia#250]
# Support generic keywords 

##  Description

JSON Schema allows to use into schema definition generic keywords (https://json-schema.org/understanding-json-schema/reference/generic.html?highlight=description)

for example:

- title
- description
- examples
- deprecated

and so on.

i was looking into 

https://github.com/samchon/typescript-json/blob/c709379db511b13b334ae9d4abdc0923033a1797/src/programmers/internal/application_schema.ts#L21

and i noticed that none of the keywords above can be "injected" into the schema genearation using `TSON.application`.

as specified in

https://swagger.io/specification/#schema-object

the supported properties for the schema definition are an extended Subset of `JSON Schema Draft 00`

## Feature Request

would be nice to have the capabilities to generate thoose props directly with the jsDoc interface, right now for example using `@description` the generated schema is the following

interface:

```typescript
export interface User{
    /**
     * @description email
     */
    email: string
}
```

generated:

```javascript
email: {
    type: 'string',
    nullable: false,
    jsDocTags: [
        {
            name: 'description',
            text: [ { text: 'email', kind: 'text' } ]
        }
    ]
}
```

instead should be generated in this way:

```javascript
email: {
    type: 'string',
    nullable: false,
    description: "email"
}
```

**Comment by samchon** [comment]
If you want to fill the `description` property, just write down the content without `@` symbol like below:

```typescript
interface Something {
    /**
      * This content would be placed into the `description` property.
      */
    email: string;
}
```

**Comment by samchon** [comment]
About other properties, I'll support them soon. Thanks for suggestion.

**Comment by samchon** [comment]
Update to `3.3.20`, then you can meet your suggested features (except `examples`).

About the `examples` property, I haven't implemented it because expressing object example data as a descriptive comment is not possible.
