### ISSUE TITLE
Unknown problem

### ISSUE THREAD

**Issue by ObscurusGrassator** [samchon/typia#271]
( TypeGuardError: Error on TSON.assertType(): invalid type on $input, expect to be (Resolve<__type.o1> | Resolve<__type>) )

Details in example:
[playground](
https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgQwM6oKawCoE8wYqpGaxwC+cAZlBCHAOQz4aoDGUwYMAtAFaoIAOwYBuAFCTxzAnABSEYEIA8AaQA0cAAoA+OAF44quBgAeMDEIAmxVDE5CA5nAA+cIQFcQAIyzi4AXAA-Nom5pY2cHYOzm6ePn6BScFwAAYAJAiq5JkMDGEW1sRaKXlwAFyMAHQMOQha5Kn+yQGVQhgAbomBbZ1YEtIs2lCdBnAA2u1dUJoADJoAjJoATJoAzJoALJoArJoAbJoA7JoAHJoAnAC6AzKEAMr2So5ayDAAFgAyGMhdqADyVGU-00ADExgwAHoAUgAxAAydIAQgAAgxNAARAoRYjxXxQMabHTNAKGcYYq7YooTKZYSkhWlQEnJSr-KmRCDePgYNgwZktAIhJDjYxKOAAawwuAgVDg-yuPCC5X5AqS-xFlLMhUi4IZfQJlQUSjUmkeMVeH2+v1YgOBGrBmi0Iw65KuOj05HGkulsvlKpalTytyGeAIgIt72U9zY7wwIGQ7OICC9lWizyulWQQlw5FNiaiTycmPzeKwhOJSTJFPzk319Pc+v9FTg93zGQQSioZew5CqmU7ZYAqo0UqGMOG3pHo7H4+NsFdNIPHc7XRWBZVp3HkON7jcpJIzJAyGxhHY4KCAJKfbAAUQASgB9f5ae8AQWwF-+ADkHwBZV9aFoF5fgA4g+9zYHewFgdg-zgZB0FjAgzIADbAJKlSrMyQgQDAnzoRglQbMyqAeN4aZOJU2wkTAyCwKgADqwAfJUezMjiTEsXAhziOQEiHtA8AnkIZ6Xte94PgAwt+GIXh+35-gBQGgUhzLQJh6jMlmVhEZpSQ4TAVGaXx+53HAABqyAoR4GBjhCFGONgEBms8+RuAwDlOV+Xj4m5jAOf8UDeQkUB+QwpZQK+UBQMguBhXRMVxRIZkRnZyjMtgyDeChGCbvG+bJuKqaFo4GYoNmlBuB41gYFQSgYFYemBHZWo4hZVk2WOTUBJJEDWSAImqq11JRYlyiZdluUxlu+bVVYtX1VYKQOc2LlOBGVp-LaE05XlyDuq4cBzQt7RLYYx11ad3VwL1-UiTephsNZ835qNsXjVlu3Tflw2RBdi3LSVq0lRtPxbUCO1TTO+16FVNWXQ1Yz-Vd4h6IYD1PR483pUkt1eINv3EFmuDjPWAAUeMDcQhNwG9uDKAOBLYHoITYM2jIAJRNpULXhNSHklU5a2OPkITC6D1oAhDn1Q1umgRYd3gQH1PxCGuAZwLz2rEALMReT5WCiy2IOTptNrS5Ne2aCtbhKyrWbqyyxvmqbYPmx9lvfft12U-dj3PYQNN0wzQhdkzLOa82yMNajEgAPRx3KqjiAnJBYDAyipSwyhIMgyBtAbUCiHA3jeJUCCmKYBchZouC4MVMR8XAbBsA3zzF7m-mC85JUMO6ZMMKXVR1w+3jIFYDAcwMAlkGZoLAChFhQAAQrgcA44E-wEDFMDAKeBUpgWMRlcTuYZUMNOWdZtksNdkN7QfRVH+mmYVYd0dnUd8OLT7fX48QAog7RXevfL2s1v6nUBjEYGLtLRuylh7L60MDpw3mgjT+H9f53VQBjAOr1gH01AdDcBaCAYhBWhuE2cDJbbRlntFBX9SGQPOhAhq10Iz5izgQRBst4yaC6jdP+VNNC+xwf7LGGA0baEnGOHhVtNa30EdgkRQi-aY3mjoTSUiiEzRph-ZkQomwQG3m8PeQhKjehlHKExu9TwSFVCeO6lRRH5mJqTFIFNVHUz5pEYOjNNYRzZr0aYHNmwOXsQKDoHVCIKNkDTcKhc6ZG3GDbdwhdrZAziIXK4TYkg8wvj4nWCVYpG2DqkiKjtVT5LiYUruese4xCNg5XJPRYmB1qbrZ4+sQpNJKi01oz8nCHQihEgIlBy5Ni9FKOAYoIxlWQqqJIxisCmOEBYqUVit4rNsSJUZizHH42cV41x2Z3EhE8dg-BY1-HM1HOzfUoT1m4D2aqKJ19qntO1owCKST+mLJCHOFgE4PjKFwRIuRXtNAf00RKKUMKxzAsjGC7GOi+GMJOg1GF3odA5MWeuNp+ZOlOCFr3KBzw-l5IJfEzyEBgq+TJU4ClrStZtQYMUuKKRg4IqoBGUF4iUV0Mhei9BWK4WVLxc2blvLkUYAhdDKFrCrCitwDoF5gRyDMk9HMgYwkzwWDsMsSo89F5YFXsoO4VixK3kfM+N88kfz-kAtBeCUFQIPlgi66CmgiWOQaa5a6ud85pJCsXUu5dK7V3xLXeugzHBNxbm3JwHcFVMLYRMNlyAGA5KkQgA5A1AxDzruiOAyyd5mMDGhSUxa3k2UDKgGwtQdWnhVlUFCEBHBkwWF2qekhU7-GTqnNApAM4p0TkkY1S8zUWtlFaiStq7zvk-A6pSzqIKupgnBNdXq6ldL9U4dEo7FmBsjf0EuZdEARuDVGuAddE1xuTcKn+6a85ZsPf3Q9SRc2qILd4YeuBR7j2LaW1Z5jGCVowNW6JgYspsFqIent4hdUtrbR25YaGEN9uMGTce80lqpGbq3WNxdUgc00N4Dw8AQCsFQMgRwhBgDEA8I4FCMaxwgQ8HRKwN5orqTgNx2gBJhCa3uN+KoQ705jjJhzSoSg3nACWmZIT6QlBgAo5oQ8PJ4AwAgCXQgZM7ysD6l0ZQD4Hx3CqBABYsM4AGcEChYzpm7g6C5oO9A6d0qp3HQvSd9Np3nivNap8L4F32sUk6t1W63UesiyBb1NLhYHs8wKY9V7T1hovVXVLMwb0xocvGwj4SKApoxY1Z9macmp3fUlgIX6nGMELf+seE9NDAZ2RWgikH3mMBg3B1OCGDymCPFpoYE6ywbwCKihMNNCp3pPm-VBJWkaKqwf-IatSuWCuIXoxVDLnCUNgV8eBtDPbIOsx-JbqbGrMlETKq5IDNu6Nqed8hQN9vPAluDOVW4GHnZYZd66WIaYK0MNRKRroayMnrIyZklQAijZXr5lglqAtzuC4uhSjrlJgRi+6zdCFQJxe7gl-hD20WiJUdgmVsMmyFRmUIWFPo4B+dnY+aSX5ZKhcx9BK4SpzzeawF9snXiKf-xlcuToq5KBNpElp1gMA1hGv51AHOKAg0jLPeGzLEVo13vy3ejuOgE7FfQZocYg9f2VyzY7QwCBeO25seWsDHXNB5tA+bv9nXa31ZQpm8gJlEPNpyq29tZM1hh4w4nfth7xOwGUHzk1yuUvq-SxXLX6Scu64N3AHQZMP2BFt1AcurXHcMHA8W13P6-0Aea3AGtMS2XeFg37+D0u7MYGDx2zYXeI+16svJt4hAqDIAXnAbDVhcNpAI-rtIXMY8Z3j0vFXecT1Fw1xllfOvY166IxQPQOfmQF6Lw7tZTuq0u+-fV39I8mue-rz15vCGkNB5Q2THYb+e1AA
)

package.json :
```json
    "devDependencies": {
        "@types/node": "18.7.18",
        "ttypescript": "1.5.13",
        "ts-node": "10.9.1",
        "typescript": "4.8.3"
    },
    "dependencies": {
        "typescript-json": "3.3.8"
        // "typescript-json": "3.3.14" - same problem
    }
```
Node.js: v18.8.0
NPM: 8.18.0

**Comment by samchon** [comment]
Need to deep research. I'll try this on Saturday.

**Comment by samchon** [comment]
```typescript
type Test555 = Filter<{
    aa: number;
    bb: { xx: number; yy: string };
    cc: string;
}>;
const value: Test555 = {
    or: {
        and: {
            or: {
                not: {},
            },
        },
    },
};
```

I understood the reason why. Following your type spec, above object does not be error. The reason why TypeScript caught `{ operation: "like", column: "bb.yy_bad", value: "abc" }` is TypeScript recently added a new restriction that type meta programming cannot over 50 depth. However, `typescript-json` does not have such restriction, therefore `typescript-json` does not consider it as error.

To make it error, you can choose two option. One is using `assertEquals()` function instead and the second options is enhancing your type not to allow such empty object by disallowing undefindable property. The 2nd option may make your type much complicate, but it seems the correct way.

Thanks for wait for a long time.

**Comment by samchon** [comment]
```typescript
export interface EmptyObject {
    [key: string]: never;
}
```

I found 3rd option. You make an empty object type like above and let `typescript-json` to add such case logic.

How do you think about it?

**Comment by samchon** [comment]
Below script is a generated JS code from `typescript-json`. It seems too complicate, but need researching.

```javascript
"use strict";
var __importDefault =
    (this && this.__importDefault) ||
    function (mod) {
        return mod && mod.__esModule ? mod : { default: mod };
    };
Object.defineProperty(exports, "__esModule", { value: true });
const src_1 = __importDefault(require("../../src"));
const FILTER_OPERATION_MAPPING_STRING_TO_STRING = {
    like: 2,
    notLike: 3,
    substring: 4,
    startsWith: 5,
    endsWith: 6,
};
const FILTER_CONDITION_MAPPING = {
    or: 2,
    and: 3,
    not: 4,
};
const value = {
    or: { operation: "like", column: "bb.yy_bad", value: "abc" },
};
const is = (input) => {
    const $join = src_1.default.createIs.join;
    const $io0 = (input) =>
        ("substring" === input.operation ||
            "endsWith" === input.operation ||
            "startsWith" === input.operation ||
            "like" === input.operation ||
            "notLike" === input.operation) &&
        "cc" === input.column &&
        "string" === typeof input.value;
    const $io1 = (input) =>
        ("substring" === input.operation ||
            "endsWith" === input.operation ||
            "startsWith" === input.operation ||
            "like" === input.operation ||
            "notLike" === input.operation) &&
        "bb.yy" === input.column &&
        "string" === typeof input.value;
    const $io2 = (input) =>
        (undefined === input.or ||
            ("object" === typeof input.or &&
                null !== input.or &&
                $iu3(input.or))) &&
        (undefined === input.and ||
            ("object" === typeof input.and &&
                null !== input.and &&
                $iu3(input.and))) &&
        (undefined === input.not ||
            ("object" === typeof input.not &&
                null !== input.not &&
                $iu3(input.not)));
    const $io3 = (input) =>
        (undefined === input.or ||
            ("object" === typeof input.or &&
                null !== input.or &&
                $iu2(input.or))) &&
        (undefined === input.and ||
            ("object" === typeof input.and &&
                null !== input.and &&
                $iu2(input.and))) &&
        (undefined === input.not ||
            ("object" === typeof input.not &&
                null !== input.not &&
                $iu2(input.not)));
    const $io4 = (input) =>
        (undefined === input.or ||
            ("object" === typeof input.or &&
                null !== input.or &&
                $iu1(input.or))) &&
        (undefined === input.and ||
            ("object" === typeof input.and &&
                null !== input.and &&
                $iu1(input.and))) &&
        (undefined === input.not ||
            ("object" === typeof input.not &&
                null !== input.not &&
                $iu1(input.not)));
    const $io5 = (input) =>
        (undefined === input.or ||
            ("object" === typeof input.or &&
                null !== input.or &&
                $iu0(input.or))) &&
        (undefined === input.and ||
            ("object" === typeof input.and &&
                null !== input.and &&
                $iu0(input.and))) &&
        (undefined === input.not ||
            ("object" === typeof input.not &&
                null !== input.not &&
                $iu0(input.not)));
    const $io6 = (input) =>
        null !== input.or &&
        undefined === input.or &&
        null !== input.and &&
        undefined === input.and &&
        null !== input.not &&
        undefined === input.not;
    const $iu0 = (input) =>
        (() => {
            if ("cc" === input.column) return $io0(input);
            if ("bb.yy" === input.column) return $io1(input);
            return $io6(input);
        })();
    const $iu1 = (input) =>
        (() => {
            if ("cc" === input.column) return $io0(input);
            if ("bb.yy" === input.column) return $io1(input);
            return $io5(input);
        })();
    const $iu2 = (input) =>
        (() => {
            if ("cc" === input.column) return $io0(input);
            if ("bb.yy" === input.column) return $io1(input);
            return $io4(input);
        })();
    const $iu3 = (input) =>
        (() => {
            if ("cc" === input.column) return $io0(input);
            if ("bb.yy" === input.column) return $io1(input);
            return $io3(input);
        })();
    const $iu4 = (input) =>
        (() => {
            if ("cc" === input.column) return $io0(input);
            if ("bb.yy" === input.column) return $io1(input);
            return $io2(input);
        })();
    return "object" === typeof input && null !== input && $iu4(input);
};
console.log(is(value));

```

**Comment by ObscurusGrassator** [comment]
\o/ Thank you very much :-) . I wouldn't solve this myself.

**Comment by ObscurusGrassator** [comment]
I try wrap line:
```ts
{[k in keyof typeof FILTER_CONDITION_MAPPING]?: Filter<TableSchema, Columns, ColumnsExclude, Prev[D]>} ;
```
to `ObjectWithOnePropertyOf<>` type:
```ts
ObjectWithOnePropertyOf<{[k in keyof typeof FILTER_CONDITION_MAPPING]: Filter<TableSchema, Columns, ColumnsExclude, Prev[D]>}> ;
```
but typescript compilation is in totaly endless loop.

Source code from: [stackoverflow.com](https://stackoverflow.com/questions/62158066/typescript-type-where-an-object-consists-of-exactly-a-single-property-of-a-set-o)
```ts
type Explode<T> = keyof T extends infer K
    ? K extends unknown
        ? { [I in keyof T]: I extends K ? T[I] : never }
        : never
    : never;
type AtMostOne<T> = Explode<Partial<T>>;
type AtLeastOne<T, U = {[K in keyof T]: Pick<T, K> }> = Partial<T> & U[keyof U]
export type ObjectWithOnePropertyOf<T extends {[key: string]: any}> = AtMostOne<T> & AtLeastOne<T>

// const test: ObjectWithOnePropertyOf<{ a: number; b: number; }> = {b: 3}; console.log(test);
```

By the way, I think that if your typescript-json library will behave differently from typescript, then even if there is no error in typescript-json, the user will write you a new issie,  because the user doesn't know how it works inside.
