### ISSUE TITLE
`',' expected` when using type imports

### ISSUE THREAD

**Issue by colecrouter** [samchon/typia#272]
Type imports don't seem to be working as intended. I'm getting this error:
```
src/routes/v1/tokens/[id].ts:1:39 - error TS1005: ',' expected.

1 import { Errors, type ScopeValue } from '...';
                        ~~~~~~~~~~
```

Note that doing the following does work:
```ts
import { Errors } from '...';
import type { ScopeValue } from '...';
```

I'm using TypeScript 4.4.

**Comment by samchon** [comment]
It seems that type keyword in bracket is not supported by TS 4.4

How about upgrading it to TS 4.8?
