### ISSUE TITLE
Proposal: Protocol Buffers Support

### ISSUE THREAD

**Issue by lemon-mint** [samchon/typia#294]
# Proposal: Protocol Buffers Support

Author: @lemon-mint

Last updated: November 2, 2022

## Abstract
This proposal introduces a protocol buffers API for typescript-json.

## Background

Protocol Buffers has been used as the industry standard binary serialization format,

It is clear that there is a need for efficient data exchange between TypeScript and other languages.

Protocol Buffers allows language-neutral data exchange, but the proto3 file format didn't work well with TypeScript types.

## Proposal

I propose the following API changes:

* Add Purpose Type `"proto3"` to `TSON.application`
    ```ts
    TSON.application<T, "proto3">();
    ```
    `TSON.application<T, "proto3">` returns a "proto3" representation of TypeScript type `T`.
* Add Comment Tag Types
    ```ts
    /**
     * @proto {number}
     * @proto_type { protobuf types "int32"|"string"|... }
     */
    ```
    `@proto` is a comment tag that specifies the field number of the field.

    `@proto_type` is a comment tag that specifies the type of the field.

    If `@proto_type` is not specified, the type of the field can be inferred from the type of the field.
* Add Protocol Buffer Serialization Support
    ``` ts
    TSON.protoify<T>(value: T): Uint8Array
    TSON.protoparse<T>(buffer: Uint8Array): T
    ```

### Example Tags

```ts
export interface TagExample {
    /**
     * @proto 10
     * @proto_type uint32 // "proto_type" annotation specifies the protobuf type
     */
    term: number;

    /**
     * @type int
     * @proto 15
     * proto_type int32 // Infered from "type" annotation
     */
    nonce: number;

    /**
     * @proto 20
     * proto_type optional string // "optional" inferred from "?" in type
     */
    votedFor?: string;

    /**
     * @proto 30
     * proto_type bytes
     */
    data: Uint8Array;

    /**
     * @proto 40
     * proto_type map<string, string> // "map" inferred from "Map" in type
     */
    map: Map<string, string>;
}
```

**Comment by samchon** [comment]
It seems really good idea. I'll study and try it.

**Comment by lemon-mint** [comment]
Proto3 Spec: https://protobuf.com/docs/language-spec

Proto3 JS Parser: https://github.com/bufbuild/protobuf.com/tree/main/examples/nearley_js

Encoding format: https://developers.google.com/protocol-buffers/docs/encoding

**Comment by samchon** [comment]
Completed.
