### ISSUE TITLE
Either-Or function to validate types, just upgrade IValidation to get advantage out of narrowing

### ISSUE THREAD

**Issue by roman-shpp** [samchon/typia#344]
## Feature Request 
Let's update IValidation to be more useful and also support type narrowing.

My vision:

```typescript
type IValidation2<T = unknown> = { success: true, result: T } | {success: false, errors: IError[] }
const a = {success: true, result: 10} as IValidation2<number>;
if (a.success) {
    console.log(a.result)
    // console.log(a.errors); // ERROR, thanks to narrowing
} else {
    console.log(a.errors);
    // console.log(a.result); // ERROR, thanks to narrowing
}
```

It brings multiple benefits: 
1) this option will be widely used by those who don't like exceptions
2) the only method which allows you to get _either_ final value with proper type _or_ clear errors description
3) narrowing allows to safely manipulate both result and errors

**Comment by samchon** [comment]
It is possible to chaning `IValidation` type to union like below.

However, I can't sure that separation is really required.

Also, I wanna ask you that why do you want to store the input value as `result`?

```typescript
type IValidation = IValidation.Success | IValidation.Failure;
```

**Comment by samchon** [comment]
Considering your suggestion, it seems reasonable.

The result value can be utilized as successfully converted value.

This feature would be added at `3.4.0` update.

**Comment by roman-shpp** [comment]
> Also, I wanna ask you that why do you want to store the input value as result?

the idea is to get functional approach, when the response from validation function can be passed to next code without need to also pass raw data and do manual type adjustment like `const validated = original as MyType` (this way requires more copy-pasting and also may bring some errors).

Another way to get what I want could be to write some wrapper (let's call it `functionalValidate`) around validate func and call it like this:
```typescript
  const validated = functionalValidate(data, createValidate<Type>()); 
```
... but again it's too ugly, so having built-in TSON method with requested functionality brings much more beautiful code.

> It is possible to chaning IValidation type to union like below.

Yep! Something like this. The most important part here is to make it a [discriminated union](https://www.typescriptlang.org/docs/handbook/2/narrowing.html#discriminated-unions), again for type safety.

I'm a big fun of discriminated unions and writing code without need to try..catch stuff, so I'm very happy to see that you liked my idea. 🙏

**Comment by samchon** [comment]
How about adding a more suggestion that can replace `assert()` function, which reports only the first error?

When suggesting, the new function name should be only one word, so please do not make them a compound word.

**Comment by roman-shpp** [comment]
Sorry, but I didn't understand you(
The following points may be based on misunderstanding, but anyway to speed up communication my thoughts are:

1. Do you think it's worth adding additional function to family of is/assert/validate? I do not think it's good idea.
2. I'm not sure there's need for "Only the first error" thing if you already get all errors, but some toString function for all these errors will be quite handy. kind of `TSON.pretty(validationResult.errors) -> string`
3. Regarding naming, there are some more words like "check", "confirm", "match", but I'm not sure if they work for your idea.

**Comment by samchon** [comment]
Okay, don't mind about it.

You can use this feature earily through below command.

```bash
npm install --saved typescript-json@next
```

**Comment by roman-shpp** [comment]
Looks good! I see that `data` is present in both Success and Failure cases (yeah, T vs unknown)
Ideally there should be no way to mention `data` at all on compiler step, before type narrowing happens.
Explanation:

```typescript
const validated = TSON.validate<...>(d);
// forgot to check validated.success....
// express
res.status(200).json(validated.data); // PROBLEM: will work even if validation fails!
```

My offer:

```typescript
    interface ISuccess<T> {
        success: true;
        data: T;
        errors: [];  // did you leave it for backwards compatibility? ideally field should not exist. success=true is enough.
    }
    interface IFailure {
        success: false;
        rejected: unknown; // <-- `rejected` is different prop name so compiler will definitely spot the bug
        errors: IError[];
    }
```

What do you think?

**Comment by samchon** [comment]
It was intended to use the same attribute name.

However, considering your use case, it would better to rename the data property. Also, erasing the property can be considered.

How do you think about it? Rename or erase?

**Comment by roman-shpp** [comment]
Haha, hard choice! 
Let's probably erase it and then add if someone needs.
At least, I _personally_ don't need it in IFailure.

**Comment by samchon** [comment]
Upgrade to `v3.3.36`, then you can meet new `IValidation` type.
