### ISSUE TITLE
Using an interface with the same name as a primitive causes it to be substituted with the primitive

### ISSUE THREAD

**Issue by wesselvdv** [samchon/typia#346]
### Summary
Write a short summary of the bug in here.

  - **SDK Version**: 3.3.31
  - **Expected behavior**:

No errors

  - **Actual behavior**: 

The following error is given:

```
{
  "success": false,
  "errors": [
    {
      "path": "$input",
      "expected": "string",
      "value": {
        "String": {
          "str": "broken"
        }
      }
    }
  ]
}
```

### Code occuring the bug
```typescript
import TSON from "typescript-json";


interface String {
  str: string;
}

console.log(
  JSON.stringify(TSON.validateEquals<String>({ String: { str: 'broken' } })),
);
```

**Comment by samchon** [comment]
Considering `String` class type as `string` primitive type is intended feature of `typescript-json`.

However, there can be someone that defining same name of the primitive related class type like you.

I will handle such special case in this Saturday.
