### ISSUE TITLE
TypeScript v4.9 update breaks plugins

### ISSUE THREAD

**Issue by samchon** [samchon/typia#351]
It seems critical bug on typescript or ttypescript has been happend.

Therefore, roll back to TS v4.8 for a while

**Comment by samchon** [comment]
It seems that would be fixed soon.

https://github.com/microsoft/TypeScript/issues/51542

**Comment by DanielRosenwasser** [comment]
4.9.4 is now out FWIW

**Comment by samchon** [comment]
@DanielRosenwasser Thanks for your service, but it is not working in my case. 

I need to check where the error has happend. Whether TS or `ttypescript`.
