### ISSUE TITLE
Support container for optional values

### ISSUE THREAD

**Issue by wesselvdv** [samchon/typia#359]
Would it possible to support containers for optional values like this one: https://github.com/fp-ts/data/blob/main/src/Option.ts? So instead of me supplying a type of:

```typescript
interface b = {
  a?: string;
}
```

I would have a type of:

```typescript
interface b = {
  a: Option<string>;
}
```

I imagine there might be other cases for other custom containers (Map, Set, HashMap, HashSet, etc.), where you might want to be able to specify how to encode/decode/guard/refine etc.

**Comment by samchon** [comment]
I read `Optional` type of the `fp-ts` and understood that, it never can replace the `TypeScript`'s undefinable type.

When you use the `Option` type of `fp-ts`, `typescript-json` will handle the type following its definition.

```typescript
type Option<T> = None | Some<T>;
type None = { _tag: "none"; };
type Some = { value: T; _tag: "some" };
```

If you want to validate custom container class, convert the container to be primitive object through `toJSON()` method. After the converting, validate the primitive instance through a `Primitive` type which can convert container class type to its return type of `toJSON()` method.

 - https://github.com/samchon/typescript-json/blob/master/src/Primitive.ts

```typescript
const container: SomeContainer;
const primitive: Primitive<SomeContainer> = container.toJSON();
TSON.validate(primitive);
```
