### ISSUE TITLE
Remove `clone()` functions

### ISSUE THREAD

**Issue by samchon** [samchon/typia#393]
No more required.

Also, it validates `T` type before cloning, but required for user is validating `Primitive<T>` type.

**Comment by gpa** [comment]
I just checked out this library for this function :D is there an alternative?

**Comment by samchon** [comment]
`JSON.parse(TSON.stringify<T>(input))` can replace it.

**Comment by gpa** [comment]
It doesn't, my use case was to convert a class T to interface I so that the resulting object contains only properties defined in the interface I without additonal properties from T
