### ISSUE TITLE
Can't I use TSON with Nest framework?

### ISSUE THREAD

**Issue by real-cupist** [samchon/typia#399]
## Question
Hello. I'd like to inquire about Typescript-json.
As you mentioned in the package description, we need a TTSC compiler for the application of Typescript-json, so would it be difficult to use it with the Nest framework?

Nestframework does not support setting of separate compiler options and provides TSC-based compilers to continuously face the error `TSON.assertEquals(): no transform has been configured` when using TSON-related functions inside the application.

Therefore, I would like to ask if there is a compatibility or a separate method for the TSON library and the Nest framework.

안녕하세요. Typescript-json 적용에 난항을 겪고 있어 호환성 관련 문의드립니다.
패키지 설명에서 언급하셨듯 Typescript-json 적용을 위해선 TTSC 컴파일러가 필요한데, 그럼 Nest framework와는 사용이 어려울까요?

Nest framwork에선 별도의 컴파일러 옵션 설정을 지원하지 않고 TSC 기반 컴파일러를 제공해서 어플리케이션 내부에서 TSON 관련 함수 사용시 'TSON.assertEquals(): no transform has been configured.' 에러를 지속적으로 마주합니다.
혹시 별도의 사용법이나, 설정이 있을지 문의 드립니다. 사용중인 Typescript veerison은 4.8.4 기준입니다.

**Comment by samchon** [comment]
Visit [nestia-helper](https://github.com/samchon/nestia-helper), then you may find what you want.

Also, to build swagger or SDK library for client developers, it would better to use [nestia](https://github.com/samchon/nestia) at the same time.

For reference, I'm planning to rename those packages like below (maybe 2023-01):

  - `typescript-json` -> some shorter name (maybe `typia` or `ttype`)
  - `nestia-helper` -> `@nestia/core`
  - `nestia` -> `@nestia/sdk`

**Comment by real-cupist** [comment]
Thank you for your answer! I should consider the direction of applying nestia-helper.
Additionally, is it possible to apply validation in business logic in Nestia-helper? Like using `TSON.assertEquals<SomeType>(typeObject)`

**Comment by real-cupist** [comment]
On another note, if you are planning to rename the Typescript-json package, I recommend `Tyson`...! It's catchy...!

**Comment by samchon** [comment]
Why do you need `assertEquals()` function instead of `assert()`? It is possible to add configuration option feature choosing one of validation functions, but wanna know the reason why. Also, `typson` has been occupied by another one.

**Comment by real-cupist** [comment]
It does not have to be an assetEquals() function. However, I wonder if I can simply check runtime validation in business logic other than API Param or Body. Can a decorator like Nestia Helper's @TypeBody do this?

**Comment by samchon** [comment]
`@TypedBody()` uses `TSON.assert()` function.

When request body data is not matced with type `T`, it returns 400 error.

**Comment by real-cupist** [comment]
Everything I was curious about has been resolved. Really Thank you!
