### ISSUE TITLE
Correct handling of the spread operator in types

### ISSUE THREAD

**Issue by janvanbouwel** [samchon/typia#407]
### Summary

typescript-json does not properly support types with the spread operator (`...`). It can be used to define a type of lists with at least one element `[string, ...string[]]`, but typescript-json handles it like `[string, string]`.

I don't know how difficult this is to implement, but at least an error message (preferably at compile time) would be nice.

### Code occuring the bug
```typescript
import { is, validate } from "typescript-json";


// const a: [string, ...string[]] = []; //Typescript errors for this one
const b: [string, ...string[]] = ['a'];
const c: [string, ...string[]] = ['a', 'b'];
const d: [string, ...string[]] = ['a', 'b', 'c'];
// the other three typecheck

console.log(is<[string]>(['a']));                       // true, expected true
console.log(is<[string, ...string[]]>(['a']));          // false, expected true

console.log(is<[string, ...string[]]>([]));             // false
console.log(is<[string, ...string[]]>(['a']));          // false, expected true
console.log(is<[string, ...string[]]>(['a','b']));      // true
console.log(is<[string, ...string[]]>(['a','b','c']));  // false, expected true


console.log(validate<[string, ...string[]]>(['a','b','c']));
// {
//   success: false,
//   errors: [ { path: '$input', expected: '[string, string]', value: [Array] } ],
//   data: undefined
// }

// validator expects [string, string] instead of [string, ...string[]]
```

**Comment by samchon** [comment]
@janvanbouwel update to `v3.3.44`, then it would be fixed.

However, one thing important is, this feature is not perfectly supported.

As TypeScript compiler API does not support rest type in its `ts.Type` class, I had to implement this feature just by analyzing programming script node instances directly, and it can't detect special case like TMP (type meta programming), using rest type of tuple type through conditional generic type.

To make this feature more stable, I'll suggest TypeScript to support the rest type in formal `ts.Type` class spec.
