### ISSUE TITLE
typia ignore yarn

### ISSUE THREAD

**Issue by green1052** [samchon/typia#418]
i tried to typia setup
but typia install package for npm but i am using yarn

![image](https://user-images.githubusercontent.com/34261355/207951035-c7d2c847-4c66-4751-8223-47743a643e13.png)

**Comment by samchon** [comment]
https://github.com/samchon/typia/wiki/Setup

You should use manual setup.

Anyway, you need additional command like below?

```bash
npx typia setup --compiler=ts-patch --manager=yarn
```
