### ISSUE TITLE
typia with vite js in development mode: refresh gives the penultimate code version

### ISSUE THREAD

**Issue by jlguenego** [samchon/typia#435]
### Summary
Using `typia `with `vite `js (vanilla typescript). Follow all the typia setup instructions. When saving file in visual studio code (ctrl+S), `vite `reload the application, but not the latest code, the penultimate code (second last). So I need to do twice CTRL+S to really refresh.

**You can reproduce the code as follow:**
clone this repo : https://github.com/jlg-formation/tsr-dec-2022
go to the `front `directory, and run `npm run dev`.
Update some part of the typescript code.
do CTRL+S. It refreshes the penultimate code.
do again CTRL+S. It refreshes the last code.

**Expected:**
One CTRL+S should be enough.

Note that if in the `vite.config.ts` file you remove the `ttypescript` plugin, only one CTRL+S is needed (as usual).
So the problem is related with `ttypescript `and may be `typia `plugin.

**Comment by samchon** [comment]
https://github.com/samchon/typia/issues/259

https://github.com/vitejs/vite/issues/10952

It is a bug from `vite`, but seems something hard. 

Sorry for cannot be helpful.

**Comment by hanayashiki** [comment]
if vite is currently not supported, it is hard to be used in actual production

**Comment by samchon** [comment]
@hanayashiki @jlguenego No way right now, just click save button twice.

If this vite bug does not be fixed for a long time, what about making a plugin automatically save twice whenever click the save button?

**Comment by samchon** [comment]
Will support through #509
