### ISSUE TITLE
Prohibit `bigint` type in JSON functions

### ISSUE THREAD

**Issue by samchon** [samchon/typia#444]
`JSON.stringify()` function and JSON schema cannot use `bigint` type.

**Comment by macols77** [comment]
Why did you prohibit bigint? Is there not a way to use some sort of custom transformer to transform bigint into string and the other way around? We're using your library but it's a lot of hurdle to change all our DTOs from bigint to string all the time.

Thanks in advance!

**Comment by samchon** [comment]
It is the spec of JS. No way to avoid it.

**Comment by miyaji255** [comment]
Is it difficult to generate the second argument reviver of JSON.parse from type information?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse#the_reviver_parameter
