### ISSUE TITLE
does `stringify` preserve object key order? 

### ISSUE THREAD

**Issue by rencarKTR** [samchon/typia#453]
Hello!

in es2015+ spec, property order is preserved in JSON.stringify, even though actual implementation might not preserve order

```
JSON.stringify({
  t: 1,
  y: 2,
  p: 3,
  i: 4,
  a: 5,
})

//  --> "{t:1, y: 2, p: 3, i: 4, a: 5}"    // not: {a: 5, i: 4, ... }
```

Is ordering preserved in Typia? If it is, is it based on the generic type param or call-site?
(or is it configurable?)

eg)
```
typia.stringify<{ t: number, y: number }>({ y: 2, t: 1}) 
// case1: if defined by type {t: 1, y: 2} 
// case2: if defined by call-site: {y: 2, t: 1}
```

Thank you!

**Comment by samchon** [comment]
Do not preserve. It re-order sequence for optimization.

Also, sequence of properties follows not construction sequence, but object type definition.

**Comment by rencarKTR** [comment]
ok! case1 it is!
(case1 is much better than es2015 spec for comparison consistency)

Thank you for the answer!

**Comment by samchon** [comment]
Typia follows sequence of object type definition, but mix it a little bit:

### Static key typed property first, dynamic key typed property later
https://github.com/samchon/typia/blob/c1e9afc0a557dd329110c2597e7e52184eb21ea9/src/programmers/helpers/StringifyJoinder.ts#L26-L36

```typescript
export type ISomething = {
    something: string; // static
    [key: string]: string; //dynamic
}
```

### Required first, undefindable later
https://github.com/samchon/typia/blob/c1e9afc0a557dd329110c2597e7e52184eb21ea9/src/programmers/internal/stringify_regular_properties.ts#L79-L81

```typescript
export interface ISomething {
    required: string;
    not_required?: string;
}
```
