### ISSUE TITLE
How to make typia work with SST (https://sst.dev/)?

### ISSUE THREAD

**Issue by bjornlll** [samchon/typia#454]
## Question
How to make typia work with SST (https://sst.dev/)?

I'm using [SST](https://sst.dev/) to build an app on top of AWS Lambda. To run my lambda functions, I need to run `npx sst start`. Since `sst` decides which typescript compiler to use, I can't use `ttypescript`.

```
Error: Error on typia.validate(): no transform has been configured. Configure the "tsconfig.json"
file following the [README.md#setup](https://github.com/samchon/typia#setup)
```
☝️ That's the error that I get.

Is there any way I can get `typia` to work for me without having to change TS compiler? Happy to provide more context, if needed.

**Comment by samchon** [comment]
I do not know SST. Will you try through ts-node and tell me the result?

https://github.com/samchon/typia/wiki/Setup#ts-patch

If not works, I will try the SST after home.

**Comment by bjornlll** [comment]
I've tried setting it up with `tc-patch` but haven't managed to make it work, so far. It seems to be a configuration issue on my side, though. One other unrelated thing that causes issues during installation is the package structure: 

```
- package.json
- tsconfig.json
- ...
- services/
  - package.json
  - tsconfig.json
  - ...
```

The `/services/` directory, where I want to run and install Typia, is set up as a [workspace](https://docs.npmjs.com/cli/v7/using-npm/workspaces) in npm. This means that I will not have a `services/node_modules` folder. This caused some issues during installation that I managed to circumvent by symlinking the root node modules folder to the one in the services dir. It's possible that this could have been avoided by using the `--project` flag. 

I will try to experiment some more and see if I can fix this.

**Comment by FreeNFTj** [comment]
+1 

Anything come of this? Fix? I think this would be a great SST addition and greatly positioned for adoption since lambdas require speed

**Comment by bjornlll** [comment]
Didn't manage to get it to a working state, unfortunately. Also briefly asked around in the SST community. Went for the second best, but much slower option: Zod.

**Someone else would have to take a stab at this!**

**Comment by samchon** [comment]
Will support through #509

**Comment by bjornlll** [comment]
@samchon many thanks for fixing this!

One other issue I had, mentioned above, was related to NPM workspaces. Did you have time to take a look at that, too? It was simple to work around - just thinking in case anyone else stumbles upon the same thing.
