### ISSUE TITLE
Feature Request: Validation errors should include the violated constraint

### ISSUE THREAD

**Issue by blakerobertson** [samchon/typia#455]
Typia lets me specify constraints like `maxLength` or `pattern`, but then when an object violates one of those constraints, the resulting error doesn't tell me which one was actually the problem. I need it to contain enough information to help the user fix whatever the issue is.

**Comment by samchon** [comment]
Would make detailed error message for special validation logics from comment tags.

However, it will be implemented after protocol buffer features.

**Comment by ghost** [comment]
+1

This is certainly needed for reporting string constraints specifically (when the client actually passed a string).

```typescript
interface TokenInput {
  /**
   * @length 64
   * @pattern ^[0-9a-f]+$
   */
  token: string;
};
```

Current errors:
```json
[
  {
    "path": "$input.token",
    "expected": "string",
    "value": "something"
  }
]
```

Desired:
```json
[
  {
    "path": "$input.token",
    "expected": "string",
    "length": 64,
    "pattern": "^[0-9a-f]+$",
    "value": "something"
  }
]
```

**Comment by samchon** [comment]
@black7375 @enote-kane Upgrade to v3.7, then be fixed.
