### ISSUE TITLE
Unions with tuples and arrays are not working properly

### ISSUE THREAD

**Issue by Drafter500** [samchon/typia#456]
### Summary
When having a union type with one of the compounds being a tuple and another an array, it only checks against a tuple and ignores an array.

  - **SDK Version**: 3.4.18
  - **Expected behavior**: 
  When a tuple fails to match the value it should check against an array
  - **Actual behavior**: 
 It never checks an array and returns an error.

### Code occurring the bug
```typescript
import typia from 'typia';

type MyType = [string, string] | number[];
const result = validate<MyType>([5]); 
```

And `result` is then:
```
{
    success: false,
    errors: [ { path: '$input', expected: '[string, string]', value: [Array] } ],
    data: undefined
}
```

**Comment by samchon** [comment]
@Drafter500, update to `v3.4.20`, then it would be fixed.
