### ISSUE TITLE
Feature request: Enable automatic conversion to builtin types when parsing

### ISSUE THREAD

**Issue by ruler501** [samchon/typia#467]
## Feature Request
I'd like to be able to parse JSON into types containing date and url typed properties. Potentially a way to assert/validate that automatically converts if possible would also be nice.

My concrete use case is I have a type
```typescript
type LastUpdated = Partial<Record<JobType, Date>>
```
That tracks the last updated time for pulling the results of a batch job and I want to be able to save and load from that type directly, but currently when loading I need to manually convert like this which just introduces a bunch of extra code (and for other types where this behavior is more nested becomes much harder to maintain.
```typescript
  assert<LastUpdated>(
    Object.fromEntries(
      Object.entries(JSON.parse(contents.toString()) as Record<JobType, string>).map(([key, value]) => [
        key,
        new Date(value),
      ]),
    ),
  );
```

It looks like https://github.com/samchon/typia/issues/372 already added some special casing for these types so maybe this support could build on top of that?

**Comment by samchon** [comment]
Sorry, no plan to support.
