### ISSUE TITLE
Use Typia in an Angular project ?

### ISSUE THREAD

**Issue by thibautLedz** [samchon/typia#471]
Hello,

I'm trying to replace class-validator in my lib.
Anyone already tried to use typia in an Angular app/library ? (Angular 14-15).
How to configure Typia transformer ?

**Comment by samchon** [comment]
As I've no experience about the Angulr, I can't be helpful. Anyone who knows how to?

@thiboot By googling, I found an issue about the transform API plugin supporting. Is it helpful?

  - https://github.com/angular/angular/issues/22434
  - https://medium.com/joolsoftware/custom-typescript-transformers-with-angular-cli-7f4150797e05

**Comment by thibautLedz** [comment]
Thank you for your answer @samchon i'll try this way i found also a plugin for webpack angular builders :
https://github.com/just-jeb/angular-builders/tree/master/packages/custom-webpack

**Comment by samchon** [comment]
Will support through #509
