### ISSUE TITLE
How I can setup typia with vite and avoid typecheking?

### ISSUE THREAD

**Issue by search654321** [samchon/typia#472]
I'm setting up typia with vite and when I run the recommended config I see TypeScript warnings on my console like this:

```
9:27:56 AM [vite] warning: @rollup/plugin-typescript TS2722: Cannot invoke an object which is possibly 'undefined'.

  46             <IconButton icon="Close" onClick={() => onClose()} size={24} />
```

I have an external command to check types and I want to avoid doing type checking on the bundler, for compilation speed reasons and to avoid cluttering the console.

How I can turn off type checking when running vite but keep typia working?

This is my current config for the `@rollup/plugin-typescript`

```ts
typescript({
  typescript: ttsc,
  cacheDir: '.tscache',
})
```

**Comment by samchon** [comment]
Have any idea not to use validator function only when release mode?

**Comment by search654321** [comment]
Right now I'm just using assert. I'm not sure how typia works but the only thing I want from this extension is to do runtime validation of types, but avoid running type checking. I'm not sure if that is a limitation of rollup plugin, but at least turning off warnings will be fine...

I use assert both in development and release mode

**Comment by samchon** [comment]
I think the error message has been occured because the `onClose` function can be undefined.

It seems not problem of `typia`.

**Comment by search654321** [comment]
Oh, the error message is not `typia`, what I mean is that I don't wan't to see typescript errors when running the vite server

**Comment by samchon** [comment]
You mean not to compile TypeScript type, but transpile only? Then using typia is not possible because it requires TypeScript type info.

In that case, I recommend you to compile typia using code independently and import the compiled code from main vite developed project.

**Comment by search654321** [comment]
But could be possible to silence typescript errors in the vite console? With webpack that is possible

**Comment by samchon** [comment]
Not possible in vite. What about solving the TypeScript errors?

**Comment by search654321** [comment]
I'm working in a legacy project and fixing them all will take a year

**Comment by samchon** [comment]
Then should compile from independently and import it
