### ISSUE TITLE
Support manual compilation of validators

### ISSUE THREAD

**Issue by TheYarin** [samchon/typia#486]
@samchon I wanna start off by saying you have done an amazing job with this project, you are the hero the TS world needed.

## Feature Request

  - The problem: Typia requires build config changes of the entire project in order to run

  - An overview of the suggested solution: Add a CLI option that compiles the different validation functions given a specific type (TS file), removing the build dependency on ttsc.

  - Examples of how the suggestion would work in various places:
  ```shell
  typia compile src/ExampleType.ts # Creates src/ExampleType.validator.ts
  ```
  And then, in `src/main.ts`:
  ```typescript
  import {isExampleType} from './ExampleType.validator.ts';

  const unvalidatedInput = {...};

  if (isExampleType(unvalidatedInput)) {
      // ...
  }
  ```

**Comment by samchon** [comment]
There was someone who suggested same idea and told me that implement these features by himself. However, he has gone without any news. It seems time to support CLI options by myself.

**Comment by TheYarin** [comment]
Not to rush you or anything but do you think I should hold my breath for this one? Do you think you'll manage to implement this in the next few days, or should I settle for an existing alternative for now?

**Comment by samchon** [comment]
Not possible in few days. 

My next purpose is to implementing protocol buffer functions, and it may be completed in March.

Therefore, this feature may be implemented in April.

**Comment by TheYarin** [comment]
Ok, thank you! I really appreciate it!

**Comment by samchon** [comment]
If possible, what about suggesting CLI design?

How interface do you want?

**Comment by samchon** [comment]
@TheYarin The reason why you wanna manual compilation is for frontend development?

**Comment by TheYarin** [comment]
> @TheYarin The reason why you wanna manual compilation is for frontend development?

No, I wanted to use it for server-side validation, but was deterred by the use of a custom typescript package, especially when it's not well-known enough. It makes auditing harder. Also, it just feels a bit excessive to have to make such configuration changes for something like validation.
I also figured a manual compilation option might make it easier for library developers to use Typia.

**Comment by samchon** [comment]
If you're developing backend server, I planned to introduce [nestia](https://github.com/samchon/nestia), but your story is clearly different.

**Comment by TheYarin** [comment]
> If possible, what about suggesting CLI design?
> 
> How interface do you want?

- I would want an interface that allows me to specify the files I want validation for. Personally being able to specify a list of file paths is enough for me, but folder/extension/regex support might be useful for others. I guess a config file will be more appropriate than a CLI argument.
- There's the issue of default exports vs specified exports vs all exported types.
- Maybe allow me to choose the validation functions I need, to reduce the amount of code generated (is/assert/equals etc.)
- I would probably end up running it manually whenever I change the types I want to validate, so it should be easily callable as a `package.json` script.

**Comment by TheYarin** [comment]
> If you're developing backend server, I planned to introduce [nestia](https://github.com/samchon/nestia), but your story is clearly different.

It might be relevant, I'll look into it. Thank you!

**Comment by samchon** [comment]
Will support through https://github.com/samchon/typia/issues/509
