### ISSUE TITLE
Typia is not working with Mongoose/Typegoose

### ISSUE THREAD

**Issue by ismailkarsli** [samchon/typia#488]
### Summary
Typia giving `Error: Error on typia.metadata(): typia does not allow "String" class type. Use "string" type instead.` error when tried to use it with both Mongoose and Typegoose.

  - **SDK Version**: 3.4.27

Typegoose is a Typescript wrapper for Mongoose. So it's using Mongoose under the hood.
In Mongoose, class types are used in models. For example: `new mongoose.Schema({ name: String })`.
So it's impossible to create mongoose models with lower case.

### Code occuring the bug
```typescript
// Mongoose
assert<typeof KittenModel>(document);

// Typegoose
assert<DocumentType<KittenClass>>(document);

// Note: it doesn't work with is, validate variations either.
```

### Demonstration
[https://stackblitz.com/edit/node-at1jm6?file=package.json&view=editor](https://stackblitz.com/edit/node-at1jm6?file=package.json&view=editor)

**Comment by samchon** [comment]
As you know, validation logic of `String` and `string` are different like below:

 - `typeof str === "string"`
 - `str instanceof String`

In such reason, I've blocked primitive class types, but you're saying that it is required for mongoose, right?

  - `Boolean`
  - `Number`
  - `BigInt`
  - `String`

When `typia` allows such class types, what about validating like below? 

```typescript
typia.is<String> = (str: String) =>typeof str === "string" || str instanceof String
```

How do you think about it? If you have a better idea, then please tell me.

**Comment by ismailkarsli** [comment]
Yeah that could do. But isn't `typeof String('test')` already `string`? Like do people inherit String class? I'm not sure about the side effects of this.

**Comment by samchon** [comment]
I think mongoose is generating `String` class through new `String()` statement.

I will test it tomorrow and fix soon.

**Comment by ismailkarsli** [comment]
Alright then. BTW thank you for creating this beautiful, silver bullet library ♥

**Comment by samchon** [comment]
You're welcome. Update to `v3.4.28`, then atomic class type like `String` would be supported.
