### ISSUE TITLE
feat/enhance: support generate rule in random() function

### ISSUE THREAD

**Issue by ltnscp9028** [samchon/typia#497]
Add a generate rule in random function or custom generator. 

```ts
export function random<T>(option: GenerateOption<T>): T;
```

for example, using this User interface.
```ts
interface User {
  id: number;
  name: string;
  email: string;
}
```
then,  ```random()``` takes a generator option as a parameter.

```ts
random<User>(option: {
  id: 'increase',
  name: 'fullName',
  email: 'email'
})
```
this option return following result
```ts
{
  id: 1,
  name: '한상진',
  email: 'ltnscp9028@gmail.com'
}
```

This option allows you to use random functions that have higher expressive power.

**Comment by samchon** [comment]
What about designing comment tags? It seems too specific
