### ISSUE TITLE
svelte integration

### ISSUE THREAD

**Issue by dirk-bester** [samchon/typia#500]
I am trying to use typia in a svelte project. Unfortunately I am new to modern js frameworks VSCode, everything. This makes it hard to know the right thing to do.

npm create svelte@latest
npm install sveltestrap
npm install --save-dev eslint-config-prettier eslint-plugin-prettier
npx typia setup --compiler ttypescript --manager npm --project ./tsconfig.json
npm install

Follow
https://github.com/samchon/typia/wiki/Setup#vite
but I am stuck on the vite instructions for vite.config.ts
**Cannot find module '@rollup/plugin-typescript' or its corresponding type declarations.ts(2307)**

https://github.com/dirk-bester/bare
This project is my experiment for this.

svelte itself is compile based so I am very unclear on how typia should properly fit in.
typescript support is already in there but not through rollup?

Mmm, going through old issues https://github.com/samchon/typia/issues/236 svelte needs to support typescript plugins. I will go hassle them on their side.

I feel like the issue is with svelte-preprocess so https://github.com/sveltejs/svelte-preprocess/issues/576

Or maybe we just need a preprocessor and or wrapper? https://sveltesociety.dev/tools#preprocessors

**Comment by samchon** [comment]
Looking at your repo, I can't find `@rollup/plugin-typescript` in `devDependencies` of `package.json` file.

At 1st, install it like below:

```bash
npm install --save-dev @rollup/plugin-typescript
```

Also, I don't know svelte well, but if svelte does not use TypeScript regular compiler, there's no way.

About that, can you help me about this issue? @hmmhmmhm

**Comment by hmmhmmhm** [comment]
Most of the typescript processing within svelte relies on svelte-preprocess, so it looks like you should put your code in the typescript referenced by "svelte-preprocess". I'm not sure if this is possible though.

**Comment by samchon** [comment]
https://github.com/sveltejs/svelte-preprocess/blob/main/docs/migration-guide.md#type-checking-components

Not possible, no way.

It would better to make independent code file generator instead. 

I'll research it how.

**Comment by samchon** [comment]
Will support through #509
