### ISSUE TITLE
Can't import lib/transform from ESM

### ISSUE THREAD

**Issue by notpeelz** [samchon/typia#503]
## Bug description

When importing `typia/lib/transform` from an ECMAScript module, it fails with this error:
```
Error: Qualified path resolution failed: we looked for the following paths, but none could be accessed.
```

This could be fixed by [defining proper exports](https://nodejs.org/api/packages.html#package-entry-points) to supports both ESM and CJS, e.g:
```diff
diff source/package.json patched/package.json
5,6c5,9
<   "main": "lib/index.js",
<   "typings": "lib/index.d.ts",
---
>   "typings": "./lib/index.d.ts",
>   "exports": {
>     ".": "./lib/index.js",
>     "./lib/transform": "./lib/transform.js"
>   },
```

## Reproduction

I setup a reproduction repo here: https://github.com/notpeelz/bug-repro-typia-esm-resolve
The `master` branch contains the current (broken) version.
The `patched` branch contains a patched version of typia that fixes the resolution problem, but only partially (see comment at the bottom).

You can test it like so:

```
$ npm i -g yarn
$ git clone https://github.com/notpeelz/bug-repro-typia-esm-resolve
$ cd bug-repro-typia-esm-resolve

$ yarn run test1
works
$ yarn run test2
*resolution error*

$ git checkout patched
$ yarn run test1
works
$ yarn run test2
typia/lib/transform is not a function: { default: Function }
```

NOTE: I believe the reason we see `{ default: Function }` is because of [CJS interop behavior](https://nodejs.org/api/esm.html#interoperability-with-commonjs). However, I'm not quite sure how to fix that problem.

**Comment by samchon** [comment]
Use `typia/lib/transform.js` instead.

**Comment by notpeelz** [comment]
That still leaves the problem where the module is exported as faux-ESM.
I would have to import it like this: `import { default as transform } from "typia/lib/transform.js";` 
Is there a way around that?

**Comment by samchon** [comment]
Can you give me a sample project?

**Comment by notpeelz** [comment]
https://github.com/notpeelz/bug-repro-typia-esm-resolve

Check out the `patched` branch and run `yarn run test2`

**Comment by samchon** [comment]
Ah, you are trying to import transform function directly, not for using from ttsc.

Is it works? `import { transform }`

If not works, you should start from `FileTransformer` class.

**Comment by notpeelz** [comment]
I'm using the transform with Webpack and `ts-loader`, just like shown [in your wiki](https://github.com/samchon/typia/wiki/Setup#webpack). The only difference is my webpack config is written in ESM (`.mjs`).

As for the other issue, importing `transform` using `import { default as transform} from "typia/lib/transform.js";` might work with the default node module resolution, but it's not spec-compliant and breaks other module resolution implementations such as Yarn PnP.

**Comment by samchon** [comment]
Then two options are left:

  1. `typia` supports duplicated transform file not using `default` statement
  2. change webpack file as `cjs`

If you want the first option, I'll update it after home (maybe 8 hours later).

**Comment by notpeelz** [comment]
The first option sounds great, thanks! :+1:

**Comment by samchon** [comment]
Now it works. Upgrade to `3.5.2`.

```javascript
import { transform } from "typia/lib/transform.js";
```

**Comment by notpeelz** [comment]
That fixes the `import { default as transform }` problem, but it still doesn't play well with Yarn PnP:

```
$ yarn build
/path/to/project/.pnp.cjs:14473
  return Object.defineProperties(new Error(message), {
                                 ^

Error: Qualified path resolution failed: we looked for the following paths, but none could be accessed.

Source path: /path/to/project/.yarn/__virtual__/typia-virtual-961dae8111/0/cache/typia-npm-3.5.2-d9b0badeaf-e1e00b27b6.zip/node_modules/typia/lib/transform.ts
Not found: /path/to/project/.yarn/__virtual__/typia-virtual-961dae8111/0/cache/typia-npm-3.5.2-d9b0badeaf-e1e00b27b6.zip/node_modules/typia/lib/transform.ts

    at makeError (/path/to/project/.pnp.cjs:14473:34)
    at resolveUnqualified (/path/to/project/.pnp.cjs:16288:13)
    at resolveRequest (/path/to/project/.pnp.cjs:16329:14)
    at Object.resolveRequest (/path/to/project/.pnp.cjs:16385:26)
    at resolve$1 (file:///path/to/project/.pnp.loader.mjs:1991:25)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at u (file:///path/to/project/.yarn/cache/@esbuild-kit-esm-loader-npm-2.5.5-2cb7377e71-9d4a03ffc9.zip/node_modules/@esbuild-kit/esm-loader/dist/index.js:1:2406)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async u (file:///path/to/project/.yarn/cache/@esbuild-kit-esm-loader-npm-2.5.5-2cb7377e71-9d4a03ffc9.zip/node_modules/@esbuild-kit/esm-loader/dist/index.js:1:2269)
    at async nextResolve (node:internal/modules/esm/loader:163:22)

Node.js v19.6.0
```

You can test it yourself by creating a Yarn PnP project: `yarn init -2 -p`
You would need to declare the exported modules like this:
```diff
diff source/package.json patched/package.json
5,6c5,9
<   "main": "lib/index.js",
<   "typings": "lib/index.d.ts",
---
>   "typings": "./lib/index.d.ts",
>   "exports": {
>     ".": "./lib/index.js",
>     "./lib/transform": "./lib/transform.js"
>   },
```

**Comment by ehaynes99** [comment]
> but it still doesn't play well with Yarn PnP:

Sooner or later, the number of "yarn 2+ doesn't work" issues are going to have to start rolling back uphill.
