### ISSUE TITLE
Making typia ZodEsque

### ISSUE THREAD

**Issue by gotjoshua** [samchon/typia#508]
## Feature Request
It would be great if typia could be considered [ZodEsque](https://github.com/trpc/trpc/blob/63daaab739e0eb2d330a977c50d823a66dd2038f/packages/server/src/core/internals/getParseFn.ts#L19) 
 By trpc and elysia

i would like to experiment with using typia instead of zod and typebox and curious if you plan to offer parse functions similar to zod.

**Comment by samchon** [comment]
Possible to use `typia` in `tRPC`.

Have not tested `elysia`, but it seems possible. Will you try it?

```typescript
import { initTRPC } from "@trpc/server";
import { v4 } from "uuid";
import typia from "typia";

interface IBbsArticle {
    id: string;
    writer: IBbsArticle.IWriter;
    title: string;
    body: string;
    created_at: string;
}
namespace IBbsArticle {
    export interface IStore {
        writer: IWriter;
        title: string;
        body: string;
        /**
         * @minLength 4
         * @maxLength 16
         * @pattern ^[a-zA-Z0-9]+$
         */
        password: string;
    }
    export interface IWriter {
        /**
         * @format uuid
         */
        external_service_id?: string;
        /**
         * @format email
         */
        email: string;
    }
}

const t = initTRPC.create();

export const appRouter = t.router({
    store: t.procedure
        .input(typia.createAssert<IBbsArticle.IStore>())
        .output(typia.createAssert<IBbsArticle>())
        .query(({ input }) => {
            return {
                id: v4(),
                writer: input.writer,
                title: input.title,
                body: input.body,
                created_at: new Date().toString(),
            };
        })
});
export type AppRouter = typeof appRouter;
```

**Comment by gotjoshua** [comment]
> ```ts
> input(typia.createAssert<IBbsArticle.IStore>())
> ```

Ahhhh using create assert... Nice, yeah I'll try that over the weekend!
Thanks 🙏


Ah but after reviewing [your](https://github.com/samchon/typia/blob/master/src/module.ts#L1498) code , i wonder if create assert parse may be more appropriate...

**Comment by samchon** [comment]
I just followed guide of tRPC. It delivers parsed object into the input function.

**Comment by gotjoshua** [comment]
So i didn't try with pure trpc, because my goal is to use the trpc plugin for elysia... Which is optimized for bun, and i didn't manage to get the server running with typia involved. I could run the ttsc command but the run commands didn't work. [Repo here](https://gitlab.com/onezoomin/ztax/bun-elysia-quickstart/-/tree/typia/src)

I expect this is because bun does not employee the transformer properly.

More investigation needed.

**Comment by samchon** [comment]
Will support through https://github.com/samchon/typia/issues/509
