### ISSUE TITLE
adding ObjectModel, superstruct and yup to the comparisons

### ISSUE THREAD

**Issue by gotjoshua** [samchon/typia#521]
## Feature Request
this is for the [docs comparison chart](https://github.com/samchon/typia/wiki/Runtime-Validators#powerful-validator) and for the speed benchmarks.
Will you consider adding more libraries?

eg:
- [Objectmodel](https://objectmodel.js.org/)

- [Superstruct](https://docs.superstructjs.org/guides/06-using-typescript)

- [Yup](https://github.com/jquense/yup#typescript-integration)

**Comment by samchon** [comment]
Welcome PR

**Comment by gotjoshua** [comment]
> Welcome PR

do PRs work for the wiki? (for the comparison chart)

which tool do you use for editing that big markdown table anyway?
(i can also just post drafts here for you to update the wiki)

**Comment by samchon** [comment]
Just run `npm run benchmark` command, then md file and svg charts would be automatically generated.
