### ISSUE TITLE
When should I use a factory function?

### ISSUE THREAD

**Issue by TheYarin** [samchon/typia#522]
The docs mention the factory functions API, but not when (or why) they should be used.
Looking at issue #247, it looks like factory functions are intended to solve some transform issues that happen when passing around the normal functions.
It's worth updating the docs (both the README and the wiki) around these functions, because currently typia's API is pretty confusing, two ways to reach the same result without an obvious difference between them.

**Comment by samchon** [comment]
Will update guide documents on https://typia.io

Thanks for suggestion.
