### ISSUE TITLE
comment of "createAssertPrune" is wrong.

### ISSUE THREAD

**Issue by rojiwon0325** [samchon/typia#530]
<img width="597" alt="스크린샷 2023-02-27 오후 4 28 21" src="https://user-images.githubusercontent.com/68629004/221500651-2d3aaebd-1326-4cb7-a8e1-0c85be57683b.png">

i think, this comment is wrong. "isPrune" -> "assertPrune"

**Comment by samchon** [comment]
You're right. Will you send a PR?

**Comment by rojiwon0325** [comment]
ok, i will.
