### ISSUE TITLE
JSDoc tags for non object types

### ISSUE THREAD

**Issue by jfrconley** [samchon/typia#535]
## Feature Request
I am trying to represent reusable simple types within my schemas.
However, it seems that jsdoc tags are only supported for objects and properties.

Example:
```
/**
 * Amazing string
 * @pattern ^[a-z]+$
 * @minLength 5
 */
type TestStringType = string;
```

Supporting this would allow creating a reusable validated string type that I could use in multiple schemas.

Adding a nominal type brand would bring additional type safety 
```
/**
 * Amazing string
 * @pattern ^[a-z]+$
 * @minLength 5
 */
type NominalyTypedString = Nominal<string, "NominalyTypedString">;
```

**Comment by rojiwon0325** [comment]
I'm waiting for it!!

**Comment by samchon** [comment]
This is difficult issue for me gave up for a long time ago.

I'll try it again, but cannot sure success.
