### ISSUE TITLE
comment tag @format uuid is only allow uuid v4. is right?

### ISSUE THREAD

**Issue by rojiwon123** [samchon/typia#540]
typia validate string property whether is uuid or not. by using comment tag "@format uuid".

now, typia only pass uuid v4, uuid v1 is invalid.

Is this working correctly?

**Comment by industriously** [comment]
TypedParam에서 사용한 UUID_PATTERN

**Comment by rojiwon123** [comment]
TypedParam에서 사용한 UUID_PATTERN.test(string)은 v1, v4 모두를 통과하지만,
@format uuid 를 사용한 검증은 v4만 통과하였습니다. 이러한 부분이 의도된 것이라면 왜 그러한지도 궁금합니다!

**Comment by samchon** [comment]
Just by mistake. Will fix soon

**Comment by samchon** [comment]
Upgrade to `v3.6.4`, then be fixed.
