### ISSUE TITLE
`createValidateEquals` module declare seems to be missing a generic T.

### ISSUE THREAD

**Issue by dodohankim** [samchon/typia#545]
## Bug Report

typia@3.6.5

https://github.com/samchon/typia/wiki/Runtime-Validators#factory-functions
The documentation is well marked.
`export function createValidateEquals<T>(): (input: unknown) => IValidation<T>;`

https://github.com/samchon/typia/blob/master/src/module.ts#L1441
The module declare seems to be missing a generic T.

`export declare function createValidateEquals<T>(): (input: unknown) => IValidation;` 

## Should be
`export declare function createValidateEquals<T>(): (input: unknown) => IValidation<T>;`

**Comment by samchon** [comment]
Update v3.6.6, then be fixed.
