### ISSUE TITLE
Why does using the "generate" feature installs dependencies to my `package.json`

### ISSUE THREAD

**Issue by TheYarin** [samchon/typia#553]
## Question

After running "generate" I noticed the following dependencies were added to my devDependencies:
```
"commander": "^10.0.0",
"inquirer": "^8.2.5",
```

Is that really necessary? Can this be avoided?

**Comment by samchon** [comment]
It requires to asking prompt.

**Comment by EricDunaway** [comment]
Can typia not rely on those packages itself?

**Comment by samchon** [comment]
@EricDunaway When running `npx typia setup` command without install, it can't import dependencies by itself.
