### ISSUE TITLE
Support Typescript 5

### ISSUE THREAD

**Issue by maicol07** [samchon/typia#556]
Hi,
can you add compatibility with Typescript 5? Currently, I get a peer dependency warning when installing it:
```
.
└─┬ typia 3.6.8
  └── ✕ unmet peer typescript@">= 4.5.2 && < 5.0.0": found 5.0.2
```

I haven't done deep testing yet, but it compiles with `assertJson`.
Thanks

**Comment by samchon** [comment]
Not working on TS5, it is the reason why blocking

**Comment by sunrabbit123** [comment]
What modifications are necessary to support TS5, and what tests need to be passed?

**Comment by samchon** [comment]
@sunrabbit123 Waiting for updates of `ts-patch` and `ttypescript`.

**Comment by sunrabbit123** [comment]
@maicol07  Now, if you use `yarn add ttsc` instead of `yarn add ttypescript`, you can use `typia` nicely with the `ttsc` command.

**Comment by samchon** [comment]
Okay, will unlock the TS version limit soon (waiting for ts-patch because of nestia)

**Comment by samchon** [comment]
Supported by `ts-patch`
