### ISSUE TITLE
`typia generate` create infinite nested folder

### ISSUE THREAD

**Issue by dodohankim** [samchon/typia#557]
## Bug Report

When using `npx typia generate --input ./src/typia --output ./src/typia/dist`, create an infinitely nested folder.

> typia^3.6.8
ttypescript^1.5.15
typescript^4.9.5

## Settings

```json
{
  "compilerOptions": {
    "target": "ES5",                         
    "module": "CommonJS",                    
    "rootDir": "./src",                      
    "moduleResolution": "node",              
    "outDir": "./dist",                      
    "esModuleInterop": true,                 
    "forceConsistentCasingInFileNames": true,
    "strict": true,                                
    "skipLibCheck": true,
    "plugins": [
      {
        "transform": "typia/lib/transform"
      }
    ]
  },
}

```
### code

``` ts
import typia from "typia";

export const is = typia.createIs<boolean>();
```

## screenshot

![typia_error_1](https://user-images.githubusercontent.com/50390565/225828302-ae07d1f0-5068-4974-9a4d-1b68af0abd6e.png)

![typia_error_2](https://user-images.githubusercontent.com/50390565/225828258-6eeac40b-7f05-4b45-bdc0-4d8304040ff2.png)

**Comment by samchon** [comment]
Upgrade to `typia@3.6.10`, then would be fixed.
