### ISSUE TITLE
Use seeded random gen for random()

### ISSUE THREAD

**Issue by gittyeric** [samchon/typia#561]
## Feature Request

Thanks for this amazing lib!  I'm currently using random() to generate random mocks in unit tests, but things would go a whole lot more smoothly if the random() functions allowed for a seeded number generator for better test consistency.  By default it could seed with current Date to maintain current "random" behavior but could also be set to a constant via config.

I'd be happy to open a PR for this if I can get a :heavy_check_mark: that you'd approve it since it looks like a simple change.  If you have a preference for the seeded random lib and how to pipe the config into the component it'd be much appreciated!

**Comment by samchon** [comment]
Okay, I will wait forr your PR

**Comment by gittyeric** [comment]
Getting this off the Issues list until I circle back with a PR, thanks for the quick response!
