### ISSUE TITLE
Feature Request: Config File and Watch

### ISSUE THREAD

**Issue by EricDunaway** [samchon/typia#562]
# Feature Request: Config File and Watch for generate command

I prefer to use the typia generate feature over patching typescript especially now the ts-patch does not support typescript v5. Could typia support a config file and watch functionality for generate?

  - I am looking to have one place to configure multiple input and output directories for a mono repo setup and to have the output regenerated when files in the input directories change.
  

  ## Example Use: 

### NestJS Project:
  In a nest mono repo project, multiple libraries may exist, and a project would want separate input and output directories for each library and the ability to regenerate the generated files when files in the input directories change.
  ```
  nest project/
├─ apps/
│  ├─ app-1/
│  ├─ app-2/
├─ libs/
│  ├─ lib-1/
│  │  ├─ src/
│  │  │  ├─ types/
│  │  │  │  ├─ generated-typia/
│  │  │  │  │  ├─ <generated files>
│  │  │  │  ├─ src-typia/
│  │  │  │  │  ├─ type-2.ts
│  │  │  │  ├─ index.ts
│  ├─ lib-2/
│  │  ├─ src/
│  │  │  ├─ dtos/
│  │  │  │  ├─ generated-typia/
│  │  │  │  │  ├─ <generated files>
│  │  │  │  ├─ src-typia/
│  │  │  │  │  ├─ type-1.ts
│  │  │  │  ├─ index.ts
```

**Comment by samchon** [comment]
Not possible to providing watch mode, but configuration file is possible.

Can you design an interface type of the configuration file what you want?

**Comment by samchon** [comment]
By the way, `ts-patch` seems to support to v5 in near time:

https://github.com/nonara/ts-patch/issues/93#issuecomment-1488595872

**Comment by samchon** [comment]
Close due to ts-patch started supporting TS 5
