### ISSUE TITLE
Typia generate incorrectly changes relative import path

### ISSUE THREAD

**Issue by Lechros** [samchon/typia#573]
## Bug Report
Typia generate incorrectly changes relative import path

### Summary
  - **SDK Version**: typia 3.7.1
 
Relative import path is converted to `"interface"` when it should be `"./interface"`.

### Code occuring the bug
```typescript
import typia from "typia";
import { SomeInterface } from "../interface";
```
and
```bash
pnpm typia generate   --input home/src/typia   --output home/src
```
becomes
```typescript
import typia from "typia";
import { SomeInterface } from "interface";
```

**Comment by samchon** [comment]
It was a bug only occured in Macbook.

Tried to fix it, but no way.

Therefore, I will change setup way like below:

```bash
npm install --save typia # must install first
npx typia setup ~
npx typia generate ~
```

**Comment by samchon** [comment]
Upgrade to `v3.7.4`, then would be fixed.
