### ISSUE TITLE
"RangeError: Maximum call stack size exceeded" for intersection of recursive type

### ISSUE THREAD

**Issue by yang** [samchon/typia#599]
**SDK Version**: 2.1.0-dev.20220505

Get `RangeError: Maximum call stack size exceeded` with:

```typescript
/** @format */

import { createIs } from "typia";

type Element =
  /** Shorthand for Text */
  | string
  | {
      component: string;
      props: Record<string, Element> & { children?: Element[] };
    };

export const check = createIs<Element>();
```

**Comment by samchon** [comment]
Your type is nonsensible, therefore TS compiler API cannot recognize it.

It actually, the `children` property does not work.

Change to be exact type like below, then it works:

```typescript
import typia from "typia";

type Element =
    | string
    | {
          component: string;
          props: {
              [P in string]?: P extends "children" ? Element[] : Element;
          };
      };

export const check = typia.createIs<Element>();
console.log(check.toString());
```

**Comment by samchon** [comment]
Even above code does not work. TS compiler API failed to construct exact `ts.Type` instance.

Need to study it.

**Comment by samchon** [comment]
<img width="400" alt="image" src="https://user-images.githubusercontent.com/13158709/234009186-76ece6e6-6b1a-4604-a9ba-03f76aee181d.png">

> ```bash
> Type 'string[]' is not assignable to type 'IElement | undefined'.ts(2322)
>
> 599.ts(5, 18): The expected type comes from property 'children' which is declared here on type '{ [x: string]: IElement | undefined; }'
> ```

Tested your type with sensible expression, but TypeScript can't identify the `children` property.

I can't sure whether this is a bug that failed to identify the `children` property, or intended spec to prohibiting multiple dynamic property type definitions. Looking at error message from TypeScript compiler, it seems like a spec, but I need to ask it to the TypeScript compiler developers by writing an issue on the TypeScript repo.

Thanks for report @yang.

------------------------------------------

You can avoid the maximum call stack error by changing sensible type like above image, but generated type checking code may not what you want. As `typia` utilizes TS compiler API, and the TS compiler API can't identify multiple dynamic property type definitions, the `children` array type be ignored.

```javascript
input => {
    const $join = typia_1.default.createIs.join;
    const $io0 = input => "string" === typeof input.component && ("object" === typeof input.props && null !== input.props && false === Array.isArray(input.props) && $io1(input.props));
    const $io1 = input => Object.keys(input).every(key => {
        const value = input[key];
        if (undefined === value)
            return true;
        if (RegExp(/(.*)/).test(key))
            return null !== value && (undefined === value || "string" === typeof value || "object" === typeof value && null !== value && $io0(value));
        return true;
    });
    return null !== input && undefined !== input && ("string" === typeof input || "object" === typeof input && null !== input && $io0(input));
}
```

**Comment by samchon** [comment]
Asked whether **unable to using multiple dynamic property types** is bug or not.

https://github.com/microsoft/TypeScript/issues/53982

**Comment by samchon** [comment]
@yang Below issue is what you want, but 7 years have passed, therefore seems hard to be accomplished. 

https://github.com/microsoft/TypeScript/issues/17867

**Comment by rojiwon123** [comment]
@samchon 같은 증상의 버그라서 새로운 이슈가 아닌 코맨트로 남기겠습니다!

저도 같은 증상을 겪지만 원인을 알 수 없고, 위와 같은 원인은 아닌 것 같습니다.
제가 겪는 증상은 현재 상태에서 nestia 관련 라이브러리나 typia를 업데이트 한 후에 발생합니다.
아래 링크는 정상적으로 swagger가 빌드되는 버전입니다. 하지만 해당 버전에서 nestia 계열 라이브러리나 typia를 최신 버전으로 업데이트하면 maximum callstack error가 발생하면서 swagger가 빌드되지 않습니다.

I am experiencing similar symptoms, but I don't think the cause is the same as mentioned above. The symptoms I am experiencing occur after updating the Nestia-related library or Typia in the current version. The link below shows a normal build of Swagger. However, if I update Nestia-related libraries or Typia to the latest version in the version, a maximum call stack error occurs, and Swagger cannot be built

https://github.com/zipzoong/zipzoong-backend/tree/user_system

command: npm run swagger

**Comment by samchon** [comment]
@industriously Show me detailed error message + DTO occuring the bug

**Comment by samchon** [comment]
@industriously Found the bug reason and fixed it.

Upgrade to `typia@3.8.1`, then it would be fixed.

**Comment by rojiwon123** [comment]
이유를 알 수 없지만 동일한 코드, package 버전, node_modules 상태에서 갑자기 정상적으로 동작하는 것을 확인했습니다.

혼란을 드려 죄송합니다.ㅠ
추측해본다면 라이브러리가 아닌 제 nodejs환경에 일시적인 문제가 있던게 아닐까 생각합니다.

다시한번 죄송합니다!!

2023년 4월 27일 (목) 오전 1:00, Jeongho Nam ***@***.***>님이 작성:
