### ISSUE TITLE
Empty array in object parameter invalid

### ISSUE THREAD

**Issue by JakubSmahovsky** [samchon/typia#603]
### Summary

  - **SDK Version**: ??? don't know, let me know if it's needed
  - **Expected behavior**: see code
  - **Actual behavior**: see code

### Code occurring the bug
```typescript
import { is } from "typia";
is<{ foo: [] }>({ foo: [] }) // false | expect true
```

**Comment by samchon** [comment]
```typescript
import typia from "typia";

interface Foo {
    foo: [];
}

console.log(typia.createIs<Foo>().toString());
console.log(typia.createIs<{ foo: [] }>().toString());
```

> ```bash
> input => {
>     const $io0 = input => Array.isArray(input.foo) && input.foo.length === 0;
>     return "object" === typeof input && null !== input && $io0(input);
> }
> input => {
>     return Array.isArray(input) && input.length === 0;
> }
> ```

TypeScript compiler API is giving me wrong type when declaring object literal type with zero length tuple.

I'll study the reason why. Until the bug fix, please use like above `interface Foo` type.

**Comment by samchon** [comment]
@JakubSmahovsky Be fixed. Upgarde to `v3.7.8` please.
