### ISSUE TITLE
The primitive type and the literal type of the primitive type Union

### ISSUE THREAD

**Issue by kakasoo** [samchon/typia#614]
I found a really small bug.
This is also happening in typia@next.

```typescript
const wrongCase = typia.random<{ a: 3 | number }>(); // type is { a: 3 | number }

const rightCase = typia.random<3 | number>(); // type is just number

```

Can I try this problem today? (Maybe at night)

**Comment by kakasoo** [comment]
Oh, given that there is no problem with the properties of the interface, it seems possible for you to solve this problem in a few minutes. Then I'll just end with a bug report.

**Comment by kakasoo** [comment]
I gave up.

**Comment by AlexRMU** [comment]
This is a problem in the highlighting, in fact the type is always `number`
https://typia.io/playground/?script=JYWwDg9gTgLgBDAnmYBDANHA3g1BzAZzgF84AzKCEOAIiRVRoG4AoFgYwgDsD4B3SlzwBhVAQCmcALwJkaAHRRUXACZUAPDlQAuOAGY4AHzhcAriABG4qCQB8ACgCUrFvUkwAjNOxwd+oybmVjbErsjuAEzeBsZmltZhYO4GMp4A2jSMALqJ7gAs3m4QZHAC3CJi4vKoQA
