### ISSUE TITLE
Typia supports Cloudflare page functions (v8)?

### ISSUE THREAD

**Issue by TaxTool** [samchon/typia#619]
## Question
Thanks for the library! I'm trying to get it to work in v8 engine through Cloudflare page functions and I'm getting a `window is not defined` error. 

Are cloudflare workers are normally supported by Typia? 

The error only occurs when I generate typia code that includes `createValidateParse` and `createAssertParse`. `createIsParse` works just fine strangely.

**Comment by samchon** [comment]
Ah, I understood which feature occurs the bug.

I'll update a patch soon, and such bug would not be occured again.

Wait an hour please.

**Comment by samchon** [comment]
@TaxTool Upgrade to `3.8.4`, then your cloudfloare page functions would be supported.

**Comment by TaxTool** [comment]
I can verify that it's been fixed. Such an amazing and quick response, thank you!
