### ISSUE TITLE
Supporting really big or really small numbers

### ISSUE THREAD

**Issue by TaxTool** [samchon/typia#621]
## Question
I want to parse JSON strings that have values that are larger than Number.MAX_SAFE_INTEGER or smaller than Number.MIN_SAFE_INTEGER. 

Can Typia handle these cases? Maybe convert these to strings so that I can handle it in my app somehow?

Ex. Currently Typia handles the value `.510000000000000000000012` as `.51` instead of the full value.

**Comment by samchon** [comment]
I am sorry but it is not possible in JS in my knowledge.

**Comment by AlexRMU** [comment]
This is only possible using other representations, such as strings or arrays.
You can also use decimal.js or mathjs.
But to use this with typia, you need to wait until custom functions are supported.
