### ISSUE TITLE
Comment tag for primitive types

### ISSUE THREAD

**Issue by chmanie** [samchon/typia#623]
## Feature Request

Thank you for making this, I'm super grateful for all your effort.

I would really appreciate if this library supported comment tags on primitive types.

For example I would like to be able to do this:

```ts
// @type int
type Int = number;
typia.assert<Int>(500.5); // Should throw
```

Would that be possible?

**Comment by LucasSegersFabro** [comment]
Awesome lib, I was always so lazy to write complex types + complex validation and now I can mostly just write good types 🚀 

I needed to do something similar to this, maybe would fit into this feature request

```ts
/**
 * @format date
 */
type LatestUpdateDate = string | undefined;

export type TableStates = {
  [K in keyof PossibleTables]: LatestUpdateDate;
};
```

where the expected outcome was to validate each string for date format

**Comment by samchon** [comment]
Not possible, getting comment tags in TS API is only possible for object property type.

**Comment by samchon** [comment]
```typescript
/**
 * @minimum 3
 * @maximum 100
 */
type MyNumber = number;
```

@chmanie When you type like above, TS compiler just considers the `MyNumber` type as an alias type of `number`, and do not archive comment tags in API. Therefore, I don't have any way to come true your suggestion. @LucasSegersFabro  About the dynamic key property type, it is not possible, either.

Instead, what about validating through wrapping like below?

```typescript
import typia from "typia";

interface IntWrapper {
    /**
     * @type int
     */
    value: number;
}
typia.assert<IntWrapper>({ value: 500.5 });
```

**Comment by LucasSegersFabro** [comment]
@samchon yeah, that should work fine, thanks for the suggestion
