### ISSUE TITLE
안녕하십니까

### ISSUE THREAD

**Issue by hardcarryDev** [samchon/typia#628]
typia.assert<T> 

TypeGuardError가 throw 되지 않는 케이스 발견했습니다.

![image](https://github.com/samchon/typia/assets/21008572/d5c27dc6-9d2d-4ac2-8d3d-3b49e850bca5)

위 이미지는 T에 대한 명세입니다.

그리고 아래는 string이어야 될 user_id 항목에 number가 들어간 케이스이고, 정확히 assert가 작동합니다.
![image](https://github.com/samchon/typia/assets/21008572/0b3d6f77-65c7-4e5b-9981-ef61d38c431e)

그러나 아래 사진과 같이 타입T 에 대한 속성이 아닌 값이 들어왔을때 제대로 작동하지 않습니다. OR를 빼고 해도 마찬가지 입니다.
![image](https://github.com/samchon/typia/assets/21008572/3274325d-70f6-44d6-a4c1-3e797cbbc29d)

user_id 하나에 대한 결과(정상)
![image](https://github.com/samchon/typia/assets/21008572/93f10b38-b5e3-4599-beb1-e76d33701268)
 
타입 T와 다른 속성이 들어왔을때( 비정상 )
![image](https://github.com/samchon/typia/assets/21008572/d35945ea-a7cd-47c2-ab6b-89c9966ae13e)

에러처리 우선 순서는 typia(TypeGuardError)  -> prisma(PrismaClientValidationError) -> SyntaxError -> Error 순으로 되어있습니다.

**Comment by samchon** [comment]
Paste full type info, with reproducable repo

**Comment by hardcarryDev** [comment]
프로젝트 주소입니다.
https://github.com/hardcarryDev/toy_project_api


패키지 정보입니다. 

"devDependencies": {
    "@types/express": "^4.17.17",
    "@types/lodash": "^4.14.194",
    "@types/mysql": "^2.15.21",
    "@types/node": "^20.1.4",
    "@typescript-eslint/eslint-plugin": "^5.59.5",
    "@typescript-eslint/parser": "^5.59.5",
    "eslint": "^8.40.0",
    "eslint-config-prettier": "^8.8.0",
    "eslint-plugin-prettier": "^4.2.1",
    "nodemon": "^2.0.22",
    "prettier": "^2.8.8",
    "prisma": "^4.14.0",
    "ts-node": "^10.9.1",
    "ts-patch": "^2.1.0",
    "typescript": "^4.9.5"
  },
  "dependencies": {
    "@prisma/client": "^4.14.0",
    "dotenv": "^16.0.3",
    "express": "^4.18.2",
    "lodash": "^4.17.21",
    "mysql2": "^3.3.1",
    "typia": "^3.8.6"
  }

**Comment by samchon** [comment]
No, do not paste full repo code.

Make sole repo only containing reproducable code.

**Comment by samchon** [comment]
What you want seems like do not allowing superfluous properties.

In that case, use `assertEquals()` function instead.

https://typia.io/docs/validators/assert/#assertequals-function
