### ISSUE TITLE
[Question] typia.is method behavior does not seem to call Primitive type

### ISSUE THREAD

**Issue by kakasoo** [samchon/typia#632]
```typescript
interface Test {
    a: Date;
}

setTimeout(() => {
    const a = typia.random<Test>();
    const b = typia.is<Test>(a);
    console.log(b); // false
}, 1000);

```
I thought the random object created by the interface Test should come out as true in the `is` method. However, the Date object appears to return `false` because the type of a property is converted to string because the result of the primitive is string, and the `is` method is probably not compared with the value of the primitive result.
I think either `true` or `false` is a convincing result, but looking at the interface of the method, I think it's more intuitive to get `true`.

**Comment by kakasoo** [comment]
We talked about this topic on the Korean NestJS Kakao Talk channel. I think other people have similar thoughts.

**Comment by samchon** [comment]
`random<T>(): Primitive<T>` function returns primitive value, therefore it is not a bug.
