### ISSUE TITLE
Error: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by myyrakle** [samchon/typia#640]
### Summary

If I implement a controller action with TypedRoute, an error occurs.
I just ran it with `npm run start:dev`.
![image](https://github.com/samchon/typia/assets/16988115/d662148e-8280-498d-a413-baf3f25cd7df)

The code itself is nothing special.
![image](https://github.com/samchon/typia/assets/16988115/47ba0d65-126e-4429-8392-cbc32e785a11)

Replace TypedRoute.Post with Port and it runs fine...
![image](https://github.com/samchon/typia/assets/16988115/bb235848-4fbd-4708-b8db-b9ecd1a63dca)

### Code occuring the bug

here
https://github.com/myyrakle/_project/blob/c35f4186e6200afa7376bb0a896af1c6726a7762/src/wallet/wallet.controller.ts#L28

**Comment by samchon** [comment]
Your are using ORM entity class directly, and the entity class is extending `Model` class of `sequelize-typescript`.

Make independent DTO type, then it would be resolved.

**Comment by myyrakle** [comment]
good
