### ISSUE TITLE
How do you integrate with Axios?

### ISSUE THREAD

**Issue by andymac4182** [samchon/typia#653]
## Question
Axios doesn't pass the type information through to `transformRequest` and `transformResponse`. Do you have any ideas on how I could integrate Typia with Axios? It would be great to get the extra performance and type safety in Axios.

**Comment by samchon** [comment]
As frontend developer tend to use non standard TS compiler like babel or swc, it is hard to support. Instead, it would better to validate request DTO in server side. Or let server to make fetch collection library for every API routes like [nestia](https://github.com/samchon/nestia)

**Comment by andymac4182** [comment]
This is in NodeJS not Front end. Sorry I meant to include that.  

I am using OpenAPI generation but looking to get the benefits at the JSON.stringify and JSON.parse replacements. 

Thanks. Will have a look at how I can wrap this up.

**Comment by samchon** [comment]
You're meaning that backend is developed by other language. And client is using NodeJS.

By the way, I'm developing such feature in `nestia`, and in that case, you can generate type safe SDK library for client developers. With the SDK, you even can simulate the other language's backend server. If you're interested in and seems like proper solution, then just wait a month please.

  - https://github.com/samchon/nestia/issues/292
  - https://nestia.io/docs/sdk/sdk/
  - https://nestia.io/docs/sdk/simulation/

**Comment by andymac4182** [comment]
Yeah I am currently using https://www.npmjs.com/package/swagger-typescript-api to generate the client. Was thinking of using typia with that to generate type safe and fast clients. 

Would be awesome if the generated code didn't need a reference to typia to keep the code self contained and minimal references. 

Personally I use wiremocks to create the fake data as I can share that between multiple languages and run the docker container to fake the data for any language.
