### ISSUE TITLE
Support "branded" custom types

### ISSUE THREAD

**Issue by jasperlin451** [samchon/typia#654]
## Feature Request

Our existing codebase has a variety of existing "Branded" type definitions. For example, we have

```typescript
type Url = string & {
    __brands: {
        Url: "Url";
    };
}
```
When creating the assert definitions, this is what I see:
```typescript
export const assertUrl = (input: any): Url => {
    const __is = (input: any): input is Url => {
        return true;
    };
    if (false === __is(input))
        ((input: any, _path: string, _exceptionable: boolean = true): input is Url => {
            return true;
        })(input, "$input", true);
    return input;
};
export const assertString = (input: any): string => {
    const __is = (input: any): input is string => {
        return "string" === typeof input;
    };
    if (false === __is(input))
        ((input: any, _path: string, _exceptionable: boolean = true): input is string => {
            const $guard = (typia.createAssert as any).guard;
            return "string" === typeof input || $guard(true, {
                path: _path + "",
                expected: "string",
                value: input
            });
        })(input, "$input", true);
    return input;
};
```

Feature requests:
1. It would be ideal to get a warning message about types Typia doesn't understand. Right now it just assumes everything is a Url. Maybe Typia assumes you know you're only supposed to use basic types with it but you have to read the generated output to understand that.
2. Is there a way to support these branded types? I can understand that it would be hard to provide a general solution but if typia could support the user passing in some mapping (e.g. `Url` -> `string`)

**Comment by samchon** [comment]
I need to study about it, but may consume lots of time.

**Comment by samchon** [comment]
By the way, such crazy type comes from a specific library? If that, I also need to study about that for testing.

**Comment by samchon** [comment]
At first, I will ignore intersection type when an object type being used with atomic type like `string`.

In that case, only `string` type would be left. @jasperlin451 Do you agree? Then I'll patch in this week.

**Comment by jasperlin451** [comment]
The actual implementation of the weird object type is internal to our repo but I think the general concept of "Typescript brands" general involves the intersection type of those base types with some object structure.

As yes, simplifying those "nonsense" intersections down to the `string` or `number` type would be a great start.

**Comment by MatAtBread** [comment]
If you stumbled across this issue, I have patched typia to support brands. See https://github.com/samchon/typia/issues/911#issuecomment-2515870176

**Comment by blaiseludvig** [comment]
See [#1066 (comment)](https://github.com/samchon/nestia/issues/1066#issuecomment-3250335492) for possible solution.
