### ISSUE TITLE
remove typia comment option for new Type (feat. `typia.random`)

### ISSUE THREAD

**Issue by 8471919** [samchon/typia#665]
## Feature Request
Thanks for your suggestion. Feel free to just state your idea. Writing the issue, it would better to filling the below items:

  - A description of the problem you're trying to solve.
  - An overview of the suggested solution.
  - Examples of how the suggestion would work in various places.
    - Code examples showing the expected behavior.

In my case, I made a `TypeToSelect` type that makes all properties of type to change `true` type for using prisma select.

```typescript
type TypeToSelect<T extends object> = {
  [P in keyof T]: true;
};

interface User = {
  /**
   * @type int
   */
  id: number;
  
  /**
   * @format email
   */
  email: string;

  /**
   * @format date
   */
  birth: string;
}


// expected value : User { id: true, email: true, birth: true}
const a = typia.random<TypeToSelect<User>>(); // error occurs

// usecase
const user = await this.prisma.user.findFirst({
  select: typia.random<TypeToSelect<User>>();
});

```

but error occurs
```
Error on typia.MetadataTagFactory.generate(): format requires string type, but no "TypeToSelect<User>.email"

// and
Error on typia.MetadataTagFactory.generate(): format requires string type, but no "TypeToSelect<User>.birth"
```

I think this is beacause when `typia.random` generate a true value about email or birth, typia comments validate the email or birth as string.

and also, when I want to make new Type using existing Type without typia comment, the comment always follow with Type.
like
```typescript
interface User {
  /**
   * @format date
   */  
  email: string;

  /**
   * @format date
   */
  birth: string;
}

interface UserDate extends User {
  birth: Date; // but, birth has @format date
}
```
I know this is extremely rare case. (honestly, I think this is useless)

and I tried to make util function similar to `typia.random` to refer no comment. It failed.
It too difficult for me.

so... I suggest you that new feature:
1. typia.randomWithoutComment function
2. the way to make new Type without typia comment.

I always use typia well. I appreciate you to make typia.
thank you for reading this issue.

**Comment by samchon** [comment]
I think only below idea can resolve this issue. Wait for one or two months plz.

https://github.com/samchon/typia/issues/630#issuecomment-1547530286

**Comment by 8471919** [comment]
I figured out the way to make new Type without typia comment.
```typescript
type UserWithoutComment {
  [P in keyof User as `${P}`]: User[P]
}
```

I was idiot... thank you for your reply.
