### ISSUE TITLE
Can typia work with playwright?

### ISSUE THREAD

**Issue by ImaBadSlime** [samchon/typia#666]
## Question
Hello!
I'm trying to use typia paired with playwright for JSON validation, but I'm keep getting an error:
```
no transform has been configured. Run "npx typia setup" command.
```

I run the test file with ```npx playwright test error.test.ts```

#### error.test.ts
```
import { test } from "@playwright/test";

import typia from "typia";

interface ExampleSchema {
  myString: string;
  myNumber: number;
}

test("To show the bug", async () => {
  const exampleSchemaString = JSON.stringify(typia.random<ExampleSchema>());
  const typiaParsedObj = typia.assertParse<ExampleSchema>(exampleSchemaString);
  console.log(typiaParsedObj);
});
```

Is there any way to run typia with playwright?

P.S. “npx typia setup” didn't help =)

**Comment by HesherBomBom** [comment]
I have same problem

**Comment by samchon** [comment]
What is playwright? How to configure transform plugin in there?

**Comment by ImaBadSlime** [comment]
Playwright is the test automation tool that I'm using
It has native Typescript support

I dont actually know how to configure transform plugin from playwright, but in uses tcs so I thought it should work fine as all other modules

There is some info about transformation ts to js in playwright
https://playwright.dev/docs/test-typescript#manually-compile-tests-with-typescript
