### ISSUE TITLE
Progression for fastify plugin 

### ISSUE THREAD

**Issue by tawanchaiii** [samchon/typia#669]
## Progression for fastify plugin 

Hello @samchon. I found your article [from this link](https://dev.to/samchon/i-made-express-faster-than-fastify-4h8g)

and I saw this.
![image](https://github.com/samchon/typia/assets/26870250/28449793-3ad4-476d-9d0f-d946497b8657)

I know that you are developing the plugin to make Typia integrate with fastify.

I very interest your lib. I am looking for migrate my code that use Typebox for schema validation to typia.

Your typia is very interesting because, I can make a type with Pure Typescript

I want to know your progression of fastify plugin. If almost finish, pls point me to your references.

**Thank you.**

**Comment by samchon** [comment]
Currently, you can use `fastify` in NestJS with `nestia`, and it dramatically enhances performance.

This `nestia` was my 1st goal for supporting `fastify`.

  - Nestia Project: https://github.com/samchon/nestia
  - Benchmark Result: https://github.com/samchon/nestia/tree/master/benchmark/results/11th%20Gen%20Intel(R)%20Core(TM)%20i5-1135G7%20%40%202.40GHz

About pure plugin of `fastify`, I'll start it at next month July.

**Comment by tawanchaiii** [comment]
@samchon Thank you for your reply. I hope that your lib will provide in official fastify docs soon 🙏
