### ISSUE TITLE
typia comment is not applied to TypedBody (feat. #667) - "as" problem

### ISSUE THREAD

**Issue by 8471919** [samchon/typia#671]
Write detailed description in here.

few days ago, I test the `typia.random` function about Type that is defined using "as" keyword.
so at this time, I test that the `TypedBody()` can validate data using typia comment.
The result is... TypedBody can't validate data.

### Code occuring the bug
```typescript
import typia from "typia";

type AdminLogInInputDto = {
  /**
   * @format email
   * /
  email: string;

  password: string;
}

type A = {
  [P in keyof AdminLogInInputDto as P]: AdminLogInInputDto[P];
};

// controller
  @TypedRoute.Post('hi')
  async hi(@TypedBody() body: A) {
    console.log(body);

    const a = typia.random<A>();
    console.log(a);
    return a;
  }


```

<img width="994" alt="스크린샷 2023-06-19 오후 8 18 13" src="https://github.com/samchon/typia/assets/27190776/35749f61-07b5-464d-8876-8fe9184733a7">

first, I send a Post method with body `{"email": "test@naver.com", "password": "1234"}`. 
the body is validated correctly. but typia.random couldn't generate correct value.

second, I send a Post method with body `{"email": "1234", "password":"1234"}`.
the body is validated but incorrectly. if the typia comment(@format email) works correctly, server must throw the Error.
but It was not.

<img width="487" alt="스크린샷 2023-06-19 오후 8 18 52" src="https://github.com/samchon/typia/assets/27190776/3db69c90-acff-448c-ae95-2c437f1e3e9d">

look at the above picture. a has email property that has typia comment(@format email).

**Comment by samchon** [comment]
Type meta programming is not omnipotent tool, and no way for typia to support it when TMP spec does not support it unless contribute to the TS core team. Let's define exact type for the DTO case \o/
