### ISSUE TITLE
Invalid jsdoc comment for literals

### ISSUE THREAD

**Issue by KristjanTammekivi** [samchon/typia#673]
https://github.com/samchon/typia/blob/master/src/module.ts#L950
https://github.com/samchon/typia/blob/master/src/module.ts#L966

```literals<"A" | "B" | 1>; // [1, 2, 3] as const```
should be
```literals<"A" | "B" | 1>; // ["A", "B", 1] as const```

**Comment by samchon** [comment]
Tested it, but no problem:

```bash
git clone https://github.com/samchon/typia
cd typia
npm install
npm run issue 673
```

**Comment by KristjanTammekivi** [comment]
```typia master ✓ npm run issue 673                    

> typia@4.1.0 issue
> node test/issue 673

[ 'A', 'B', 1 ]
```
But docs say it will be [1, 2, 3]

**Comment by samchon** [comment]
Ah, bug was in comment. Thanks for reporting.

Would you send a PR? I can wait until Sunday.
