### ISSUE TITLE
How to stop allowing additional properties?

### ISSUE THREAD

**Issue by petarDenevFlutterint** [samchon/typia#675]
How to disable allowing additional properties when checking. The below example is an error for TS and VSCode but not for typia?
If I have type with one field and asset with more fields I expect to throw an error:
```javascript
  type Named = {
    Name: string;
  };

  const a /* : Named */ = {
    Name: 'someName',
    extraField: 'abc', // << this is an extra field
  };

  assert<Named>(a);
````

TS error:
```
Type '{ Name: string; extraField: string; }' is not assignable to type 'Named'.
  Object literal may only specify known properties, and 'extraField' does not exist in type 'Named'.ts(2322)
```

**Comment by samchon** [comment]
Use `assertEquals()` function

https://typia.io/docs/validators/assert/#assertequals-function
