### ISSUE TITLE
Adding custom formats.

### ISSUE THREAD

**Issue by SupremeTechnopriest** [samchon/typia#676]
Hello,

Thanks for the nice validation library.  I would like to be able to define my own formats along side the predefined ones.  Either that or have all the [ajv-formats](https://github.com/ajv-validator/ajv-formats/blob/master/src/formats.ts) implemented. I think a good approach would be to piggy back on the existing `customValidators`.

```ts
const formats: Record<string, RegExp> = {
  hash: /^0x[0-9a-fA-F]{16}$/,
  hostname: /^(?=.{1,253}\.?$)[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?(?:\.[a-z0-9](?:[-0-9a-z]{0,61}[0-9a-z])?)*\.?$/i,
}

typia.customValidators.insert('format')('string')(
  (format: string) => (value: string) => {
    const pattern = formats[format]
    if (!pattern) throw new Error(`Format '${format}' is not defined.`)
    return pattern.test(value)
  }
)
```

Then on your format factory you can check the custom validator map before no op on undefined formats. As a workaround I am just using the name `@shape`, but it would be much nicer to have all formats under the same key.

Let me know if you need more info.  Happy to open a PR, but I'm willing to bet that this would take you far less time than it would take me. It would take a bit to familiarize myself with the project, test suite and docs. 

Thanks!

**Comment by samchon** [comment]
Format tag of typia is following openapi spec, and the openapi spec does not handle the customization. I think it would better to use other tag rather than format.
