### ISSUE TITLE
literals should accept null

### ISSUE THREAD

**Issue by KristjanTammekivi** [samchon/typia#685]
## Feature Request
https://typia.io/playground/?script=JYWwDg9gTgLgBDAnmYBDOAzKERwERIqp4DcAUGYWgHQA2wMAplKrQM4A8A5AIJdwAfOADsArrVoA+ABQBKIA

Currently null does not work, the extends for literals does not allow for it and when suppressing the error it just omits the value from the array

**Comment by samchon** [comment]
I think that null cannot be distinguished as constant literal value of atomic values.

In JS classification, null is a type of object. Therefore, current typia supports only those types in literals function.

  - boolean
  - number
  - bigint
  - string

**Comment by KristjanTammekivi** [comment]
I don't quite see how that affects it, I managed to add a few lines of code into literalsProgrammer to get nulls to work

![image](https://github.com/samchon/typia/assets/8754356/242fbe4f-ed4d-45ee-baa3-3061c0c3d0b6)

I'd happily take a closer look at the original code but I can't seem to get the tests to work

A bit off topic: I wanted to add a github action step to check that the test:generate has been run, seemed to notify just fine, but after running test:generate the tests don't seem to pass https://github.com/KristjanTammekivi/typia/actions/runs/5414154249/jobs/9840790293

**Comment by samchon** [comment]
You can just check nullable through `Metadata.nullable` property in the `LiteralsProgrammer`.

Also, you have to change generic type of `literals` function to like below:

```
export function literals<T extends Atomic.Type | null>(): T[];
```
