### ISSUE TITLE
Feedback for “Is”

### ISSUE THREAD

**Issue by bogeeee** [samchon/typia#687]
> If you repeat to call typia.is<T>() function on the same type, size of JavaScript files would be larger because of duplicated AOT compilation

That sentence is very hard to understand for me. I mean either you compile it AOT or not ? How could the call at runtime result in larger compiled code ? Or am i missing something ?

**Comment by Th3Whit3Wolf** [comment]
Using `typia.is()` will compile AOT but it gets generated everytime it is called whereas if you were to use `typia.createIs()` it will generate that code once and wrap it in a function.


<table>
  <tr>
    <th>Method</th><th>Size</th>
  </tr>
  <tr>
    <td><code>.is()</code></td><td>size<sub>AOT</sub> × occurrences<sub>.is()</sub></td>
  </tr>
  <tr>
    <td><code>.createIs()</code></td><td>size<sub>AOT</sub> + size<sub>function wrapper</sub></td>
  </tr>
</table>
