### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Danes99** [samchon/typia#695]
## Bug Report

/Users/user/Documents/projects/json-validator/node_modules/typia/src/factories/TypeFactory.ts:91
    const get_name = (symbol: ts.Symbol): string => {
                     ^
RangeError: Maximum call stack size exceeded - /Users/user/Documents/projects/json-validator/src/index.ts:18:26
    at get_name (/Users/user/Documents/projects/json-validator/node_modules/typia/src/factories/TypeFactory.ts:91:22)
    at /Users/user/Documents/projects/json-validator/node_modules/typia/src/factories/TypeFactory.ts:67:34
    at /Users/user/Documents/projects/json-validator/node_modules/typia/src/factories/internal/metadata/iterate_metadata_native.ts:13:62
    at /Users/user/Documents/projects/json-validator/node_modules/typia/src/factories/internal/metadata/iterate_metadata.ts:77:45
    at /Users/user/Documents/projects/json-validator/node_modules/typia/src/factories/internal/metadata/explore_metadata.ts:28:55
    at /Users/user/Documents/projects/json-validator/node_modules/typia/src/factories/internal/metadata/iterate_metadata_intersection.ts:31:39
    at Array.map (<anonymous>)
    at /Users/user/Documents/projects/json-validator/node_modules/typia/src/factories/internal/metadata/iterate_metadata_intersection.ts:27:28
    at /Users/user/Documents/projects/json-validator/node_modules/typia/src/factories/internal/metadata/iterate_metadata.ts:44:72
    at /Users/user/Documents/projects/json-validator/node_modules/typia/src/factories/internal/metadata/iterate_metadata_union.ts:16:59

### 📝 Summary
Write a short summary of the bug in here.

  - **Typia Version**: 4.1.1
  - **Expected behavior**: 
  - **Actual behavior**: 

### 💻 Code occuring the bug
```typescript
import { readFileSync } from 'fs';
import { join } from 'path';

import typia from 'typia';

import type { ISetupConfig } from './sdk/main';

const assertJsonInput = typia.createIs<ISetupConfig>();

function main() {

  const rawJson = readFileSync(
    join(__dirname, './data/config_settings.json'),
    'utf8'
  );

  const jsObject: any = JSON.parse(rawJson);

  const isJsonFileValid = assertJsonInput(jsObject);

  console.log(`isJsonFileValid: ${isJsonFileValid}`);
}

main();
```

**Comment by samchon** [comment]
Where is `ISetupConfig` type? Please paste it with playground link

**Comment by Danes99** [comment]
```typescript
export type ISetupConfig =
  | ({
      type: 'Main';
    } & ISetupConfigMain)
  | ({
      type: 'Before';
    } & ISetupConfigBefore)
  | ({
      type: 'After';
    } & ISetupConfigAfter);

export type ISetupConfigMain = {
  content: ISetupConfig;
};

export type ISetupConfigBefore = {
  content: ISetupConfig;
};

export type ISetupConfigAfter = {
  content: ISetupConfig;
};
```

**Comment by Danes99** [comment]
https://typia.io/playground/?script=JYWwDg9gTgLgBAbzsAznAvnAZlCI4DkMAnmMAIYEDcAUDQKYAekscJY9cAkgMr0wBXMAGEIAOyzAA5nAC8NOHAA+cABQIFire3oAuQgFlywMdU2LMAMm59BI8ZKlGTASk0r157aT2EAQvRY0PRmWhhw1rz8QqIS0gFBUPRuih4aYYo6+gQAglgw9FChWlY20fZxUnkFUC60DMzQ8DpldrGOzmJyiJoAxuIFYjD6UW0O0rTo9UwszT6tMeNSCcHd6XD9Q-RDI7aLlZPTjawto-uO1YVrfQPbwwsVjod0WAJivTDA4nAgxmKqLh6ik2KHgiXo0jEAHkAEYAK3oH305DExGuYQA+sAACbZABsABYAJz0ci9GEAJgpRIAzASAIw0gCs9AADDCsDCCeRyEyCAAaLwmbFMfSswVhKQCHHZbH0vG9LAUgDsWAAtIimUS1QSacqmWryDSYfQ1UzWfR6UyABz0Cn00m9AVClA5D7AABuviw5AANih6BKtDC-Sjer4CAASen8xnWgB0NudYTIHwESWyAAsYDAwLoAPT5sC+sn0TMQX3Y+PAGD5mkUxj15NachSXwU8VeejEeiiX3QbIw30CEJBxRicggCM8GC4MQyADSKNHmimdGB4lByBQADFgpDYQiPt1UAAeM6PaQAPlU4IP8MRMDqNHQdF+JgBVCAA

**Comment by samchon** [comment]
I'll find how to solve the problem. Until that, it would better to change like below:

https://typia.io/playground/?script=JYWwDg9gTgLgBDAnmYBDOAzKERwORIqp4DcAUGQKYAeksCylcAkgMqUwCuYAwhAHYZgAczgBeMnDgAfFuy68BQ4QFlUwfpJlyO3PoJEAhShmiUtstrsUHhAQQwxKUclVrR4hJlYX7lajXE4AG8tLwAuOAAiAP4o8ikAYwEnfhhInz0lEXIAX1caOk9GHV9s4WNTKCYxELDGSKjKs3itZLTKNIz5LNs8gvd6L1Le5QcnKCDQqQjo8edWpJTO9JGbZX6KDE5+RJhgATgQdX4ACgBKOqX+AGd4KsoRfgB5ACMAK0o9yNR+RCmtFIAPrAAAmkTwADYACwATkoqESrwATMjYQBmaEARnRAFZKAAGV4YV7Q1CoXF4AA0gLgGlBNEiBJpUikwk4YIhoKxkMSGGRAHYMABaL642HC6HogW44WodGvSjC3EEyhY3EADkoyKxCMS1NpwBudj2wAAbpRIhhUAAbG6UFms16236JS34AAkWKpOI1ADpNQbWXAUHtONUIQALGAwMDhAD08bANsRlEjEBtoL9wBg8fRyOo+aDrNQwndyOZtMoiEofBt0AhrxtnEoxak-FQIHdeFYMGw-FEAGlfq3HfkKNc7nSbgAxMxPN6fPZBQhobM3AA8mXWIgAfKcHguPl8YOc8hRjhoLiQgA

```typescript
import typia from 'typia';

export type ISetupConfig =
  | ISetupConfigMain
  | ISetupConfigBefore
  | ISetupConfigAfter;

export type ISetupConfigMain = {
  type: "Main";
  content: ISetupConfig;
};

export type ISetupConfigBefore = {
  type: "Before";
  content: ISetupConfig;
};

export type ISetupConfigAfter = {
  type: "After";
  content: ISetupConfig;
};

function main() {
  const foreignObject: any = {
    _id: '649eacb22934135e0bfb4aa5',
    index: 0,
    guid: 'd16cf27f-ec59-4375-a3be-50e158e21eac',
    isActive: false,
    balance: '$1,138.58',
    picture: 'http://placehold.it/32x32',
    age: 20,
    eyeColor: 'blue',
    name: 'Strong Kane',
  };

  const isForeignObject = typia.is<ISetupConfig>(foreignObject);
}

main();
```

**Comment by samchon** [comment]
Upgrade to `typia@4.1.2`, then would be fixed.
