### ISSUE TITLE
Add Typia Support to nest js event patterns and message patterns

### ISSUE THREAD

**Issue by denniarems** [samchon/typia#697]
## Feature Request
Thanks for your suggestion. Feel free to just state your idea. Writing the issue, it would better to filling the below items:

  - A description of the problem you're trying to solve.
  - An overview of the suggested solution.
  - Examples of how the suggestion would work in various places.
    - Code examples showing the expected behavior.

**Comment by samchon** [comment]
Detailed description and consider to write on [nestia](https://github.com/samchon) please.

**Comment by denniarems** [comment]
can you please tell me why ?
