### ISSUE TITLE
Can typia work without strictNullChecks

### ISSUE THREAD

**Issue by HenryWu01** [samchon/typia#700]
## Question
Hi, thank you for your awesome project. You are a life saver to my Nest.JS project. However, a question araises when I tried to integrate my library in monorepo mode in Nest.JS instead of referencing as a seperated project hosted on npm.js.

As you may know, typegoose's ``Ref`` or findById might return undefiend, my code logic promise it will not be undefined or null. But I do not want add around 100 if checks to my code since it's redunant. So is there any chance that ``strictNullChecks`` can be disabled for typia? My use cause will not encounter situation with ``null`` or ``undefined``.

**Comment by samchon** [comment]
`typia does not allow `strictNullChecks` property, because `typia` utilizes TypeScript types directly.

If it allows, `typia` would generate terrible code like below:

```typescript 
// source code
typia.createIs<number>();

// generate code
$input => $input === null || $input === undefined || "number === typeof $input
```

**Comment by HenryWu01** [comment]
> `typia does not allow `strictNullChecks`property, because`typia` utilizes TypeScript types directly.
> 
> If it allows, `typia` would generate terrible code like below:
> 
> ```ts
> // source code
> typia.createIs<number>();
> 
> // generate code
> $input => $input === null || $input === undefined || "number === typeof $input
> ```

Thank you for answering! I decided to make my code strictNullChecks compatible.

**Comment by samchon** [comment]
Good choice
