### ISSUE TITLE
missing "url" in doc. typia comment tag > string > @format > url

### ISSUE THREAD

**Issue by rojiwon123** [samchon/typia#701]
in typia.io, comment tag > string > @format > url is missing.

typia comment tag is supporting @format url

<img width="894" alt="스크린샷 2023-07-03 오후 5 31 48" src="https://github.com/samchon/typia/assets/116284195/76762042-6342-41bc-9968-3d5a9b6fefdf">

**Comment by samchon** [comment]
https://typia.io/playground/?script=JYWwDg9gTgLgBDAnmYBDOAzKERwERIqp4DcAUGcAHYwCmUGqAxrXAJICytIARvXAG8ycEXAD0AKgnDRcCXAACGaCFTwArlAA2M0RLG64mrQC44AZxhRqAc3IBfCmLEBaNy7LP2AZU+v3ZIRoAHRMULRqtGzmADyc3HxQAHwAFACUJEA

In your screenshot, `typia` is validating `@format url` exactly. 

What is the problem?

**Comment by rojiwon123** [comment]
It is missing from the official documentation.

<img width="362" alt="스크린샷 2023-07-03 오후 5 40 53" src="https://github.com/samchon/typia/assets/116284195/9c940d1c-d401-4be4-b1f4-652e76d071b5">

**Comment by samchon** [comment]
Got it. Thanks for reporting. Now it be fixed.
