### ISSUE TITLE
Enum support

### ISSUE THREAD

**Issue by Namchee** [samchon/typia#703]
## Feature Request

Comment tags should support `enum` values for fields to filter specified value to the field. Currently, this is only supported in strings via the `regex` tag.

The tag should be defined in comma-separated values enclosed in square brackets.

```typescript
 /**
   * @enum [1, 2, 3]
   */
```

## Example Usage

```typescript
// Only books with categoryID 1, 2, or 3 are valid.

interface Book {
    /**
     * @type int
     * @enum [1, 2, 3]
     */
    categoryID: number;
}
```

**Comment by samchon** [comment]
Why you are not using real enum type?

```typescript
interface Book {
    categoryID: 1 | 2 | 3;
}
```

**Comment by Namchee** [comment]
I didn't know that was possible, sorry for the inconvenience. Thanks!
