### ISSUE TITLE
Support equality checking between two types.

### ISSUE THREAD

**Issue by MinisculeGirraffe** [samchon/typia#708]
## Feature Request
Firstly this is the best library i've ever used. I love you. 

### Description
The way that this library works to do compile time code generation is very similar to how Rust works with it's procedural macros and it's trait system. 

The current state of the library operated very similar to how the Rust library [serde](https://serde.rs/derive.html) works. The default behavior when parsing some JSON is to always make sure the types match what you're trying to parse, and it acomplishes that with compile time code generation.

You seem to also be handling another rust procedural macro, [clone](https://doc.rust-lang.org/std/clone/trait.Clone.html), by doing compile time code generation for clone functions.

However Rust can compile time codegen more functionality that would likely be possible to implement in this library, and also be super useful to have in TS.

- [Eq](https://doc.rust-lang.org/std/cmp/trait.Eq.html)
This is used to provide equality checking.  For all non trivial data types JS uses pointer equality which is lame.I would absolutely love a compile time object equality checkers 
- [Ord](https://doc.rust-lang.org/std/cmp/trait.Ord.html)
Provides ordering for objects/enums
- [Hash](https://doc.rust-lang.org/std/hash/trait.Hash.html)
Converts a type into a hash based on the values and structure of the type.

Each of the links have examples of how they function and the expected behavior.

 I can write TS examples if they would help.

**Comment by samchon** [comment]
For a long time, I had made a [TSTL](https://github.com/samchon/tstl) ilbrary that migrated from C++ STL to TypeScript.

In [TSTL](https://github.com/samchon/tstl), it is possible to define above three functions, `equals()`, `less()` and `hashCode()`. What about using below codes? Especially about the `Hash` function, I think iterating every member properties are inefficient. In actually, many programmers are composing `hashCode()` function with only few members (in Java).

Anyway, I think your suggestions can be accomplished ust by using traditional runtime logics like below. It is possible to optimize `Eq`, `Hash` functions through AOT compilation with `typia`, but I can't understand why they are required. If I am missing something, or you have another insight, then tell me please.

## Using Class
```typescript
import std from "tstl";

class MyCompositeKey {
    group: string;
    name: string;

    equals(x: MyCompositeKey): boolean {
        return this.group === x.group && this.name === x.name;
    }
    hashCode(): number {
        return std.hash(this.group, this.name);
    }
    less(x: MyCompositeKey): boolean {
        return this.group === x.group
            ? this.name < x.name
            : this.group < x.group;
    }
}
const hashMap: std.HashSet<MyCompositeKey> = new std.HashSet();
const treeMap: std.TreeSet<MyCompositeKey> = new std.TreeSet();
```

## Using Interface
```typescript
import std from "tstl";

interface MyCompositeKey {
    group: string;
    name: string;
}
const hashMap: std.HashSet<MyCompositeKey> = new std.HashSet(
    x => std.hash(x.group, x.name),
    (x, y) => x.group === y.group && x.name === y.name
);
const treeMap: std.TreeSet<MyCompositeKey> = new std.TreeSet(
    (x, y) => x.group === y.group
        ? x.name < y.name
        : x.group < y.group
);
```

## Equailty Function
Also, the `Eq` function case, you can easily implement it like below:

```typescript
export const json_equal_to =
    (exception: (key: string) => boolean) =>
    <T>(x: T) =>
    (y: T): string[] => {
        const container: string[] = [];
        const iterate =
            (accessor: string) =>
            (x: any) =>
            (y: any): void => {
                if (typeof x !== typeof y) container.push(accessor);
                else if (x instanceof Array)
                    if (!(y instanceof Array)) container.push(accessor);
                    else array(accessor)(x)(y);
                else if (x instanceof Object) object(accessor)(x)(y);
                else if (x !== y) container.push(accessor);
            };
        const array =
            (accessor: string) =>
            (x: any[]) =>
            (y: any[]): void => {
                if (x.length !== y.length) container.push(`${accessor}.length`);
                x.forEach((xItem, i) =>
                    iterate(`${accessor}[${i}]`)(xItem)(y[i]),
                );
            };
        const object =
            (accessor: string) =>
            (x: any) =>
            (y: any): void =>
                Object.keys(x)
                    .filter((key) => x[key] !== undefined && !exception(key))
                    .forEach((key) =>
                        iterate(`${accessor}.${key}`)(x[key])(y[key]),
                    );

        iterate("")(x)(y);
        return container;
    };
```

**Comment by samchon** [comment]
Follow-up: the `Eq` part shipped as `typia.misc.equal` (being relocated to `typia.compare.equal` in #1952), and the `Ord` part is now specified in #1950 as `typia.compare.less<T>(x, y): boolean`. `Hash` remains open.
