### ISSUE TITLE
Strongly typed parsing/transformation

### ISSUE THREAD

**Issue by BenjaBobs** [samchon/typia#710]
The improved json parsing that Typia provides is nice, but as far as I can tell it currently still doesn't allow us to skip the step of transforming the parsed json data into the actual models we want to use, because the parsing is still done through `JSON.parse()`.

Example:
```ts
// Given some type
type MyType = {
  id: number;
  nestedObject: {
    timestamp: Date; // <-- sent as string in json
  };
};
```

```ts
// When parsing the json, we cannot actually use the timestamp as a Date
const json = `
{
  "id": 1,
  "nestedObject": {
    "timestamp": "1982-01-05"
  }
}
`;

const parsed = JSON.parse(json); // Cannot type as MyType as that would currently be incorrect
console.log(parsed.nestedObject.timestamp); // "1982-01-05"
```

Most of the time I want to work with strongly typed `MyType`.
Since Typia already generates functions for validating, so maybe the type info can be used to also generate some code to do transformation into the type?

Very naive version of this could be with a transformer function that can take an input object and a transformation _"schema"_.
```ts
// Transformation function
function transform<T = any>(input: any, transformer: any) {
  if (input == null) return input;

  for (const [key, value] of Object.entries(transformer)) {
    if (input[key]) {
      if (typeof value === "function") {
        input[key] = value(input[key]);
      } else {
        input[key] = transform(input[key], value);
      }
    }
  }

  return input as T;
}
```

```ts
// Transformation schema for MyType
const myTypeSchema = {
  nestedObject: {
    timestamp: (input: any) => new Date(input)
  }
};

const parsed = JSON.parse(json); // typed as Any
console.log(parsed.nestedObject.timestamp); // "1982-01-05"

const transformed = transform<MyType>(parsed, myTypeSchema); // now typed as MyType
console.log(transformed .nestedObject.timestamp); // Tue Jan 05 1982 01:00:00 GMT+0100 (Central European Standard Time)
```

I've no idea how simple/hard this would be to implement, but this feature would be my main reason for using Typia.

**Comment by samchon** [comment]
This feature may what you want, but its priority is low.

https://github.com/samchon/typia/issues/683

**Comment by BenjaBobs** [comment]
Ah, very good point, I tried searching but somehow didn't understand that #683 is basically the same feature request.
I'll close this and follow the other. 😄
