### ISSUE TITLE
Remove cursing for random "any"

### ISSUE THREAD

**Issue by mmamedel** [samchon/typia#737]
Thank you very much for the random generator tool. It has helped a lot when it comes to perform testing. We just noticed that whenever we generate random objects that have properties with the "any" type, they come as a literal string:

> "f***king any type exists..."

We understand the frustration with the "any" type but unfortunately some of it comes from third-party libraries that we are using. Do you think we could remove the cursing here to something like:

> "any type used..."

An angry face emoji 😠 could be included too to express the frustration.

Thank you for considering this

**Comment by marcesengel** [comment]
I think it's pretty easy to create a PR for this issue and that in turn will most likely improve your odds 🤣

**Comment by samchon** [comment]
Wait your PR
