### ISSUE TITLE
Why are the createXx functions needed?

### ISSUE THREAD

**Issue by marcesengel** [samchon/typia#738]
## Question

Hi!

Today I created a bug (`Error on typia.is(): no transform has been configured.`) by using `is` in place of `createIs` and I was wondering why that's an issue? In my head the code transformer would transform `is<...>` to code and leave the argument untouched. However the actual behaviour is, that `is<...>` will not be transformed unless invoked (I tried to do `.filter(typia.is<...>)`).

I was just wondering why this is (and thereby there is a nead for the separate `createXx` functions)? I understand if you don't have time to answer this :D if you do, I'd like to say thank you in advance.

Best regards

**Comment by samchon** [comment]
https://dev.to/samchon/good-bye-typescript-is-ancestor-of-typia-20000x-faster-validator-49fi

In the early `typia` (named `typescript-json` at the time), just typing `TSON.stringify<T>` produced the same effect as the current `typia.createStringify<T>()` function . However, as `typia` absorbed and accepted `typescript-is`, it decided to follow the interface of `typescript-is`, so the factory function was provided separately as it is now.

**Comment by marcesengel** [comment]
Thank you for the explanation! I will close this for now, as I understand the reasoning, even though I would have prefered the old behaviour, as it's more in line with normal functions. What do you think about keeping the factory function, but supporting the old syntax as well?

**Comment by samchon** [comment]
As long as I accept the create factory functions, If it is combined with creating a factory function only with simple designation like `typia.is<T>;`, it is not good in terms of consistency, so it was deleted. As the designation like `typia.is<T>` even can be written just by mistake (forgotten to write call expression), I'm careful about the revival.

**Comment by marcesengel** [comment]
I'd argue that this is the point with any function and something typescript should save us from, but I get what you mean 👍
