### ISSUE TITLE
Typia stringify nested object

### ISSUE THREAD

**Issue by HenryWu01** [samchon/typia#739]
## Question
I'm working with a nested object as shown below:

```JavaScript
exParams: {
    dataId: '123456',
    dataType: 2
}
```

By using the following code, I can stringify this object as expected:
```TypeScript
private static _stringify(input: object): string {
    for (const key in input) {
        if (_.isObject(input[key])) {
            input[key] = this._stringify(input[key]);
        }
    }

    return JSON.stringify(input);
}
```

The output is as expected: ``{"exParams":"{\"dataId\":\"123456\",\"dataType\":2}"}``

However, when I try to use the typia library to stringify the nested object according to the defined SampleInterface, the nested object doesn't get stringified as desired
```TypeScript
export interface SampleInterface {
    exParams: {
        dataId?: string;

        dataType?: number;
    };
}

typia.stringify<SampleInterface>(input)
```

The result is: ``{"exParams":{"dataId":"123456","dataType":2}}``

Is there a way to get typia to stringify the nested object?

**Comment by samchon** [comment]
https://typia.io/playground/?script=JYWwDg9gTgLgBDAnmYBDOAzKERwERIqp4DcAUGQKYAekscwAdjJVBqgMaVwDKq4AG0oBJZq3Zc4AbzJw5cGgAVUUfgGcAXNNnzdAE1QxUwvQH4tamFCYBzcrv2HUAFWSVzcRgFcQAI1b28gC+5EFkhGgAdBxQlIaUPFa2wBiIADx8giJibJyUAHwAFACUJEA

It seems well stringified. What is the problem?

Tried below code, and exact JSON string be generated

```typescript
import typia from "typia";

export interface SampleInterface {
    exParams: {
        dataId?: string;
        dataType?: number;
    };
}

const value: string = typia.stringify<SampleInterface>({
    exParams: {
        dataId: "123456",
        dataType: 2,
    },
});
console.log(value);
```

```json
{"exParams":{"dataId":"123456","dataType":2}}
```

**Comment by HenryWu01** [comment]
> https://typia.io/playground/?script=JYWwDg9gTgLgBDAnmYBDOAzKERwERIqp4DcAUGQKYAekscwAdjJVBqgMaVwDKq4AG0oBJZq3Zc4AbzJw5cGgAVUUfgGcAXNNnzdAE1QxUwvQH4tamFCYBzcrv2HUAFWSVzcRgFcQAI1b28gC+5EFkhGgAdBxQlIaUPFa2wBiIADx8giJibJyUAHwAFACUJEA
> 
> It seems well stringified. What is the problem?

The difference is that it converts object to string representation as well (with escape character and quotation mark on both end), does ``typia`` provide such option to do that?

![Code_vG5qnxDdSv](https://github.com/samchon/typia/assets/99880210/5f48a231-9a51-4ce9-8cc0-6c71259cf959)

**Comment by samchon** [comment]
What you want is `JSON.stringify(JSON.stringify(input))` for nested object?

**Comment by HenryWu01** [comment]
> What you want is `JSON.stringify(JSON.stringify(input))` for nested object?

I think the logic is, if an object have nested object, stringify that nested object to string representation frist, and then stringify the final object

**Comment by samchon** [comment]
I can't accept your suggestion because it is not a standard case.

But I am curious the reason why. Why are you doubly serializing? Is there any special reason?

**Comment by HenryWu01** [comment]
> I can't accept your suggestion because it is not a standard case.
> 
> But I am curious the reason why. Why are you doubly serializing? Is there any special reason?

Yes. Some ``Chinese`` website use the method I mentioned to ``stringify`` object data, without nested stringify, the server won't accept the request and response with an error. Thank you for your time answering my question! I think for this case I need to go with ``JSON.stringify``

**Comment by samchon** [comment]
Thanks for replying.
