### ISSUE TITLE
Is it possible to use decorators instead of comments 

### ISSUE THREAD

**Issue by vsamofal** [samchon/typia#742]
## Feature Request

  - A description of the problem you're trying to solve.

I'm not fill pretty comfortable with writing comments for validations, and it will be great to have the ability to write well all decorators, since typia just reads comments, probably it won't be that hard to support both. Happy to contribute to it, but probably will need some guidance, I checked typia code and it's not that easy to work with it because of AOT 

  - An overview of the suggested solution.

same way as class validator

  - Examples of how the suggestion would work in various places.

same way as a class validator

    - Code examples showing the expected behavior.

same way as a class validator

https://github.com/typestack/class-validator

interesting to talk it through

**Comment by KotlinIsland** [comment]
Typia doesn't use comments, it uses the type annotations. Could you clarify what you mean by comments?

**Comment by samchon** [comment]
`typia` supports interface type, and the interface type cannot use property decorator.

```typescript
export interface ISomething {
    value: number;
}
```
