### ISSUE TITLE
Feature: VSCode extension for typia autocomplete / lint

### ISSUE THREAD

**Issue by TriStarGod** [samchon/typia#754]
## Feature Request
Thanks for your suggestion. Feel free to just state your idea. Writing the issue, it would better to filling the below items:

  - A description of the problem you're trying to solve.
Mistakes can easily occur while creating comment based validations
  - An overview of the suggested solution.
Autocomplete / lint of typia tags and values
  - Examples of how the suggestion would work in various places.
@format uui (would error or shown tab to complete to uuid)

**Comment by samchon** [comment]
What is the purpose? Detailed description please.

**Comment by TriStarGod** [comment]
**Linter**: a static code analysis tool used to flag programming errors, bugs, stylistic errors and suspicious constructs; Reasons why? Comments can include any text, including invalid content; Without a linter, it would be hard to identify and correct mistakes;
**Autocomplete**: a software function that gives users the option of completing words or forms by a shorthand method on the basis of what has been typed before; Reasons why? Reduce errors and increase development speed;
**Visual Studio Code extension**: VSCode has 81% market coverage;

**Comment by samchon** [comment]
https://typia.io/docs/validators/tags/

Use type tags of v5 instead, it is type safe as you wish.
