### ISSUE TITLE
have you planned to support generic type?

### ISSUE THREAD

**Issue by Moon-DaeSeung** [samchon/typia#757]
assume array named 'arr' that has three object [a, b, c]
a's type is A
b's type is B
c's type is C

I want to make function find which need generic type argument
like this
function <T>findWithGeneric(value: any) {
     ....
}

I wonder if typia.is<T> support generic type like this:

function <T>findWidthGeneric(value: any) {
   return typia.is<T>(value)
}
const result = arr.find<A>((value) => find(value) )
console.log(result) // 'a'

**Comment by samchon** [comment]
No plan. Use functional parameter instead.
