### ISSUE TITLE
Primitive? 

### ISSUE THREAD

**Issue by dan-fritchman** [samchon/typia#762]
Great library, thanks for your work on it! 

I see there are a handful of functions documented to have call-signatures like so:  
https://typia.io/docs/json/parse/
```typescript
function validateParse<T>(input: string): IValidation<T>;
```

But the actual call signature, at least in the current v4.2.3, is this:  
```typescript
function validateParse<T>(input: string): IValidation<Primitive<T>>;
```

Where the difference there is the `Primitive` in the return type. 

What does one do with these `Primitive`s? How does one get the `T` out of them?  
They seem to be pretty light in the documentation.

**Comment by kakasoo** [comment]
I sympathize with the poorness of the document. However, I think it is encouraging because typia is being updated at a very fast pace. To answer on behalf of this library developer, Primitive is the type that deduces the primitive types that typescript originally have. For example, Primary <Date> is string.

Please correct anyone if my answer is wrong.

**Comment by samchon** [comment]
https://typia.io/docs/json/parse/

Click third tab `Primitive`

**Comment by dan-fritchman** [comment]
FWIW that doc snippet didn't really answer anything for me.  
(Other than, you guys do seem to know this type system quite well.)  

Anyway great work on the library, no worries here.

**Comment by samchon** [comment]
Isn't this comment description enough? If not, which point should I explain?

![image](https://github.com/samchon/typia/assets/13158709/36d99f88-8534-4794-ac27-0e01955e9696)

**Comment by RDeluxe** [comment]
Hey there! I'm also a bit puzzled on how to use this type.

```typescript
   const parsedObject = typia.json.assertParse<T>(message.content)
   // parsedObject is of type Primitive<T>, but that's not that I want nor expected here. I want a T object that I can continue to play with
```

A really simple 2 line example of how to get the `T` object "back" from the Primitive would help a lot, because the main point of parsing the JSON is to use its value afterward!
