### ISSUE TITLE
Feature Request: @alias comment tag

### ISSUE THREAD

**Issue by Namchee** [samchon/typia#763]
## Feature Request

Thanks for this amazing project! I would like to request a new comment tag `@alias` that's mainly used for enhanced features. As the name implies, `@alias` maps a field to another name when being stringified and vice versa.

The most common use case for this tag is `snake_case` to `camelCase` conversion or simply having a different dictionary for I/O purposes.

`class-transformer` have a similar feature that can be achieved using the `@Expose` decorator

### API Proposal

```ts
import typia from 'typia';

interface Person {
  /**
   * @format date
   * @alias date_of_birth
   */
  dateOfBirth: string;
}

const json = `{ "date_of_birth": "2023-07-01" }`;
const object = typia.assertParse<Person>(json);

console.log(object); // { dateOfBirth: "2023-07-01" }

const jsonString = typia.stringify(object); // { "date_of_birth": "2023-07-01" }
```

**Comment by samchon** [comment]
This is too domestic feature.

Use conversion casting types and functions like below.

https://gist.github.com/kuroski/9a7ae8e5e5c9e22985364d1ddbf3389d

**Comment by samchon** [comment]
Suggesting naming notation conversion function also can be an alternative option.

```typescript
export function pascal<T extends object>(obj: T): Pascal<T>;
export function camel<T extends object>(obj: T): Camel<T>;
export function snake<T extends object>(obj: T): Snake<T>;
```

**Comment by Namchee** [comment]
What if we need to map it to entirely different field when parsing and serializing JSON? The naming notation conversion is just one example of usecase for `@alias`

**Comment by kakasoo** [comment]
@Namchee 
Is there a reason not to express it through a customized type?
Below is an example of how to turn a snake into a camel. I can also implement this opposite. Do you need any help?

```typescript
export type ToString<T> = T extends string ? T : T extends number ? `${T}` : never;

export type CapitalizeFirstLetter<T extends string> = T extends `${infer F}${infer Rest}`
  ? `${Uppercase<F>}${Rest}`
  : T;

export type TitleCase<T extends string[]> = Join<
  {
    [K in keyof T]: CapitalizeFirstLetter<T[K]>;
  },
  ''
>;

export type Tail<T extends readonly string[]> = T extends readonly [infer Head, ...infer Rest] ? Rest : [];

export type Join<T extends readonly string[], U extends string> = T extends readonly []
  ? ''
  : T extends readonly [infer F]
  ? F
  : `${T[0]}${U}${Join<Tail<T>, U>}`;

export type Split<T extends string, P extends string = ''> = T extends `${infer F}${P}${infer Rest}`
  ? [F, ...Split<Rest, P>]
  : T extends ''
  ? []
  : [T];

export type SnakeToCamel<S extends string> = CamelCase<Split<S, '_'>>;

export type CamelCase<T extends string[] | string> = T extends string[]
  ? `${T[0]}${ToString<TitleCase<Tail<T>>>}`
  : T extends string
  ? SnakeToCamel<Lowercase<T>>
  : never;
```
