### ISSUE TITLE
Use with TypeScript Project References

### ISSUE THREAD

**Issue by dan-fritchman** [samchon/typia#773]
Can typia be used with TypeScript projects using the project-references feature? 

https://www.typescriptlang.org/docs/handbook/project-references.html

This may boil down to a `tsc` compiler support question. Last I see out on the interwebs is from 2020, saying that the combination of `transforms` and `references` is not supported: 

https://stackoverflow.com/questions/61552896/use-typescript-custom-transformer-and-project-reference

My own experience has been that this doesn't work; every sub-project other than the one that directly depends on `typia` produces this: 

```
Uncaught Error: Error on typia.validateParse(): no transform has been configured. Read and follow https://typia.io/docs/setup please.
```

**Comment by jmroon** [comment]
Typia works with the standard Nx monorepo setup, so maybe go with a similar approach to tsconfigs.

```
/
-- packages/
---- project1/
------ tsconfig.json <-- extends tsconfig.base.json, has project references to tsconfig.app.json, tsconfig.spec.json
------ tsconfig.app.json
------ tsconfig.spec.json
--tsconfig.base.json <-- base tsconfig which every project extends. Has the typia transform plugin
```

**Comment by dan-fritchman** [comment]
Terrific thanks - confirming this works for me, with the typia transform in the "parent" `tsconfig` shared by all sub-projects.

Thanks again!
