### ISSUE TITLE
Human readable validation errors.

### ISSUE THREAD

**Issue by SupremeTechnopriest** [samchon/typia#774]
## Feature Request

Hello!

Looking for a way to map validation errors to a more user friendly format.  Maybe something like:

```ts
interface RequestBody {
  /**
   * User email adddress.
   * 
   * @format email
   * @message Your email address is invalid.
   */
  name?: string
}
```

and then the validatation error:

```ts
[{
  path: 'input.email',
  expected: 'string (@format email)'
  message: 'Your email address is invalid.'
  value: foo
}]
```

I think this would be a nice addition. The alternative is writing a function to map the `expected` field to human readable format which can be cumbersome.

**Comment by samchon** [comment]
Current TypeGuardException is enough identifiable. This suggestion could not be accepted because this way cannot support union type case, and validate method tracing every type errors. Hope to adjust current structure.
