### ISSUE TITLE
Can typia work with nuxt3?

### ISSUE THREAD

**Issue by huyoo** [samchon/typia#775]
## Question
Hello!
I'm trying to use typia paired with nuxt3 for JSON validation, but I'm keep getting an error:

```
no transform has been configured. Read and follow https://typia.io/docs/setup please.
```

I run the project with `pnpm run dev`
code like this
```
interface Query {
  projectId: string
  pId?: string
}

function queryFn(params) {
  typia.validate<Query >(params)
}

queryFn({
  projectId: 'testId'
})
```

Is there any way to run typia with nuxt3?

P.S. “pnpm typia setup --manager pnpm” didn't help =)

**Comment by jmroon** [comment]
Did you add the typescript plugin to vite as detailed on the page you linked?

And does your tsconfig have a transform section? The typia setup should have added it. It should look something like this:

![image](https://github.com/samchon/typia/assets/36086006/083d3ca0-c974-4c4c-9c2b-59cc4ca8b63a)

**Comment by ryoppippi** [comment]
Hi guys!
I made a plugin for bundlers
Check this out and plz give us a feedback!

https://typia.io/docs/setup/#unplugin-typia

Note that this plugin supports `ts`/`tsx` files only, so if you wan to use Typia for your nuxt project, define validation functions in `.ts` and then import them in `.vue` file
