### ISSUE TITLE
Sharing resources on custom comment tags parsing

### ISSUE THREAD

**Issue by jymchng** [samchon/typia#777]
Hi, Typia is an excellent validation library that I am currently using in my side project, thanks for creating this.

I am interested to learn more about custom comment tags parsing which you use heavily in Typia, e.g. `@int` which validates a field is of type 'integer' at runtime.

The Internet is sparse with resources that explain how this works behind the scene. I would be grateful if you can point to me resources on this or perhaps some of your code snippets where you use this magic in the implementation of Typia.

Thank you.

**Comment by samchon** [comment]
https://dev.to/samchon/series/22474

Enough explanation? or something more required?

**Comment by jymchng** [comment]
Hi @samchon Thank you for sharing the link but your blog posts do not go into the actual codes that deal with the parsing of the comment tags. Do you have specific lines of codes that you can share with me to accomplish this? Thank you.

**Comment by samchon** [comment]
1. Get comments -> https://github.com/samchon/typia/blob/master/src/factories/internal/metadata/emplace_metadata_object.ts#L56
2. Convert to type tags -> https://github.com/samchon/typia/blob/master/src/factories/MetadataCommentTagFactory.ts
3. Type tag generation and validation -> https://github.com/samchon/typia/blob/master/src/factories/MetadataTypeTagFactory.ts
4. Type tags to validation script (`number` case) -> https://github.com/samchon/typia/blob/master/src/programmers/internal/check_number.ts
5. Validation script to TS elements -> https://github.com/samchon/typia/blob/master/src/factories/ExpressionFactory.ts#L127
6. Where parsed type tags be placed in -     public readonly tags: IMetadataTypeTag[][];

**Comment by jymchng** [comment]
Hi @samchon, thank you for pointing me to the exact lines of codes that accomplish the beautiful parsing of tag comments which is essential in the implementation of this beautiful library. I deeply appreciate your time and effort in rendering me this help. I will study these codes deeply and learn as much as possible from you.

Thank you.
