### ISSUE TITLE
Custom validators

### ISSUE THREAD

**Issue by SupremeTechnopriest** [samchon/typia#792]
Hello!

Has the ability to create custom comment tags been removed from v5?  It looks like the `customValidators.insert` function is no longer exported.  I see the documentation for creating custom validation types, but I prefer the comment tag syntax.

**Comment by samchon** [comment]
Yes, removed it for type safety.

**Comment by SupremeTechnopriest** [comment]
Okay, so no way to do custom comment tags anymore?  The new API makes it difficult to do complicated validations because everything is a string now.

For example: 

```ts
export type CommaSeparated<Value extends string> = tags.TagBase<{
  kind: 'commaSeparated',
  target: 'string',
  value: Value,
  validate: `$input.split(',').every(v => ${Value}.split(',').includes(v))`
}>
```

This validator fails to compile. I want to validate if a comma separated string of values is part of a union type. Is there a better way to achieve this?  Im validating a search parameter so passing an array isn't possible.

**Comment by SupremeTechnopriest** [comment]
Trying to use it like this:

```ts
interface IRequestQuery {
  foo: string & CommaSeparated<'bar,baz'>
}
```

**Comment by SupremeTechnopriest** [comment]
Ideally I would be able to use an actual union type:

```ts 
export type MyType = 'bar' | 'baz'
```

**Comment by SupremeTechnopriest** [comment]
Any suggestions on how to implement this validator? It seems to fail when I pass the iterator function to every.

**Comment by SupremeTechnopriest** [comment]
Here is a playground that demonstrates the error.  It compiles ok for js but not ts.

https://typia.io/playground/?script=JYWwDg9gTgLgBDAnmYBDANHA3g1BzAZzgF84AzKCEOAIiRVRoG4AoF4AOxgFMozUAxtzgBJALLcQAI17YWcBXGAATAFxwCMKJzxwAZHACKAV1RdgZRABFQ3DgWAR7AHhbE29YSbMwL12-aOLvJwAGqoADbGwtwAHjwcygQhCgA+cADkggCOGSlw6Rl2eHmKBZnAMGClioUCHABueQB8cAC8uIQAdAAq+ABCqATczlghANacapnKAQ5OBDUwqFB43DDqGZraHCUhDZHR6uFR3PuRKqg86gAGACScYMYwXQRgEZUAFBnoGQCUXW4DV4iE+j2e7Va4PgbVhmTIEAg-xubmabAEC3gBw+ynaCGQaC6Aig3Cu3BOlx4AFFsqYIgRnOJJDIoM1Pn8gA

**Comment by samchon** [comment]
Succeeded to find the reason why bug being occured.

Would be fixed soon, and patch version `5.0.1` would be published soon.

Thanks for reporting.

**Comment by SupremeTechnopriest** [comment]
Awesome! Glad to help!

**Comment by SupremeTechnopriest** [comment]
Works like a charm.  Thanks!
