### ISSUE TITLE
How to validate startDate < endDate in same a input?

### ISSUE THREAD

**Issue by trangianhuan** [samchon/typia#799]
## Question

I can't find an example for this case

```
export interface IApp {
  startDate: Date;
  endDate: Date;
}
```

**Comment by samchon** [comment]
Do not support custom validation for specific class (object) case. 

I think that the `IApp` case, you should make addtional function like below.

```typescript
const assertApp = (app: IApp) => {
    typia.assert(app);
    if (startDate < endDate)
        throw typia.TypeGuardError({
            ...
        });
};
```

**Comment by trangianhuan** [comment]
i got it.
`assertApp` will be called in the controller?

> Do not support custom validation for specific class (object) case.

Will it be supported in the future? @samchon

**Comment by samchon** [comment]
If want to earlier publish, can you suggest a good interface? The new suggestion should be compile time safe like current.

**Comment by trangianhuan** [comment]
I'm sorry 
I don't understand what you mean 🥲

**Comment by samchon** [comment]
I mean suggest me a way how to (interface level)

**Comment by trangianhuan** [comment]
it will look like:
```
export interface IApp {
  startDate: Date;

  /**
     * @greaterOrEqualField startDate
     */
  endDate: Date;
}
```

**Comment by sunrabbit123** [comment]
@gte
@gt
@lt
@lte
@eq

These tags look like they could be very useful!

If you can, of course.

These are the tags that came to mind from trangianhuan's comment.
