### ISSUE TITLE
Nextjs 13.4

### ISSUE THREAD

**Issue by mp3por** [samchon/typia#801]
Hello,

I saw the thread for Nextjs SWC however I am not that deep in to the TS word and don't understand what this means.

All I want to know is if I can use your library for server side type checking in a standard NextJS 13.4.

Thank you

EDIT: I searched more and found https://nextjs.org/docs/architecture/nextjs-compiler -> so nextjs 13.4 uses SWC and based on a previous thread it is not possible to use typia with NextJS 13.4. Thank you.

**Comment by samchon** [comment]
Not possible with SWC
