### ISSUE TITLE
Provide a Typeprovider similar to fastify-type-provider-zod

### ISSUE THREAD

**Issue by Uzlopak** [samchon/typia#806]
## Feature Request

Provide a typia typeprovider for fastify like fastify-type-provider-zod.

fastify-type-provider-zod is actually very simple. So I assume it could be used as a template. But I wonder, how you could extract the json schema from typia as typia is using json schema v4 and not v7

**Comment by samchon** [comment]
Typia will support fastify like nestia case.

May released at next month.

- https://github.com/samchon/schedules
- https://github.com/samchon/nestia

**Comment by Uzlopak** [comment]
You have a new package?

**Comment by samchon** [comment]
Yes, it would be a new package

**Comment by martin-hason-ls** [comment]
Any news? A new package doesn't exist.

**Comment by samchon** [comment]
I can't be sure when, and I might never even start.

Just recommend to use `nestia`.
