### ISSUE TITLE
One Typescript Transformer to run them All

### ISSUE THREAD

**Issue by M-jerez** [samchon/typia#809]
# Discussion: One Typescript Transformer to run them All
 
Hello, I been reading a bit after discovering the [typescript-needs-types](https://github.com/akutruff/typescript-needs-types) repo and Looks like the TS team will never emit type data to be used at runtime.

There are currently 2 approaches to solve validation which i suppose is the main use case.
1 - Libraries that that declare an schema and then infer a type from that schema. i.e: zod, valibot, etc...
2 - Libraries that use Typescript Transformers to read the AST and either modify the js output or emit type metadata.

As the TS team would never emit types metadata Think we could identify the libraries that use Typescript Transformers and create a single package that suits every current existing library requirements and use that single one instead duplicated efforts. (Just for the part that parses the AST and eemits code or metadata)

I've personally have investigated two libraries that uses typescript transformers, [Typia](https://github.com/samchon/typia) and [Deepkit](https://github.com/deepkit/deepkit-framework) (from what I can see these two are that mayor players using typescript transformers).
These two as well have different approaches. Typia emmits custom validation functions while Deepkit emits bytecode representing the type metadata.

Maybe we could create a well documented package that boths emits metadata and use a visitor pattern or similar so can emit custom code when traversing the AST, this would cover both typia and deepkit requirement and would be the base for any other project trying to achieve something similar.

We would nne to chat with @samchom and @marcj  and check if they are up to the task. I'm not that expert on using the AST but happy to collaborate on what i can 👍

Note I've opened this same Issue in the involved repos:
* [typescript-needs-types issue 28](https://github.com/akutruff/typescript-needs-types/issues/28)
* [Deepkit issue 475](https://github.com/deepkit/deepkit-framework/issues/475)
* [Typia issue 809](https://github.com/samchon/typia/issues/809)

**Comment by samchon** [comment]
As `deepkit` is not using `ts-patch` and performing transformation by itself, no way to support both of them.

Furthermore, besides `typia` transforms function call statements, `deepkit` writes special statements to target type directly. 

Therefore, both `typia` and `deepkit` can't be compatible.


## Typia
https://typia.io/docs/validators/assert



## Deepkit
### TypeScript Source
```typescript
import { is } from '@deepkit/type';

class Something {
    public constructor(public readonly value: number) {}
}

console.log(is<Something>(new Something(5)));
```

### Compiled JavaScript
```javascript
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const type_1 = require("@deepkit/type");
class Something {
    constructor(value) {
        this.value = value;
    }
}
Something.__type = ['value', 'constructor', 'P\'2!:9"0"5'];
console.log((0, type_1.is)(new Something(5)));
```

**Comment by AlexRMU** [comment]
What about https://github.com/samchon/typia/issues/878#issuecomment-1896149792
