### ISSUE TITLE
Can Typia consume code compiled WITH Typia (with ts-patch transformers) without being in a transform environment?

### ISSUE THREAD

**Issue by matthew-dean** [samchon/typia#813]
## Question
This project seems pretty awesome. However, in comparing with other libraries that emit reflection metadata, I'm wondering if this scenario is supported:

1. I have a mono-repo with a number of independent TypeScript packages.
2. I want to compile Package A with Typia.
3. I want to import Package A into Package B. (It would import `.js` and `.d.ts` files.) Package B uses Typia to _validate_ but does not need to generate any runtime types. I also want Package A to be importable / use-able by anyone.

So, first, can Typia work with compiled libraries (i.e. Typia would not have access to Package A's AST)? Second, can any consumer of Package A use Typia to _validate_ types, but _without_ having to patch TypeScript or set up TypeScript for patching? With packages that emit metadata, this is possible, but I'm not sure how Typia works.

**Comment by matthew-dean** [comment]
## Follow-up question

Does Typia support validating type signatures for functions?

That is, say I have a function like:
```ts
function myFunc(one: Color, two?: any, three?: any) {}
```
Is there a way to validate that the arguments I want to pass into the function match the parameters defined by the function?

As in:
```ts
type ParamType = Parameters<typeof myFunc>
is<ParamType>([new Color()]) // true
is<ParamType>([null]) // false
is<ParamType>([new Color(), true, false]) // true
is<ParamType>([new Color(), true, false, true]) // false
```

**Comment by tsengia** [comment]
> 
> Does Typia support validating type signatures for functions?
>

This sounds like a function of Typescript itself and not Typia

**Comment by samchon** [comment]
About your 1st question, I'm also using like you.

About 2nd question, I'll demonstrate below playground link:

https://typia.io/playground/?script=JYWwDg9gTgLgBDAnmYBDANHA3g1BzAZzgF84AzKCEOAIiRVRoG4AoFsgVwDsBjGYCFzhgANhwIAKAB4AuOFw4gARgFMomRHIXK1ASi2LVUbCzhm4UFTA5QhUuAGo4iVsTb0VcAAqooqEAAqyJ4AvN6+-lZqBAA8HhBkwmIEAHys9GgAdDyWqDAqAJKxPn6BwSkSukxAA
