### ISSUE TITLE
Nx monorepo + NodeJS + Typia

### ISSUE THREAD

**Issue by jose-cabral** [samchon/typia#814]
## Question
Beforehand, thank you very much @samchon  for this project!
I am astonished by the simplicity and performance of this 🚀

I successfully configured and used `Typia` in a `NodeJS` project without any issue.

I am now trying to use it in a `nx monorepo` still with a `NodeJS` app.

The setup works fine but when I call `typia.validate` it fails with this error

`Error on typia.validate(): no transform has been configured. Read and follow https://typia.io/docs/setup please.`

I've setup typia in the root `tsconfig.base.json` as mentioned in [#773](https://github.com/samchon/typia/issues/773).
I've also read through `Nestia` documentation (despite I'm not using it) and tried to add something like this to **nx** `project.json`

```JSON
"targets": {
    "build": {
      ...
      "options": {
        ...
        "target": "node",
        "compiler": "tsc",
        "transformers": [
          "typia/lib/transform",
          {
            "name": "typia/lib/transform", <--------------- not sure what to put here in my case
            "options": {
              "validate": "assert",
              "stringify": "assert"
            }
          }
        ]
      }
    },
    ...
 }
 ```

What am I doing wrong? 🤔

Note 1: I've created fresh new projects to test this
Note 2: I am using the same index.ts code for both _nx_ and _non-nx_ projects

**Comment by jose-cabral** [comment]
I was using `@nx/esbuild:esbuild` as the build `executor`, in the app's  `project.json`

```json
{
  "name": "project1",
  "$schema": "../../node_modules/nx/schemas/project-schema.json",
  "sourceRoot": "apps/project1/src",
  "projectType": "application",
  "targets": {
    "build": {
      "executor": "@nx/esbuild:esbuild",
```

It seems that executor does not allow transformers.

I was able to fix this by changing the executor to `@nx/js:tsc` (it may work with others)

```json
{
  "name": "project1",
  "$schema": "../../node_modules/nx/schemas/project-schema.json",
  "sourceRoot": "apps/project1/src",
  "projectType": "application",
  "targets": {
    "build": {
      "executor": "@nx/js:tsc",
```

Don't forget to configure the plugins in your `tsconfig.json`

```json
    "plugins": [
      {
        "transform": "typia/lib/transform",
      }
    ],
````

**Comment by samchon** [comment]
I'll bookmark your comment, and try it by myself, and update setup guide of `typia`.

Thanks for studying.
