### ISSUE TITLE
Add support for Bun runtime / package manager

### ISSUE THREAD

**Issue by manast** [samchon/typia#822]
## Feature Request

As this library's focus is performance, it would be great if it also supported Bun (https://bun.sh/), so that we can get the fastest validation library with the fastest runtime working together.

**Comment by samchon** [comment]
Not possible to support bun because it does not support transform API

**Comment by samchon** [comment]
Also, there is no performance gain even when using generation mode to execute in bun

**Comment by manast** [comment]
Why wouldn't be a performance gain if the resulting JS is executed by Bun?

**Comment by samchon** [comment]
I do not know the reason why either \o/.

**Comment by samchon** [comment]
It would he interesting study to researching the reason why like below article, but I do not have enough time to do it right now. Maybe possible at next year

https://dev.to/samchon/secret-of-typia-how-it-could-be-20000x-faster-validator-hidden-class-optimization-in-v8-engine-1mfb

**Comment by dror-weiss** [comment]
is [this transform api](https://bun.sh/docs/api/transpiler#transform) relevant to support bun?

**Comment by samchon** [comment]
You can run it on `bun` with `unplugin-typia`.

https://typia.io/docs/setup/#unplugin-typia
