### ISSUE TITLE
`addDiagnostic` return type is redundant

### ISSUE THREAD

**Issue by hax** [samchon/typia#824]
### 📝 Summary
 I'm using `typia/lib/transform` directly, the types force me to write :

```typescript
import typia from "typia/lib/transform";

// some other code...

        const emitResult = program.emit(undefined, undefined, undefined, undefined, {
            before: [
                someOtherTransformer(program),
                typia(program, undefined, {
                    addDiagnostic(diag) { return 0 }, // I'm forced to provide addDiag method
                }),
            ],
        });

```

I guess `addDiag` could be used to output diag, but it should not be forced. Further,  it's weird that `addDiagnostic`should return a number. I checked the source code, it seems it's just automatically generated by the default impl `diag => diags.push(diag)` :-P

It's easy to fix it by just wrap `{}`.

Anyway, `typia` is a great project. Thank you .

**Comment by samchon** [comment]
It is essential parameter for printing compilation errors from typia.

Below code would be helpful for you.

https://github.com/samchon/typia/blob/master/src/programmers/TypiaProgrammer.ts#L59-L113
