### ISSUE TITLE
[Question] Why schema name differ from type name when use `Type` keyword and `Partial` utiltype.

### ISSUE THREAD

**Issue by rojiwon123** [samchon/typia#826]
## Question
What is the reason for the schema name changing when declaring a Type using the Partial utility type?

```ts
interface IOriginal {
    a: string;
    b: string;
    c: string;
    d: string;
}

interface UseInterface extends Partial<IOriginal> {};
type UseType = Partial<IOriginal>;

const schemas = typia.json.application<[UseInterface, UseType]>();

// UseInterface's schema name => 'UseInterface'
// UseType's schema name => 'PartialIOriginal'
```

**Comment by samchon** [comment]
In the TypeScript type system, the statement `type` means an alias type referencing another one (similar concept with Window`s shortcut). In contrary, the statement `interface` has an independent type instance.

This is the reason why. In such reason, it would better to define DTO type as interface.
