### ISSUE TITLE
Setup downgrades from typescript@latest to typescript@4.9.5

### ISSUE THREAD

**Issue by hlovdal** [samchon/typia#827]
## Question

Yesterday I ran setup

```shell
$ npx typia setup
----------------------------------------
 Typia Setup Wizard
----------------------------------------
? Package Manager npm

npm install --save-dev ts-patch@latest
npm install --save-dev ts-node@latest
npm install --save-dev typescript@latest
npm run postinstall
$
```

and everything was like expected. Today I ran setup again (to regenerate `package-lock.json` in an interactive rebase)

```shell
$ npx typia setup
Need to install the following packages:
  typia@5.1.3
Ok to proceed? (y) y
----------------------------------------
 Typia Setup Wizard
----------------------------------------
? Package Manager npm

npm install --save-dev ts-patch@latest
npm install --save-dev ts-node@latest
npm install --save-dev typescript@4.9.5
npm run postinstall
```

and suddenly the typescript version is downgraded. Is this expected?

Looking into all commits (`git reflog -p -G typia -- package.json | grep typia | sort -u`, same for `package-lock.json`), the version installed has always been 5.1.3, so it is not that I used to have 5.0.5 and then updated.

And since currently there are no commits present after the 5.1.3 release (which was done earlier yesterday) there are no logical explanation for the difference in behaviour.

**Comment by samchon** [comment]
It is because you run the setup command without installing typia.

By the way, I also need to update the setup wizard, because typescript 4.9.5 is no more required, and ro prevent special bug like your case.
