### ISSUE TITLE
Participate in Hacktoberfest

### ISSUE THREAD

**Issue by tsengia** [samchon/typia#830]
## Feature Request
Can this repository be registered to participate in [Hacktoberfest](https://hacktoberfest.com/) this year?

I believe to register Typia for Hacktoberfest, you would need to do the following (based upon instructions [here](https://hacktoberfest.com/participation/#maintainers)):
- Add the `hacktoberfest` topic to the repo
- Apply `hacktoberfest` label to issues that can be taken for Hacktoberfest

I am personally planning to work on getting Typia to work with React/Svelte (#812), and to figure out #238 (which may be a non-issue).

**Comment by samchon** [comment]
I'll do this at tomorrow, and ask you if need help.

**Comment by samchon** [comment]
Have done, check it plz

**Comment by tsengia** [comment]
Thank you!
