### ISSUE TITLE
typia should support custom validate function

### ISSUE THREAD

**Issue by loynoir** [samchon/typia#841]
### feat

Validate custom type with custom function

```ts
import { Opaque } from 'type-fest'
import typia, { tags } from 'typia'

type Even = Opaque<number, 'Even'> & tags.customIs<typeof isEven>
```

### problem

Currently, seems no way to validate custom type with custom function, using typia.

```ts
import { Opaque } from 'type-fest'

type Even = Opaque<number, 'Even'>
type Odd = Opaque<number, 'Odd'>

function isEven(input: unknown): input is Even {
  return typeof input === 'number' && input % 2 === 0
}

function isOdd(input: unknown): input is Odd {
  return typeof input === 'number' && input % 2 === 1
}

interface Foo {
  a: Even
  b: Odd
}

function isFoo(input: unknown): input is Foo {
  return typeof input === 'object' && input !== null && 'a' in input && isEven(input.a) && 'b' in input && isOdd(input.b)
}

export { isFoo }
```

### suggestion

```ts
import { Opaque } from 'type-fest'
import typia, { tags } from 'typia'

type Even = Opaque<number, 'Even'> & tags.customIs<typeof isEven>
type Odd = Opaque<number, 'Odd'> & tags.customIs<typeof isOdd>

function isEven(input: unknown): input is Even {
  return typeof input === 'number' && input % 2 === 0
}

function isOdd(input: unknown): input is Odd {
  return typeof input === 'number' && input % 2 === 1
}

interface Foo {
  a: Even
  b: Odd
}

const isFoo = typia.createIs<Foo>()

export { isFoo }
```

**Comment by samchon** [comment]
No way to do it on compile time.

Current type tag is the best way I can do at now.

**Comment by loynoir** [comment]
@samchon 

Why not possible?

I mean, just infer the custom function, `typia` don't need to implment the code logic.

Isn't it just need to get substring from that location?

Compiler Implement

```ts
function infer(type: "number & tags.customIs<typeof isEven>") {
  return "isEven"
}
```

Input

```ts
interface Foo {
  a: number & tags.customIs<typeof isEven>
}

const isFoo = typia.createIs<Foo>()
```

Output template

```ts
interface Foo {
  a: Even;
}

function isFoo(input: unknown): input is Foo {
  // template
  const infer_is_Foo_a = {{infer("number & tags.customIs<typeof isEven>")}};

  return (
    typeof input === "object" &&
    input !== null &&
    "a" in input &&
    infer_is_Foo_a(input.a)
  );
}
```

**Comment by samchon** [comment]
This is not such easy thing as you think. The idea that referencing the custom function seems like a good idea if not consideing how to implement, but there had been enough reason why typia is guiding users to define the typia.tags.TagBase type.

If you cannot understand the reason why, it would be better to challenge the compiler API. At first, the typeof statement would be converted to the primitive type definition, and the target function statement be erased in the compiler API. During the steps to reaching to the phenomenon and studying the reason why, you may understand.
