### ISSUE TITLE
Runtime size

### ISSUE THREAD

**Issue by djMax** [samchon/typia#849]
## Question
I don't THINK this is answered in docs or issues, but I apologize if it is. I would like to use Typia to generate validators for server configuration. At 3+MB, it would be a non-trivial tax to pay compared to the rest of our application infrastructure. I would assume that the validator RUNTIME would be a lot smaller than the code generation and the rest of the infra. Is there any plan to split these or to allow dependency-free validator generation?

**Comment by samchon** [comment]
You're meaning that generating validation code not in the compile time, but in the runtime?

I'm sorry but I've no plan to do it right now.

By the way, as I'm planning to provide a type info method (`typia.metadata()`), your suggestion can be done in someday, just by combining components of `typia`. However, it would not be done in this year, as my plan is full.

**Comment by djMax** [comment]
We are generating validation code at build time but that validation still yields a require of the typia module, so we would have to include the whole module in runtime. Maybe we could do some bundling to stop that, but that's more work than just a separate package for runtime usage. I assume the runtime validation components are a very small part of the overall package.

**Comment by djMax** [comment]
I built a thing for this that makes a standalone bundle of about 170k for a typical validation: https://github.com/sesamecare/typia-standalone-validator
