### ISSUE TITLE
Why we get "non-specified generic argument"?

### ISSUE THREAD

**Issue by sgpinkus** [samchon/typia#850]
## Question
I'm trying to use typia to get typescript to recognise a type assertion. Like this:

```
import typia from "typia";

interface Point {
  x: number;
  y: number;
  tag?: string;
}

function x(v: unknown) {
  v = <Point> typia.assertEquals<Point>(v); // Does not work, v is still unknown according to typescript.
  v = typia.assertEquals<Point>(v) as Point;  // Does not work, v is still unknown according to typescript.
  _assertEquals<Point>(v); // Does not work, typia compile error: "non-specified generic argument"
  _assertPoint(v); // Works.
 console.log(v.x + v.y);
}

function _assertPoint(v: unknown): asserts v is Point {
  typia.assertEquals<Point>(v);
}

function _assertEquals<T>(v: unknown): asserts v is T {
  typia.assertEquals<T>(v);
}
```

Would be great if the 3rd form worked (generic) otherwise have to write specific assertion function for *every* type. Why we get "non-specified generic argument"? Is there another way?

**Comment by KristjanTammekivi** [comment]
https://github.com/samchon/typia/issues/125

**Comment by andymac4182** [comment]
You might need to use the `createAssert` function https://typia.io/docs/validators/assert/#reusable-functions
I found a few spots if we needed to do that to get the right types.

**Comment by sgpinkus** [comment]
Thanks @andymac4182. Wasn't immediately obvious, but ended up doing that - instead of generic, encode type in validator function and pass that around.
