### ISSUE TITLE
The change of Comment Tags is not reflected

### ISSUE THREAD

**Issue by davidhamrak** [samchon/typia#852]
The change of Comment Tags is not reflected in the typia validator if there is no other change in the type -> name or type of any field. However, the change is reflected in Swagger docs.

I know the Type Tag is recommended but maybe it is good to know about it.

However, I can't confirm, if this is an issue related to my configuration.

**Comment by samchon** [comment]
TypeScript compiler does not re-analyse the source file only when comments being updated.

It is one of the reason why I have developed type tag system in typia.

**Comment by davidhamrak** [comment]
Okay, thank you, make sense
