### ISSUE TITLE
Why Typia doesn't work via ts-node?

### ISSUE THREAD

**Issue by sgpinkus** [samchon/typia#857]
## Question
My Typescript project using Typia builds and runs successfully. But trying to run anything that touches Typia via ts-node give error like:

> Error on typia.assertEquals(): no transform has been configured. Read and follow https://typia.io/docs/setup please. at halt (/home/node/node_modules/typia/src/module.ts:659:11), at Object.assertEquals (/home/node/node_modules/typia/src/module.ts:257:5)

I've followed the instructions at said link (as stated, project builds and runs, it's just trying to run via ts-node that doesn't work). Couldn't find much on how to run with ts-node. AFAICT only thing you have to do is set the ts-node compiler option to [ts-patch/compiler](https://github.com/nonara/ts-patch#method-1-live-compiler)? My tsconfig.json is below.

```
{
  "compilerOptions": {
    "emitDecoratorMetadata": true,
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "module": "commonjs",
    "isolatedModules": true,
    "moduleResolution": "node",
    "noImplicitAny": false,
    "outDir": "./dist/",
    "strict": true,
    "lib": [
      "ESNEXT",
      "DOM"
    ],
    "target": "ES6",
    "useDefineForClassFields": true,
    "resolveJsonModule": true,
    "sourceMap": true,
    "baseUrl": ".",
    "paths": {
      "@/*": [
        "./src/*"
      ],
      "@package": [
        "./package.json"
      ]
    },
    "plugins": [
      {
        "transform": "typescript-transform-paths"
      },
      {
        "transform": "typia/lib/transform"
      }
    ],
    "strictNullChecks": true
  },
  "include": [
    "src/**/*.ts",
    "scripts/*.ts"
  ],
  "exclude": [
    "node_modules/*",
    "**/*-aot.ts"
  ],
  "ts-node": {
    "compiler": "ts-patch/compiler",
    "transpileOnly": true,
    "require": [
      "typescript-transform-paths/register"
    ]
  }
}
```

**Comment by samchon** [comment]
Because of `transpileOnly` option

**Comment by sgpinkus** [comment]
> Because of transpileOnly option

Thanks for quick reply @samchon. Thought it might be related to that option but if I disable it I get weird errors from ts-node like it's trying to compile already compiled code. 

```
npm exec -- ts-node src/index.ts 
/home/node/node_modules/ts-node/src/index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
src/rest-api.ts:25:7 - error TS2451: Cannot redeclare block-scoped variable 'config_1'.

25 const config_1 = __importDefault(require("./config"));
         ~~~~~~~~

  src/index.ts:20:7
    20 const config_1 = __importDefault(require("./config"));
             ~~~~~~~~
    'config_1' was also declared here.
src/rest-api.ts:32:22 - error TS2683: 'this' implicitly has type 'any' because it does not have a type annotation.

32     return __awaiter(this, void 0, void 0, function* () {
                        ~~~~
src/rest-api.ts:65:22 - error TS2683: 'this' implicitly has type 'any' because it does not have a type annotation.

65     return __awaiter(this, void 0, void 0, function* () {
                        ~~~~
src/rest-api.ts:86:55 - error TS18046: 'e' is of type 'unknown'.
```

**Comment by sgpinkus** [comment]
Do I need to add something to `ts-node` tsconfig.json `require` array like [typescript-transform-paths](https://github.com/LeDDGroup/typescript-transform-paths#3-usage)?

**Comment by samchon** [comment]
The errors are came from `typia`. 

Just remove the `ts-node` property from `tsconfig.json`, and run the `ts-node src/index.ts` command.

After that, tell me the result please.

**Comment by sgpinkus** [comment]
If I completely remove `ts-node` section from `tsconfig` it works! No idea why but thanks!
