### ISSUE TITLE
how can I execute the code generated by the playground?

### ISSUE THREAD

**Issue by opensas** [samchon/typia#859]
## Question

I'd like to be able to quickly run this code (for example) to check how typia works, just like we can currently do with Typescript playground:

```typescript
import typia, { tags } from "typia";

interface IMember {
    id: string & tags.Format<"uuid">;
    email: string & tags.Format<"email">;
    age: number 
        & tags.Type<"uint32"> 
        & tags.Minimum<20> 
        & tags.ExclusiveMaximum<100>;
    parent: IMember | null;
    children: IMember[];
}

const check = typia.createValidate<IMember>();

const res = check({
    id: 'id',
    email: 'email@gmail.com',
    age: 21,
    parent: null,
    children: []
})

console.log(res)
```

Meaning, I don't only want to see the generated javascript output, I also want to execute and see the output of `console.log(res)`

it seems like currently the playground is missing a `Run` option like typescript's playground has

(if that's the case I can turn this question into a feature request)

second question: what is the most straightforward way to create a project to test the above code? (Ideally some online option, that wouldn't require me to install / run anything on my computer, perhaps with gitpod or something similar)

**Comment by samchon** [comment]
As the playground code actually requires importing the `typia` library, I don't know how to do it yet.

Hope someone to help this.

**Comment by ryoppippi** [comment]
@samchon 
Is this issue solved?
