### ISSUE TITLE
How to use Typia with Next.js

### ISSUE THREAD

**Issue by karimpanacci** [samchon/typia#860]
Hi, I'm trying to set up Typia with Next.js but I can't find a way to make Typia work when I start Next.js with "next dev"...

Can you explain to me how I have to set things up so that when I start "next dev" typia starts the compilation/generation?

I was thinking of doing the following thing:
When I start the script with "npm run dev" this happens:

- copy all project file inside typia_build folder
- start generation of typia with npx typia generate inside typia_build
- start nextjs with "next dev" inside typia_build

The only problem is to copy all the node_modules that are heavy and take too long, do you have any ideas?

**Comment by karimpanacci** [comment]
Looks like I managed to use Typia with Next.js 14
It works on both the client side and the server side, I used the following configurations on next.config.js:

```
/** @type {import('next').NextConfig} */

const nextConfig = {
  webpack: (config) => {
    config.module.rules.push({
      test: /\.(tsx|ts)$/,
      exclude: /node_modules/,
      loader: 'ts-loader',
    });
    config.resolve.extensions = ['.tsx', '.ts', '.js'];

    return config;
  },
};

module.exports = nextConfig;
```

Also I had to add these 2 options on tsconfig.json:`"allowJs": false,
"noEmit": false,`

The important thing was noEmit, but tsconfig gave me an error and the only way I found to fix it was to put allowJs on false


UPDATE:
There is some problem using server actions, Typia works perfectly, nextjs not... surely this configuration performs the compilation incorrectly, I unfortunately don't understand much about it, I went a bit of a try... but actually it seems that there is a way to use typia with nextjs using the transformation mode, @samchon can you give me a hand?

I would love to use typia in this project that will soon go into production, but I don't know how to do it...

**Comment by bradennapier** [comment]
If you are emitting it probably seems to you like it is working but it is not in reality.  The emitted typescript is not used by nextjs they compile using swc which wouldn't support this.  

Basically the types probably work fine even without any changes to your nexxt config -- but next uses their own compiler and everything so you'd almost surely need to use the generation method to build typescript from the typescript then pass that to nextjs for it to work. 

Basically best if you use a monorepo and have that setup but you could manage without doing that. 

Otherwise typia would need to have a plugin for swc which would be awesome for sure

https://nextjs.org/docs/architecture/nextjs-compiler#swc-plugins-experimental


This uses rust to transform the project so it is def possible and it would be lightning fast
https://github.com/swc-project/plugins/blob/main/packages/transform-imports/transform/src/lib.rs

Although as pointed out in the docs - if they strip all type information even from the plugins, which they probably do, then i doubt much can be done.

**Comment by karimpanacci** [comment]
@bradennapier I understand... but how can I make it work with the generation mode?

Because I wish I could use it in development mode too... so I should find a way to do so that every time nextjs finishes recompiling the project it runs the script typia generate...

But clearly in next dev mode the compilation happens every time a file changes automatically... how can I add "typia generate" script that modifies the build every time?

**Comment by MarArMar** [comment]
@bradennapier did you manage to make it work on NextJS with a monorepo ?

I tried with Turborepo / Sveltekit but Typia seems to not be working : 

https://github.com/samchon/typia/issues/873

**Comment by ristomatti** [comment]
**Disclaimer**: I've been checking this repo every once in a while to see how it evolves but I have not yet tried typia at all.

@karim2012 With the disclaimer out of the way, I've been watching the repo to pick any signs of Next.js support in one way or another. Hence, this thread seems interesting. While we're not using typia on my current project, we are using graphql-codegen.

The way we use it in dev mode is  simply by having two terminals open. One is running `next dev` and on the other a `nodemon` watching changes on `*.graphql` and triggering code generation on changes. The codegen will output the generated filed into a directory within the Next.js app, so it in turn hot reloads when the generated files changes.

Could something like this could work in this case as well?

**Comment by karimpanacci** [comment]
@ristomatti I had thought about this solution too, but there is a passage that is not clear to me...

Let's make a guess... I have my page.tsx file where I write a typia function inside it...

As soon as I save the file, nodemon activates and trigger the code generation... now the problem is:

Where will the output be generated? Because clearly you can't overwrite the file you were developing on, so you'll have to direct the output to another folder, but that doesn't work anymore since there would be problems with the imports of the files since they changed path...

The only way to make this thing work is that every time a file is edited you copy the entire project to another folder, run the generation and clearly next dev needs to be started to that new folder... but it seems very inefficient to me... like this:

root
..|-- generated_project (output of typia generate)
..|-- project
.........|-- node_modules
.........|-- app
.........|-- components
.........|-- etc...

Now what has to happen is that you start next dev on the generated_project folder.
And every time a file is modified within the project folder, it is generated using ./project as input and ./generated_project as output

But that way you have to copy all the node_modules too or am I wrong?

**Comment by ristomatti** [comment]
@karim2012 As said earlier, I've got no experience of typia so I've only got a vague idea how it works. We're still stuck on the `pages` router as well. I just made the assumption you're using it on an `/api` endpoint.

It still sounds like you're overcomplicating this though. Using it directly on a route file (or perhaps even in a `.tsx` file) doesn't sound like the best location for anything you'll be generating. I'd try to extract the logic into a separate file. Try moving the input file outside the dir watched by Next.js and just the generated file(s). Try to refactor your code so that you'll import the generated code into your `page.tsx`.

**Comment by karimpanacci** [comment]
@ristomatti Sorry, now I've fixed the file tree that I tried to describe in my previous comment,
Anyway no I can't do as you say, because I have the following situation, I'm using the server actions and the router app...

So I have a server actions done like this:


```
"use server"

export async function updateUser(userData: Partial<User>, userId: string){
  typia.assert<Partial<User>>(userData)
  // or typia.assert(userData) it's the same thing


  // update data to database
  await prisma.user.update({
    where: { id: userId},
    data: userData
  })
}

```

So I will have a lot of typia calls scattered throughout the project, and it would be too inefficient for me to have the validation code in one place...

**Comment by karimpanacci** [comment]
@ristomatti The only thing that comes to my mind is to "overwrite" in development mode the typia package with a typia.assert function that does nothing... like this:

```
export function assert(data:any){
}
```

And then somehow make sure that when the build is done (in production mode) the actual typia package is used ...

**Comment by ristomatti** [comment]
@karim2012 Does the app router break if you'd move the validation into a function call in a wrapper function? Or is it possible to wrap the function containing the whole update function in a higher order function? I can see how this would likely create enough complexity to warrant the use or typia though.

**Comment by ristomatti** [comment]
If you can't get anything else than the overwrite strategy working, you can could move the line that calls typia into an exported function which you conditionally define it as a `noop` function based on the value of `process.env` rather than overwriting the whole file?

**Comment by karimpanacci** [comment]
@ristomatti I could do something like this:

lib/typia.ts
```
import prodTypia from 'typia';

const devTypia = new Proxy(
  {},
  {
    get: () => (...args: any) => {},
  }
) as typeof prodTypia;

const typia = process.env.NODE_ENV === 'development' ? devTypia : prodTypia;
export default typia;
```

And always use typia from the lib/typia.ts file...
I believe this could be the solution to the problem

**Comment by ristomatti** [comment]
> And always use typia from the lib/typia.ts file...
> I believe this could be the solution to the problem

This is essentially what I meant with `noop`. `Proxy` is a clever trick for this purpose. I'll also note that I see the issue better now, (I was answering from mobile yesterday and missed a few details). It would definitely remove most of the convenience provided by typia if you'd have to define a separate validator function for each endpoint.

**Comment by ristomatti** [comment]
@karim2012 I see you've closed this. Was the last snippet the solution you went with in the end? 

Personally, I think it's still a workaround. It doesn't allow fast iterative testing/development cycle if it only works on a product build. Taking into account the huge popularity of Next.js, it'd be great to have an usage example as part of the documentation. Please consider reopening the issue.

**Comment by karimpanacci** [comment]
@ristomatti Hi, yes in the end I went with the last snippet of code, personally it's fine with me too since I only have to use typia to prevent an attacker from sending data that doesn't meet expectations, So I don't really need to use typia in development mode but okay, I'll reopen the issue

In any case, thank you very much because if we have come to this alternative solution it is also thanks to you!

**Comment by ryoppippi** [comment]
https://typia.io/docs/setup/#unplugin-typia
Hi guys!
You can check this out

**Comment by ryoppippi** [comment]
@samchon 
Same as https://github.com/samchon/typia/issues/812#issuecomment-2175598578

**Comment by samchon** [comment]
Great
