### ISSUE TITLE
Make clear that Typia does not perform class conversion

### ISSUE THREAD

**Issue by a-kla** [samchon/typia#869]
## Example

[⏯ Playground Link](https://typia.io/playground/?script=JYWwDg9gTgLgBDAnmYBDANHA3g1BzAZzgF84AzKCEOAIiRVRoG4AoF4AOxgFMozUAxtzgBJALLcQAI17YWcBXGAATAFxwCMKJzxwAZLkIA6AGLQQqGAB4aAV1sqaAPlaK4k1MAA26zdo66BjD4BKbmljYe3s6uivjc6hy20rLybopBIUYAKsjcNg5cAMwATM5waen6hqFinKDJViUADE4VVQqZxgCiAB4CXrYEwABu3GKovQ0gVgCMza2xCmCoUNxc6uKSMlBwAD5wSV5eS3ACABbeymscmxIpUADaALqnbpVwUsCw58qWCXAACL-U4AelBcDWAlQXgEti8-zgqA4ykh3BgtigHCReGEQx0CEuoS+Pz+PFOtjAZO4AEFcQAKACUqiSDxYxDY4IAtDyuSxwXAAGo0gAyIkBNOyIgA8gA5fmg3l8+hoIwCNb-EQEKxbB5OJmsBVKhVwABKNNlgOlYiNvJYAggHE0cFxMFNyOUVDgAF4EMhVeruP93SiqDr7jt9YzDdy7QKAFIAZTltp59sdzpgEHjBEdPr9DCMACtcxw1RqeImtDpgGREOHtrwo6wHU74BQqDm876Vahi6Xy0GeDSCAReDAAAqrMcNvUGzmKuMQiem6XZaUAYWlIrgACEAKomEzdU2pvkm3tGMCULNSWxkQf-bocB3KfK6yPz0EAKhYAD0ALREAIBGAkBQIc4IAAdyIVBDmAIQ4G6KBKF2MREwAcVUNg3EAMgI4FsJ1KUgWBuFRehhDfHgBB4ZQcMULlRAjXgjBJGBfn+dRgR4D5GM9bgiA4CB4AIYjoHgbjhAoow4H3McNGrAIC2EThNCDZQjDYb9QU5b891seAhPgdjhC7bEVlgdRtJYbhehI+BW2dMzsgE+BfSZH02iwNIvHRSEPS9X1XRDT0QHnBRfPgKAApAEp8w7EAzPpLMkui0MQEZaN6J-NIYAIekSiKAA2AB2RkkJQ6BsIUNLQvUHB8LYjieC4kECKpf46QBDhuDGKAmBINJaqoEp6rgRrvnY6lfEUvABspakusSXreAGjk0lssBuBosjqv89KfW9X1htitIPTgXItvzBrPkm5qAUk+aOuHBlmUOZIdjWtJrJq9FMWxekTsO46YpKLKOSAA) <= first take a look at this

## Feature Request

Please update the Documentation and point out that Typia only works well with primitive types.

It's frustrating if you use a Validator to prevent runtime errors but  just get them on another unexpected Place.

It's known that Typia don't work with classes (creates a Object without the methods).
@ https://github.com/samchon/nestia/issues/431
> Current `nestia` does not performan class conversion, and recommends to use pure interface type instead.

But no Words about it in the Typia Documentation.

And I don't understand why `typia.createRandom<Date>()` returns to a valid Date class but
 `typia.json.assertParse<Date>(new Date().toISOString());` asserts a string as Date.

**Comment by samchon** [comment]
Got it, will write the word that typia is not write the intanceof statement.

**Comment by samchon** [comment]
![image](https://github.com/samchon/typia/assets/13158709/0f180173-a5ee-4466-b466-ff965978ade2)

New section "Restriction" would be newly added at v5.3 update

**Comment by AlexRMU** [comment]
Close as completed?
