### ISSUE TITLE
Error recovery?

### ISSUE THREAD

**Issue by hax** [samchon/typia#870]
## Feature Request

Is it possible to support error recovery strategy? 

For example, if some fields are invalid as schema, instead of failing, we might choose to coercing it (eg. the field should be in the range 1~10, we got 12,  clamp it to 10), drop it (if it's not required), give it a default value, or some customized recovery logic.

**Comment by samchon** [comment]
I can't understand what you want.

**Comment by AlexRMU** [comment]
He wants the possibility of autocorrection (autofix, autorepair):
```ts
type T = number & tags.Minimum<10>;
```
If the input number is less than 10, it will be replaced by 10, there will be no error.

He can't do that now, and he doesn't really need to.
