### ISSUE TITLE
generate wildcards

### ISSUE THREAD

**Issue by roderik** [samchon/typia#871]
## Feature Request

Some context:

- nestjs app
- about 50 modules in one "nx package"
- using swc so need to use generation
- every module has a folder called config-templates that i want to generate to a config folder

I'm using NX as a monorepo tool, so i created this task in each of the module

```
    "codegen": {
      "executor": "nx:run-commands",
      "inputs": ["{projectRoot}/**/config-templates/*.ts"],
      "outputs": ["{projectRoot}/**/config/*.ts"],
      "options": {
        "commands": [
          {
            "command": "pnpm typia generate --input libs/shared/nest/entities/src/lib/user/config-templates --output libs/shared/nest/entities/src/lib/user/config --project libs/shared/nest/entities/tsconfig.json"
          },
          {
            "command": "pnpm typia generate --input libs/shared/nest/entities/src/lib/personal-access-token/config-templates --output libs/shared/nest/entities/src/lib/personal-access-token/config --project libs/shared/nest/entities/tsconfig.json"
          },
          {
            "command": "pnpm typia generate --input libs/shared/nest/entities/src/lib/abstract/config-templates --output libs/shared/nest/entities/src/lib/abstract/config --project libs/shared/nest/entities/tsconfig.json"
          }
        ]
      }
    },
    ```

But this is quite annoying to maintain.

If i could use a glob pattern i could do something like 
```
pnpm typia generate --input libs/shared/nest/entities/src/lib/**/config-templates --output libs/shared/nest/entities/src/lib/**/config --project libs/shared/nest/entities/tsconfig.json
```

Obviously the output bit will not work because what is the glob in that context, but some logic that makes sense could certainly be applied?

**Comment by samchon** [comment]
Supporting wildcard is not a hard problem, so it may possible at next month. 

By the way, Target files are belonged into one `tsconfig.json` file? It seems not. Also, I think it would much better to using standard TypeScript compiler for convenient development. And, if you're using `typia` in the NestJS for data validation, I recommend to using `nestia` instead of configuring such hard.

https://nestia.io/docs
