### ISSUE TITLE
Support for MongoDB schema

### ISSUE THREAD

**Issue by marcesengel** [samchon/typia#875]
## Feature Request

We'd like to generate [MongoDB json schema](https://www.mongodb.com/docs/manual/reference/operator/query/jsonSchema/#std-label-jsonSchema-keywords) just like the currently supported types `ajv` and `swagger`.

Would you be open to merge this, provided we prepare a PR? Thanks in advance for your response!

**Comment by samchon** [comment]
I do not know the mongo schema being composee, but Welcome your PR

**Comment by sourav-bhar** [comment]
@marcesengel – been thinking about this exact use case. Will what you're working on also work with mongoose schemas? I think this would be really useful for folks working with mongodb / mongoose.
