### ISSUE TITLE
Generic type schema

### ISSUE THREAD

**Issue by rracariu** [samchon/typia#878]
It will be very helpful to have something similar to `application` that would generate a Typia specific schema, kind of like an AST representation.

Right now, someone can use `application` to generate JSON schemas, but those schemas don't do a great job of capturing all the aspects of the Typia tags ('x-typia-*' properties are not that nice).

For example, this would be one possible way to solve it:

```typescript
interface Person {
 dob: string & tags.Format<"date-time">
}

const schema = typia.schema<Person>() // get the Person schema
/*
{
  type: 'Person',
  properties: {
    dob: {
      type: 'string',
      tags: {
        format: 'date-time'
      }
    }
  }
}
*/
```
Not limited to, but such a schema would be helpful for:
- schema extensibility, one can use the Typia schema to generate other schemas
- form validation
- UI generation for a type (i.e. automatic forms)
- cross language generation, for example code generation for language inter-operability (Rust<->Typescript | Go<->Typescript).
- a form of type serialization

**Comment by samchon** [comment]
How about this feature? 

`typia` had supported `typia`'s own schema structure, but I've not documented it yet, due to no one had interested in.

```typescript
import { metadata } from "typia/lib/reflect";

const schema = metadata<[A, B, C]>();
```

**Comment by rracariu** [comment]
> How about this feature?
> 
> `typia` had supported `typia`'s own schema structure, but I've not documented it yet, due to no one had interested in.
> 
> ```ts
> import { metadata } from "typia/lib/reflect";
> 
> const schema = metadata<[A, B, C]>();
> ```

OK, tested on the playground and looks to be working nicely. I guess having some documentation on the metadata related types would be helpful in general.
Thanks!

**Comment by patelvanita360** [comment]
const schema = metadata<[A, B, C]>();
how to use this schema in typia validate function ?

**Comment by matjaeck** [comment]
+1. My use case is to use `FormData.get` without having to hardcode field names.

This was a handy feature in Zod:

```
export function getFormDataByObjShape<T extends z.ZodRawShape>(formData: FormData, schema: z.ZodObject<T>) {
  return Object.fromEntries(
    Object.keys(schema.shape).map(
      field => [field, formData.get(field)]
    )
  );
}
```

**Comment by samchon** [comment]
> +1. My use case is to use `FormData.get` without having to hardcode field names.
> 
> This was a handy feature in Zod:
> 
> ```
> export function getFormDataByObjShape<T extends z.ZodRawShape>(formData: FormData, schema: z.ZodObject<T>) {
>   return Object.fromEntries(
>     Object.keys(schema.shape).map(
>       field => [field, formData.get(field)]
>     )
>   );
> }
> ```

This may be what you want:

https://typia.io/docs/misc/#query-functions
