### ISSUE TITLE
Any way to ignore a property check?

### ISSUE THREAD

**Issue by Devidian** [samchon/typia#880]
Hey, i dont know if i do something wrong, so i first have a question:

My env is nest.js / nestia and i have an interface using a "FeatureCollection" type (GeoJSON) but after some update of typia /nestia i get the message "$any is not a function". My only solution for now is to remove the property from the interface because setting it to any causes the same error.

Q: Is there any way to ignore a property type / not validate it?

**Comment by samchon** [comment]
Oops, I'm sorry, but this is my mistake. 

When accepting a suggestion of "assertClone" option on the `TypedBody()` decorator function (https://github.com/samchon/nestia/issues/672), I've taken a mistake that have not considered the `any` typed property case from the request body DTO. I think you're using the `assertClone` option, and there's an `any` typed property on your DTO.

I'll fix this issue immediately, and publish a new version of `@nestia/core`. Wait for a while please.

**Comment by samchon** [comment]
@Devidian Upgrade to the latest version of `@nestia/core`, or run the `npx nestia setup` command.

Then, this bug would be fixed.

**Comment by Devidian** [comment]
Hey nice, yes i've changed to assertClone just a few days ago and updated all deps :D
I'm now on vacation but i will rollback my workaround after that. Thanks for the quick fix!
