### ISSUE TITLE
Consider combining small files to reduce size on disk

### ISSUE THREAD

**Issue by cody-greene** [samchon/typia#889]
This is a large library. There are several ways to address this, but here's one cause of this problem and one solution you should consider.

Take a look at this directory:
```
$ du -shc node_modules/typia/lib/transformers/features/protobuf/*
4.0K  node_modules/typia/lib/transformers/features/protobuf/ProtobufAssertDecodeTransformer.d.ts
4.0K  node_modules/typia/lib/transformers/features/protobuf/ProtobufAssertDecodeTransformer.js
4.0K  node_modules/typia/lib/transformers/features/protobuf/ProtobufAssertDecodeTransformer.js.map
...
204K  total
```
That's size on disk. However every single file in this directory is less than 4K. The *apparent* size of this directory is:
```
$ du -sbhc node_modules/typia/lib/transformers/features/protobuf/*
334 node_modules/typia/lib/transformers/features/protobuf/ProtobufAssertDecodeTransformer.d.ts
857 node_modules/typia/lib/transformers/features/protobuf/ProtobufAssertDecodeTransformer.js
487 node_modules/typia/lib/transformers/features/protobuf/ProtobufAssertDecodeTransformer.js.map
...
29K total
```
Woah! That's a lot of space wasted because each tiny file uses a whole (4k in my case) filesystem block. Combining these tiny files would be an easy way to reduce the actual (uncompressed) size of this library.

**Comment by samchon** [comment]
If merge those small files into one, then it would hard for me to maintaining.

Also, those files you've listed up are used only when performing transformation or generation, so that does not affect to the runtime level.
