### ISSUE TITLE
AVDL Support for Interface Transformation

### ISSUE THREAD

**Issue by floriansollami** [samchon/typia#896]
Issue Description:
I'm currently using typia for transforming TypeScript interfaces into protobuf, and it's been incredibly useful for my workflow. However, in my line of work, particularly with Kafka, we often use Apache Avro IDL (AVDL).

Feature Request:
I would like to suggest the possibility of extending typia's capabilities to include support for AVDL in addition to Protobuf. This feature would greatly benefit developers who are working in environments where AVDL is a standard.

**Comment by samchon** [comment]
Similar issue with https://github.com/samchon/typia/issues/514, but not enough time to do it in nowadays.

So, it is okay to sending a PR. Anyone challenges to it.

**Comment by samchon** [comment]
Close due to no one challenges.
