### ISSUE TITLE
How to generate full swagger file

### ISSUE THREAD

**Issue by andymac4182** [samchon/typia#902]
I am working on building a wrapper for koa-router. I want to generate a full swagger file from this wrapper. 

Do you have an example of generating a swagger file completely with the URLs using Typia?

**Comment by samchon** [comment]
https://nestia.io/docs/sdk/swagger/

I'm supporting the full swagger file generation in NestJS.

You can reference the code, and develop the `koa-router` swagger generator by yourself.

https://github.com/samchon/nestia/blob/master/packages/sdk/src/generates/SwaggerGenerator.ts

**Comment by andymac4182** [comment]
Thanks :) That is a good reference :)
