### ISSUE TITLE
Prepare hook fails for NPM install without devDependencies

### ISSUE THREAD

**Issue by rene-leanix** [samchon/typia#908]
## Bug Report

The NPM prepare hook created by typia, `ts-patch install && typia patch`, fails when `npm ci` or `npm install` are executed with `--production` or `--omit=dev`, because ts-patch is a development dependency.

This could be fixed by either checking `$NODE_ENV` in the hook, which is set to 'production' for the two flags mentioned above:

- `[ "$NODE_ENV" != 'production' ] || (ts-patch install && typia patch)` or
- `[ "$NODE_ENV" = 'production' ] && exit 0; ts-patch install && typia patch`

or by checking that ts-patch has been installed:

- `[ "$(npm ls -p ts-patch)" = '' ] || (ts-patch install && typia patch)`

Alternatively, `typia patch` could check `$NODE_ENV` and install `ts-patch` if not yet installed.

**Comment by samchon** [comment]
Here document would be helpful for you.

https://nestia.io/docs/setup/#webpack

**Comment by rene-leanix** [comment]
Yes, thanks, I didn't see this:

> By the way, when removing devDependencies for --production install, never forget to add the --ignore-scripts option to prevent the prepare script.

This is a good solution and probably best practice for production builds on CI anyway. If the host repository has another script, e.g. `postinstall`, which shouldn't be skipped, it can be executed explicitly after the production install.

**Comment by zdila** [comment]
I solved it differently:

`"prepare": "if [ -d node_modules/ts-patch ]; then ts-patch install && typia patch; fi"`
