### ISSUE TITLE
Does a `@UseGuard(AuthGuard)` gets executed first before `@TypedBody<UserDTO>()`?

### ISSUE THREAD

**Issue by jymchng** [samchon/typia#909]
## Question
I have an `AuthGuard` that checks the `username` belongs to the database and its `password` is correct, guarding the controller's endpoint.

My `username` field does not allow for underscore (`_`). When I send a json body with the username having an underscore, it fails because the `AuthGuard` caught it for not having a username with an `_` in the database, but I want `typia.TypedBody<UserDTO>()` to catch it first by returning a response that a `username` should not have underscore, `_`.

Thank you.

**Comment by jymchng** [comment]
@samchon Any answer?

**Comment by samchon** [comment]
https://docs.nestjs.com/faq/request-lifecycle

Read above doc, then you may understand the reason why.

By the way, here is not `nestia`, but `typia` repo.
