### ISSUE TITLE
`IJsonApplication` Swagger version

### ISSUE THREAD

**Issue by ghost** [samchon/typia#919]
## Feature Request
``` javascript
export const eventsComponents = json.application<
  [Book, Author],
  'swagger'
>().components;
```
When comparing [3.0 to 3.1.0](https://www.openapis.org/blog/2021/02/16/migrating-from-openapi-3-0-to-3-1-0) there are some schema changes. Specifically `nullable` is considered redundant in 3.1.0. The feature request I'd make is to be able to define which version of swagger, and have the output meet the spec.

**Comment by samchon** [comment]
Welcome your PR

**Comment by samchon** [comment]
Upgrade to v6, then be ready.
