### ISSUE TITLE
Extending interface from another module

### ISSUE THREAD

**Issue by tomwidmer** [samchon/typia#921]
## Question
moduleA/index.ts

```typescript
export interface EntityBase {
  /**
   * GUID of this entity (24 hex characters)
   * @pattern ^[0-9A-Fa-f]{24}$
   */
  id: string;
  /**
   * @type int
   * @minimum 0
   */
  version: number;
}
``` 

moduleB/entity.ts
```typescript
import * as typia from 'typia';
import { EntityBase } from 'moduleA';

/**
 * Some entity
 */
export interface Entity extends EntityBase {
  /**
   * Some field
   */
  fieldA: string;
}

export isEntity = typia.is<Entity>;
``` 

I can see that there's a fundamental problem that moduleA has already been compiled by `tsc`, so there's no way for the `typia.is` transform to do it's magic. Is there any way to set up tsc compilation for the two modules so that you get proper definitions for the EntityBase fields (presumably you'd need to export something extra from moduleA)?

**Comment by samchon** [comment]
No problem when importing external type.

If your problem caused from comment tag (I think you have built modoule A with remove comments option), use type tag instead.
