### ISSUE TITLE
Can we manipulate errors ?

### ISSUE THREAD

**Issue by patelvanita360** [samchon/typia#932]
I want to make error more simple 
{
    "errors": [
        {
            "path": "$input.field1",
            "expected": "'mongoose'.Types.ObjectId"
        },
        {
            "path": "$input.field2",
            "expected": "string"
        }
    ]
}

want to make path error in human language

**Comment by samchon** [comment]
Do it yourself with `TypeGuardError` or `IValidation<T>` result, then it would be the human language.

Duplicated - https://github.com/samchon/typia/issues/854
