### ISSUE TITLE
Use `Typia`'s JSON transformation in Express application

### ISSUE THREAD

**Issue by jainChetan81** [samchon/typia#935]
## Question
How do I replace JSON.stringify() and parse() methods from `express` to `typia`'s methods
currently the api design looks like this
```
res.json({
    listingDetail: result.metaData,
    constantData: result.constant_data,
});
```
Express internally used `JSON.stringify()` when using `res.json`, How do I override this with `typia`?

**Comment by samchon** [comment]
Make a function getting functional parameter.

```typescript
export const doSomething = <T>(stringify: (input: T) => string) => {};
```

If you're inconvenient repeating the `typia.json.createAssertStringify<T>()` function call for every API endpoints, you can use another option.

1. Use Nestia with NestJS
2. Make your custom transformer library reading the `nestia` code

**Comment by jainChetan81** [comment]
I get the generic function type, it'll make it easier to use everywhere, I don't understand how `Nestia` and `NestJS` come into play here.
I am using `ExpressJS` here, is there any way to use `typia.json.stringify<T>()` in this response like
```
res.send(typia.json.stringify<T>({
    listingDetail: result.metaData,
    constantData: result.constant_data,
}));
```
@samchon

**Comment by jainChetan81** [comment]
BTW, I came here after reading this article, there is an express example code, but I didn't quite understand how to use it...
https://dev.to/samchon/i-made-express-faster-than-fastify-4h8g

**Comment by samchon** [comment]
The benchmark was done by manual mapping through `typia.json.createAssertStringify<T>()` functions.

Also, about the `nestia` case, you have to read its implementation code to follow the same way.

In personally, I just recommend to use the `nestia`.

**Comment by jainChetan81** [comment]
Will look into it, thanks
