### ISSUE TITLE
Cannot use typia with generic functions (Angular, TypeScript)

### ISSUE THREAD

**Issue by deyan-peychev** [samchon/typia#941]
I have an Angular application and I'm creating a PayloadValidationService which has a generic function that uses typia's `validateEqual` to validate objects:

```
import { Injectable } from "@angular/core";
import typia from "typia";

@Injectable({
  providedIn: 'root'
})
export class PayloadValidationService {

  validatePayload<T>(payload: object): void {
    console.log(typia.validateEquals<T>(payload)); // There will be additional functionality if the result is an error
  }

}
```

I am using the function as follows:

```
interface MyPayload {
    someValue: string;
}

@Injectable({
    providedIn: 'root'
})
export class MyService {

    constructor(private payloadValidationService: PayloadValidationService) {}
    
    myApiRequest(data: any) {
        this.payloadValidationService.validatePayload<MyPayload>(data);

        // ... 
    }
}

```

This throws the following error in the console: 

`ERROR Error: Error on typia.validateEquals(): no transform has been configured. Read and follow https://typia.io/docs/setup please.`

If I use the `validateEquals` directly with my interface and not use generics (e.g. `typia.validateEquals<MyPayload>(data)`), everything works normally without any errors.

Is there any way to make it work with generics?

---

Angular version: 17
Typia version: `"^5.4.0"`
I have run `npm install typia` and `npx typia setup`

**Comment by samchon** [comment]
Too much duplicated question, and not possible to do it.

To accomplish the feature, I've to remake Typia and TypeScript compiler entirely.

Utilize `typia.createAssert<T>()` like functions intead please.
