### ISSUE TITLE
Feature request: utility function filter

### ISSUE THREAD

**Issue by seo-rii** [samchon/typia#966]
## Feature Request
Thank you for making a good library! I suggest one feature that would be great.

My suggestion is to add a function called `filter`. This is a function that tries to satisfy the type condition of a given object. 
- If a given value matches a type, it returns the given value as it is. 
- If a given value is an object type, and there is only one way to satisfy the type by removing some fields from here, it returns the value by removing the field to satisfy the type. 
- If there is no way to convert a given object to match the type, or if there is more than one way to convert the type, an exception is thrown.

This will be useful for extracting the original value when the entered value contains a token for verification or some additional information.

**Comment by samchon** [comment]
`typia.misc.assertClone<T>()` and `typia.misc.assertPrune<T>()` functions are what you want.

- https://typia.io/docs/misc/#clone-functions
- https://typia.io/docs/misc/#prune-functions

**Comment by seo-rii** [comment]
Oh, I missed it. Sorry for bothering 😅
