### ISSUE TITLE
In a packager environment like Vite, use typia in Vue files, and just run transform for preprocessing without emit for js.

### ISSUE THREAD

**Issue by moheng233** [samchon/typia#990]
# How I got this idea
I want to make a form library that is as convenient as possible and has input validation and error prompts without template code.

He is based on `Typescript` and `Typia`, It looks like this to use.
```ts
const [field, form] = useForm({
    email: "" as string & tags.Format<"email"> & tags.MaxLength<30>,
    password: "" as string & tags.MinLength<8> & tags.MaxLength<20>
}, {
    onValidate(data) {
        return typia.validate(data);
    },
    onSubmit(data) {
        console.log(data);
        return false;
    }
});
```
```vue
<CForm :context="form">
    <InputText type="email" v-model="field.email.value"/>
    <Password v-model="field.password.value"></Password>
    <CFormSubmit v-slot="{ submit }">
        <Button @click="submit"></Button>
    </CFormSubmit>
</CForm>
```

In the process, I found out that VITE's `TypeScript2` plugin doesn't handle TS in Vue, so I added *.vue to the include path of the plugin. It worked, but because it was preprocessed by Vue and stripped of the type information, it couldn't generate the completed typia validation function.

However, if you advance the compilation process of TypeScript before the Vue plugin, then the compiler macros of Vue will not work.

So, we need a preprocessor that can run before the vue build process, handle TS with types and emit TS.

# Functional implementation
So I tried to make a demo using unplugin, which I only tested on vite.
[unplugin-vue-typia](https://github.com/moheng233/nops/tree/main/packages/unplugin-typia)
I'd like to know your thoughts and suggestions.

**Comment by moheng233** [comment]
I have a more vague idea. I think that if the validation function is generated into a separate virtual module, it can effectively speed up the build.

This would be similar to the current generate pattern, but more flexible.

**Comment by samchon** [comment]
I don't develop vue and front-end applications, so I have no insight into your suggestions. If you think the plugin you created is worthy of being widely distributed to many front-end developers, please send a PR with installation instructions in the document below.

- https://typia.io/docs/setup/
- https://github.com/samchon/typia/blob/master/website/pages/docs/setup.mdx

**Comment by ryoppippi** [comment]
I also need this for svelte

**Comment by ryoppippi** [comment]
@moheng233 
Hi! any license for your work?

**Comment by moheng233** [comment]
It will use the same MIT license as typia, and I will extract it as a separate repository soon and publish it to npm. Thank you for letting me know someone would need it



At 2024-05-24 20:56:39, "ryoppippi" ***@***.***> wrote:

@moheng233
Hi! any license for your work?

**Comment by ryoppippi** [comment]
Hi
I made a bundler plugin using unplugin based on [moheng233](https://github.com/moheng233)`bs work

[ryoppippi/unplugin-typia@main/packages/unplugin-typia](https://github.com/ryoppippi/unplugin-typia/tree/main/packages/unplugin-typia?rgh-link-date=2024-06-01T11%3A37%3A07Z)

You can try it! it works fine with frontend bundlers
