### ISSUE TITLE
generated ajv json schema for empty tuple is not valid

### ISSUE THREAD

**Issue by hax** [samchon/typia#996]
### 📝 Summary
generated ajv json schema for empty tuple is not valid.

  - **Typia Version**: latest
  - **Expected behavior**: `items` property should be `false` (or `additionalItems: false` if follow old draft)
  - **Actual behavior**: `items` property is `[]`

As json schema, [`items` property](https://json-schema.org/understanding-json-schema/reference/array#additionalitems) should be boolean or at least one member, but currently empty tuple (`type foo = []`) will generate invalid json schema `items: []`.

### ⏯ Playground Link
> #### Example Link
> https://typia.io/playground/?script=JYWwDg9gTgLgBDAnmYBDOAzKERwERIqp4DcAUGcAHYwCmUGqAxrXAJICytIARvXAG8ycEXAD0AKglxhouNIACGaCFTwAruuAATGXPli9onQC44AZxhRqAc3KyRk6Q5GLlUVfG6pgAGyOiEoYu3n5mltZUdhRyTi7ycAqErFo08Yog1KDquABMAAzpibQAHky+6ubAAG60HKgl2bgAjPmF+kEuqDa0ZlQ5fFDkcmCoULQ0Zpzcg3AAPnD9vr7DokwAFn7a41RTXLz0ANoAuuQAvhRiYgC0t9dkV+wAyg83d2SEaAB0TONqtGxzAAeaYHKAAPgAFABKchAA

### 💻 Code occuring the bug
```typescript
import typia, { tags } from "typia";

type Test = {foo: []}
const schema = typia.json.application<[Test], "ajv">();
```

**Comment by samchon** [comment]
I'll fix this bug at v6 update, developing exact JSON schema spec.

**Comment by samchon** [comment]
Completed. Upgrade to v6, then would be exact.
